// Code generated by mockery. DO NOT EDIT.

package biz

import (
	biz "github.com/acepanel/panel/v3/internal/biz"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AlertRepo is an autogenerated mock type for the AlertRepo type
type AlertRepo struct {
	mock.Mock
}

type AlertRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *AlertRepo) EXPECT() *AlertRepo_Expecter {
	return &AlertRepo_Expecter{mock: &_m.Mock}
}

// AddAlert provides a mock function with given fields: alert
func (_m *AlertRepo) AddAlert(alert *biz.Alert) error {
	ret := _m.Called(alert)

	if len(ret) == 0 {
		panic("no return value specified for AddAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*biz.Alert) error); ok {
		r0 = rf(alert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlertRepo_AddAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAlert'
type AlertRepo_AddAlert_Call struct {
	*mock.Call
}

// AddAlert is a helper method to define mock.On call
//   - alert *biz.Alert
func (_e *AlertRepo_Expecter) AddAlert(alert interface{}) *AlertRepo_AddAlert_Call {
	return &AlertRepo_AddAlert_Call{Call: _e.mock.On("AddAlert", alert)}
}

func (_c *AlertRepo_AddAlert_Call) Run(run func(alert *biz.Alert)) *AlertRepo_AddAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*biz.Alert))
	})
	return _c
}

func (_c *AlertRepo_AddAlert_Call) Return(_a0 error) *AlertRepo_AddAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertRepo_AddAlert_Call) RunAndReturn(run func(*biz.Alert) error) *AlertRepo_AddAlert_Call {
	_c.Call.Return(run)
	return _c
}

// AllRules provides a mock function with no fields
func (_m *AlertRepo) AllRules() ([]*biz.AlertRule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllRules")
	}

	var r0 []*biz.AlertRule
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*biz.AlertRule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*biz.AlertRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.AlertRule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_AllRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllRules'
type AlertRepo_AllRules_Call struct {
	*mock.Call
}

// AllRules is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) AllRules() *AlertRepo_AllRules_Call {
	return &AlertRepo_AllRules_Call{Call: _e.mock.On("AllRules")}
}

func (_c *AlertRepo_AllRules_Call) Run(run func()) *AlertRepo_AllRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_AllRules_Call) Return(_a0 []*biz.AlertRule, _a1 error) *AlertRepo_AllRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_AllRules_Call) RunAndReturn(run func() ([]*biz.AlertRule, error)) *AlertRepo_AllRules_Call {
	_c.Call.Return(run)
	return _c
}

// CertExpiry provides a mock function with no fields
func (_m *AlertRepo) CertExpiry() ([]*biz.AlertMetric, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertExpiry")
	}

	var r0 []*biz.AlertMetric
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*biz.AlertMetric, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*biz.AlertMetric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.AlertMetric)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_CertExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertExpiry'
type AlertRepo_CertExpiry_Call struct {
	*mock.Call
}

// CertExpiry is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) CertExpiry() *AlertRepo_CertExpiry_Call {
	return &AlertRepo_CertExpiry_Call{Call: _e.mock.On("CertExpiry")}
}

func (_c *AlertRepo_CertExpiry_Call) Run(run func()) *AlertRepo_CertExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_CertExpiry_Call) Return(_a0 []*biz.AlertMetric, _a1 error) *AlertRepo_CertExpiry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_CertExpiry_Call) RunAndReturn(run func() ([]*biz.AlertMetric, error)) *AlertRepo_CertExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// ClearAlerts provides a mock function with no fields
func (_m *AlertRepo) ClearAlerts() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearAlerts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlertRepo_ClearAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAlerts'
type AlertRepo_ClearAlerts_Call struct {
	*mock.Call
}

// ClearAlerts is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) ClearAlerts() *AlertRepo_ClearAlerts_Call {
	return &AlertRepo_ClearAlerts_Call{Call: _e.mock.On("ClearAlerts")}
}

func (_c *AlertRepo_ClearAlerts_Call) Run(run func()) *AlertRepo_ClearAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_ClearAlerts_Call) Return(_a0 error) *AlertRepo_ClearAlerts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertRepo_ClearAlerts_Call) RunAndReturn(run func() error) *AlertRepo_ClearAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// ClearAlertsBefore provides a mock function with given fields: t
func (_m *AlertRepo) ClearAlertsBefore(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for ClearAlertsBefore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlertRepo_ClearAlertsBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAlertsBefore'
type AlertRepo_ClearAlertsBefore_Call struct {
	*mock.Call
}

// ClearAlertsBefore is a helper method to define mock.On call
//   - t time.Time
func (_e *AlertRepo_Expecter) ClearAlertsBefore(t interface{}) *AlertRepo_ClearAlertsBefore_Call {
	return &AlertRepo_ClearAlertsBefore_Call{Call: _e.mock.On("ClearAlertsBefore", t)}
}

func (_c *AlertRepo_ClearAlertsBefore_Call) Run(run func(t time.Time)) *AlertRepo_ClearAlertsBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *AlertRepo_ClearAlertsBefore_Call) Return(_a0 error) *AlertRepo_ClearAlertsBefore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertRepo_ClearAlertsBefore_Call) RunAndReturn(run func(time.Time) error) *AlertRepo_ClearAlertsBefore_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRule provides a mock function with given fields: rule
func (_m *AlertRepo) CreateRule(rule *biz.AlertRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*biz.AlertRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlertRepo_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type AlertRepo_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - rule *biz.AlertRule
func (_e *AlertRepo_Expecter) CreateRule(rule interface{}) *AlertRepo_CreateRule_Call {
	return &AlertRepo_CreateRule_Call{Call: _e.mock.On("CreateRule", rule)}
}

func (_c *AlertRepo_CreateRule_Call) Run(run func(rule *biz.AlertRule)) *AlertRepo_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*biz.AlertRule))
	})
	return _c
}

func (_c *AlertRepo_CreateRule_Call) Return(_a0 error) *AlertRepo_CreateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertRepo_CreateRule_Call) RunAndReturn(run func(*biz.AlertRule) error) *AlertRepo_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DatabaseServers provides a mock function with no fields
func (_m *AlertRepo) DatabaseServers() ([]*biz.DatabaseServer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseServers")
	}

	var r0 []*biz.DatabaseServer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*biz.DatabaseServer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*biz.DatabaseServer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.DatabaseServer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_DatabaseServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseServers'
type AlertRepo_DatabaseServers_Call struct {
	*mock.Call
}

// DatabaseServers is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) DatabaseServers() *AlertRepo_DatabaseServers_Call {
	return &AlertRepo_DatabaseServers_Call{Call: _e.mock.On("DatabaseServers")}
}

func (_c *AlertRepo_DatabaseServers_Call) Run(run func()) *AlertRepo_DatabaseServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_DatabaseServers_Call) Return(_a0 []*biz.DatabaseServer, _a1 error) *AlertRepo_DatabaseServers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_DatabaseServers_Call) RunAndReturn(run func() ([]*biz.DatabaseServer, error)) *AlertRepo_DatabaseServers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function with given fields: id
func (_m *AlertRepo) DeleteRule(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlertRepo_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type AlertRepo_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - id uint
func (_e *AlertRepo_Expecter) DeleteRule(id interface{}) *AlertRepo_DeleteRule_Call {
	return &AlertRepo_DeleteRule_Call{Call: _e.mock.On("DeleteRule", id)}
}

func (_c *AlertRepo_DeleteRule_Call) Run(run func(id uint)) *AlertRepo_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *AlertRepo_DeleteRule_Call) Return(_a0 error) *AlertRepo_DeleteRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertRepo_DeleteRule_Call) RunAndReturn(run func(uint) error) *AlertRepo_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function with given fields: id
func (_m *AlertRepo) GetRule(id uint) (*biz.AlertRule, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *biz.AlertRule
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*biz.AlertRule, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *biz.AlertRule); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.AlertRule)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type AlertRepo_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - id uint
func (_e *AlertRepo_Expecter) GetRule(id interface{}) *AlertRepo_GetRule_Call {
	return &AlertRepo_GetRule_Call{Call: _e.mock.On("GetRule", id)}
}

func (_c *AlertRepo_GetRule_Call) Run(run func(id uint)) *AlertRepo_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *AlertRepo_GetRule_Call) Return(_a0 *biz.AlertRule, _a1 error) *AlertRepo_GetRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_GetRule_Call) RunAndReturn(run func(uint) (*biz.AlertRule, error)) *AlertRepo_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// ListAlerts provides a mock function with given fields: page, limit
func (_m *AlertRepo) ListAlerts(page uint, limit uint) ([]*biz.Alert, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListAlerts")
	}

	var r0 []*biz.Alert
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]*biz.Alert, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []*biz.Alert); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, uint) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AlertRepo_ListAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAlerts'
type AlertRepo_ListAlerts_Call struct {
	*mock.Call
}

// ListAlerts is a helper method to define mock.On call
//   - page uint
//   - limit uint
func (_e *AlertRepo_Expecter) ListAlerts(page interface{}, limit interface{}) *AlertRepo_ListAlerts_Call {
	return &AlertRepo_ListAlerts_Call{Call: _e.mock.On("ListAlerts", page, limit)}
}

func (_c *AlertRepo_ListAlerts_Call) Run(run func(page uint, limit uint)) *AlertRepo_ListAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *AlertRepo_ListAlerts_Call) Return(_a0 []*biz.Alert, _a1 int64, _a2 error) *AlertRepo_ListAlerts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AlertRepo_ListAlerts_Call) RunAndReturn(run func(uint, uint) ([]*biz.Alert, int64, error)) *AlertRepo_ListAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// ListRules provides a mock function with given fields: page, limit
func (_m *AlertRepo) ListRules(page uint, limit uint) ([]*biz.AlertRule, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRules")
	}

	var r0 []*biz.AlertRule
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]*biz.AlertRule, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []*biz.AlertRule); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.AlertRule)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, uint) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AlertRepo_ListRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRules'
type AlertRepo_ListRules_Call struct {
	*mock.Call
}

// ListRules is a helper method to define mock.On call
//   - page uint
//   - limit uint
func (_e *AlertRepo_Expecter) ListRules(page interface{}, limit interface{}) *AlertRepo_ListRules_Call {
	return &AlertRepo_ListRules_Call{Call: _e.mock.On("ListRules", page, limit)}
}

func (_c *AlertRepo_ListRules_Call) Run(run func(page uint, limit uint)) *AlertRepo_ListRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *AlertRepo_ListRules_Call) Return(_a0 []*biz.AlertRule, _a1 int64, _a2 error) *AlertRepo_ListRules_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AlertRepo_ListRules_Call) RunAndReturn(run func(uint, uint) ([]*biz.AlertRule, int64, error)) *AlertRepo_ListRules_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectNames provides a mock function with no fields
func (_m *AlertRepo) ProjectNames() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_ProjectNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectNames'
type AlertRepo_ProjectNames_Call struct {
	*mock.Call
}

// ProjectNames is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) ProjectNames() *AlertRepo_ProjectNames_Call {
	return &AlertRepo_ProjectNames_Call{Call: _e.mock.On("ProjectNames")}
}

func (_c *AlertRepo_ProjectNames_Call) Run(run func()) *AlertRepo_ProjectNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_ProjectNames_Call) Return(_a0 []string, _a1 error) *AlertRepo_ProjectNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_ProjectNames_Call) RunAndReturn(run func() ([]string, error)) *AlertRepo_ProjectNames_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function with given fields: rule
func (_m *AlertRepo) UpdateRule(rule *biz.AlertRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*biz.AlertRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlertRepo_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type AlertRepo_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - rule *biz.AlertRule
func (_e *AlertRepo_Expecter) UpdateRule(rule interface{}) *AlertRepo_UpdateRule_Call {
	return &AlertRepo_UpdateRule_Call{Call: _e.mock.On("UpdateRule", rule)}
}

func (_c *AlertRepo_UpdateRule_Call) Run(run func(rule *biz.AlertRule)) *AlertRepo_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*biz.AlertRule))
	})
	return _c
}

func (_c *AlertRepo_UpdateRule_Call) Return(_a0 error) *AlertRepo_UpdateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertRepo_UpdateRule_Call) RunAndReturn(run func(*biz.AlertRule) error) *AlertRepo_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// WebsiteExpiry provides a mock function with no fields
func (_m *AlertRepo) WebsiteExpiry() ([]*biz.AlertMetric, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebsiteExpiry")
	}

	var r0 []*biz.AlertMetric
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*biz.AlertMetric, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*biz.AlertMetric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.AlertMetric)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_WebsiteExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebsiteExpiry'
type AlertRepo_WebsiteExpiry_Call struct {
	*mock.Call
}

// WebsiteExpiry is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) WebsiteExpiry() *AlertRepo_WebsiteExpiry_Call {
	return &AlertRepo_WebsiteExpiry_Call{Call: _e.mock.On("WebsiteExpiry")}
}

func (_c *AlertRepo_WebsiteExpiry_Call) Run(run func()) *AlertRepo_WebsiteExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_WebsiteExpiry_Call) Return(_a0 []*biz.AlertMetric, _a1 error) *AlertRepo_WebsiteExpiry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_WebsiteExpiry_Call) RunAndReturn(run func() ([]*biz.AlertMetric, error)) *AlertRepo_WebsiteExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// WebsiteHourStats provides a mock function with no fields
func (_m *AlertRepo) WebsiteHourStats() ([]*biz.WebsiteHourStat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebsiteHourStats")
	}

	var r0 []*biz.WebsiteHourStat
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*biz.WebsiteHourStat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*biz.WebsiteHourStat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.WebsiteHourStat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlertRepo_WebsiteHourStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebsiteHourStats'
type AlertRepo_WebsiteHourStats_Call struct {
	*mock.Call
}

// WebsiteHourStats is a helper method to define mock.On call
func (_e *AlertRepo_Expecter) WebsiteHourStats() *AlertRepo_WebsiteHourStats_Call {
	return &AlertRepo_WebsiteHourStats_Call{Call: _e.mock.On("WebsiteHourStats")}
}

func (_c *AlertRepo_WebsiteHourStats_Call) Run(run func()) *AlertRepo_WebsiteHourStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AlertRepo_WebsiteHourStats_Call) Return(_a0 []*biz.WebsiteHourStat, _a1 error) *AlertRepo_WebsiteHourStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlertRepo_WebsiteHourStats_Call) RunAndReturn(run func() ([]*biz.WebsiteHourStat, error)) *AlertRepo_WebsiteHourStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlertRepo creates a new instance of AlertRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertRepo {
	mock := &AlertRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
