// Code generated by mockery. DO NOT EDIT.

package biz

import (
	biz "github.com/acepanel/panel/v3/internal/biz"
	acme "github.com/mholt/acmez/v3/acme"

	mock "github.com/stretchr/testify/mock"

	pkgacme "github.com/acepanel/panel/v3/pkg/acme"
)

// CertAccountRepo is an autogenerated mock type for the CertAccountRepo type
type CertAccountRepo struct {
	mock.Mock
}

type CertAccountRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CertAccountRepo) EXPECT() *CertAccountRepo_Expecter {
	return &CertAccountRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: account
func (_m *CertAccountRepo) Create(account *biz.CertAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*biz.CertAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CertAccountRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CertAccountRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - account *biz.CertAccount
func (_e *CertAccountRepo_Expecter) Create(account interface{}) *CertAccountRepo_Create_Call {
	return &CertAccountRepo_Create_Call{Call: _e.mock.On("Create", account)}
}

func (_c *CertAccountRepo_Create_Call) Run(run func(account *biz.CertAccount)) *CertAccountRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*biz.CertAccount))
	})
	return _c
}

func (_c *CertAccountRepo_Create_Call) Return(_a0 error) *CertAccountRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertAccountRepo_Create_Call) RunAndReturn(run func(*biz.CertAccount) error) *CertAccountRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *CertAccountRepo) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CertAccountRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CertAccountRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *CertAccountRepo_Expecter) Delete(id interface{}) *CertAccountRepo_Delete_Call {
	return &CertAccountRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *CertAccountRepo_Delete_Call) Run(run func(id uint)) *CertAccountRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *CertAccountRepo_Delete_Call) Return(_a0 error) *CertAccountRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertAccountRepo_Delete_Call) RunAndReturn(run func(uint) error) *CertAccountRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *CertAccountRepo) Get(id uint) (*biz.CertAccount, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *biz.CertAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*biz.CertAccount, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *biz.CertAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.CertAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertAccountRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CertAccountRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id uint
func (_e *CertAccountRepo_Expecter) Get(id interface{}) *CertAccountRepo_Get_Call {
	return &CertAccountRepo_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *CertAccountRepo_Get_Call) Run(run func(id uint)) *CertAccountRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *CertAccountRepo_Get_Call) Return(_a0 *biz.CertAccount, _a1 error) *CertAccountRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertAccountRepo_Get_Call) RunAndReturn(run func(uint) (*biz.CertAccount, error)) *CertAccountRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCAEmail provides a mock function with given fields: ca, email
func (_m *CertAccountRepo) GetByCAEmail(ca string, email string) (*biz.CertAccount, error) {
	ret := _m.Called(ca, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByCAEmail")
	}

	var r0 *biz.CertAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*biz.CertAccount, error)); ok {
		return rf(ca, email)
	}
	if rf, ok := ret.Get(0).(func(string, string) *biz.CertAccount); ok {
		r0 = rf(ca, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.CertAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(ca, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertAccountRepo_GetByCAEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCAEmail'
type CertAccountRepo_GetByCAEmail_Call struct {
	*mock.Call
}

// GetByCAEmail is a helper method to define mock.On call
//   - ca string
//   - email string
func (_e *CertAccountRepo_Expecter) GetByCAEmail(ca interface{}, email interface{}) *CertAccountRepo_GetByCAEmail_Call {
	return &CertAccountRepo_GetByCAEmail_Call{Call: _e.mock.On("GetByCAEmail", ca, email)}
}

func (_c *CertAccountRepo_GetByCAEmail_Call) Run(run func(ca string, email string)) *CertAccountRepo_GetByCAEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *CertAccountRepo_GetByCAEmail_Call) Return(_a0 *biz.CertAccount, _a1 error) *CertAccountRepo_GetByCAEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertAccountRepo_GetByCAEmail_Call) RunAndReturn(run func(string, string) (*biz.CertAccount, error)) *CertAccountRepo_GetByCAEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetGoogleEAB provides a mock function with no fields
func (_m *CertAccountRepo) GetGoogleEAB() (*acme.EAB, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGoogleEAB")
	}

	var r0 *acme.EAB
	var r1 error
	if rf, ok := ret.Get(0).(func() (*acme.EAB, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *acme.EAB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*acme.EAB)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertAccountRepo_GetGoogleEAB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoogleEAB'
type CertAccountRepo_GetGoogleEAB_Call struct {
	*mock.Call
}

// GetGoogleEAB is a helper method to define mock.On call
func (_e *CertAccountRepo_Expecter) GetGoogleEAB() *CertAccountRepo_GetGoogleEAB_Call {
	return &CertAccountRepo_GetGoogleEAB_Call{Call: _e.mock.On("GetGoogleEAB")}
}

func (_c *CertAccountRepo_GetGoogleEAB_Call) Run(run func()) *CertAccountRepo_GetGoogleEAB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CertAccountRepo_GetGoogleEAB_Call) Return(_a0 *acme.EAB, _a1 error) *CertAccountRepo_GetGoogleEAB_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertAccountRepo_GetGoogleEAB_Call) RunAndReturn(run func() (*acme.EAB, error)) *CertAccountRepo_GetGoogleEAB_Call {
	_c.Call.Return(run)
	return _c
}

// GetZeroSSLEAB provides a mock function with given fields: email
func (_m *CertAccountRepo) GetZeroSSLEAB(email string) (*acme.EAB, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetZeroSSLEAB")
	}

	var r0 *acme.EAB
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*acme.EAB, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *acme.EAB); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*acme.EAB)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertAccountRepo_GetZeroSSLEAB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZeroSSLEAB'
type CertAccountRepo_GetZeroSSLEAB_Call struct {
	*mock.Call
}

// GetZeroSSLEAB is a helper method to define mock.On call
//   - email string
func (_e *CertAccountRepo_Expecter) GetZeroSSLEAB(email interface{}) *CertAccountRepo_GetZeroSSLEAB_Call {
	return &CertAccountRepo_GetZeroSSLEAB_Call{Call: _e.mock.On("GetZeroSSLEAB", email)}
}

func (_c *CertAccountRepo_GetZeroSSLEAB_Call) Run(run func(email string)) *CertAccountRepo_GetZeroSSLEAB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CertAccountRepo_GetZeroSSLEAB_Call) Return(_a0 *acme.EAB, _a1 error) *CertAccountRepo_GetZeroSSLEAB_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertAccountRepo_GetZeroSSLEAB_Call) RunAndReturn(run func(string) (*acme.EAB, error)) *CertAccountRepo_GetZeroSSLEAB_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: page, limit
func (_m *CertAccountRepo) List(page uint, limit uint) ([]*biz.CertAccount, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*biz.CertAccount
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]*biz.CertAccount, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []*biz.CertAccount); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.CertAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, uint) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CertAccountRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CertAccountRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - page uint
//   - limit uint
func (_e *CertAccountRepo_Expecter) List(page interface{}, limit interface{}) *CertAccountRepo_List_Call {
	return &CertAccountRepo_List_Call{Call: _e.mock.On("List", page, limit)}
}

func (_c *CertAccountRepo_List_Call) Run(run func(page uint, limit uint)) *CertAccountRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *CertAccountRepo_List_Call) Return(_a0 []*biz.CertAccount, _a1 int64, _a2 error) *CertAccountRepo_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *CertAccountRepo_List_Call) RunAndReturn(run func(uint, uint) ([]*biz.CertAccount, int64, error)) *CertAccountRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAccount provides a mock function with given fields: email, ca, eab, keyType
func (_m *CertAccountRepo) RegisterAccount(email string, ca string, eab *acme.EAB, keyType pkgacme.KeyType) (*pkgacme.Client, error) {
	ret := _m.Called(email, ca, eab, keyType)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAccount")
	}

	var r0 *pkgacme.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *acme.EAB, pkgacme.KeyType) (*pkgacme.Client, error)); ok {
		return rf(email, ca, eab, keyType)
	}
	if rf, ok := ret.Get(0).(func(string, string, *acme.EAB, pkgacme.KeyType) *pkgacme.Client); ok {
		r0 = rf(email, ca, eab, keyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkgacme.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *acme.EAB, pkgacme.KeyType) error); ok {
		r1 = rf(email, ca, eab, keyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertAccountRepo_RegisterAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAccount'
type CertAccountRepo_RegisterAccount_Call struct {
	*mock.Call
}

// RegisterAccount is a helper method to define mock.On call
//   - email string
//   - ca string
//   - eab *acme.EAB
//   - keyType pkgacme.KeyType
func (_e *CertAccountRepo_Expecter) RegisterAccount(email interface{}, ca interface{}, eab interface{}, keyType interface{}) *CertAccountRepo_RegisterAccount_Call {
	return &CertAccountRepo_RegisterAccount_Call{Call: _e.mock.On("RegisterAccount", email, ca, eab, keyType)}
}

func (_c *CertAccountRepo_RegisterAccount_Call) Run(run func(email string, ca string, eab *acme.EAB, keyType pkgacme.KeyType)) *CertAccountRepo_RegisterAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*acme.EAB), args[3].(pkgacme.KeyType))
	})
	return _c
}

func (_c *CertAccountRepo_RegisterAccount_Call) Return(_a0 *pkgacme.Client, _a1 error) *CertAccountRepo_RegisterAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertAccountRepo_RegisterAccount_Call) RunAndReturn(run func(string, string, *acme.EAB, pkgacme.KeyType) (*pkgacme.Client, error)) *CertAccountRepo_RegisterAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: account
func (_m *CertAccountRepo) Save(account *biz.CertAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*biz.CertAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CertAccountRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CertAccountRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - account *biz.CertAccount
func (_e *CertAccountRepo_Expecter) Save(account interface{}) *CertAccountRepo_Save_Call {
	return &CertAccountRepo_Save_Call{Call: _e.mock.On("Save", account)}
}

func (_c *CertAccountRepo_Save_Call) Run(run func(account *biz.CertAccount)) *CertAccountRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*biz.CertAccount))
	})
	return _c
}

func (_c *CertAccountRepo_Save_Call) Return(_a0 error) *CertAccountRepo_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertAccountRepo_Save_Call) RunAndReturn(run func(*biz.CertAccount) error) *CertAccountRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewCertAccountRepo creates a new instance of CertAccountRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertAccountRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertAccountRepo {
	mock := &CertAccountRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
