// Code generated by mockery. DO NOT EDIT.

package biz

import (
	request "github.com/acepanel/panel/v3/internal/request"
	types "github.com/acepanel/panel/v3/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// ContainerRepo is an autogenerated mock type for the ContainerRepo type
type ContainerRepo struct {
	mock.Mock
}

type ContainerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ContainerRepo) EXPECT() *ContainerRepo_Expecter {
	return &ContainerRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: sock, req
func (_m *ContainerRepo) Create(sock string, req *request.ContainerCreate) (string, error) {
	ret := _m.Called(sock, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *request.ContainerCreate) (string, error)); ok {
		return rf(sock, req)
	}
	if rf, ok := ret.Get(0).(func(string, *request.ContainerCreate) string); ok {
		r0 = rf(sock, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, *request.ContainerCreate) error); ok {
		r1 = rf(sock, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ContainerRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - sock string
//   - req *request.ContainerCreate
func (_e *ContainerRepo_Expecter) Create(sock interface{}, req interface{}) *ContainerRepo_Create_Call {
	return &ContainerRepo_Create_Call{Call: _e.mock.On("Create", sock, req)}
}

func (_c *ContainerRepo_Create_Call) Run(run func(sock string, req *request.ContainerCreate)) *ContainerRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*request.ContainerCreate))
	})
	return _c
}

func (_c *ContainerRepo_Create_Call) Return(_a0 string, _a1 error) *ContainerRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerRepo_Create_Call) RunAndReturn(run func(string, *request.ContainerCreate) (string, error)) *ContainerRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Kill(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type ContainerRepo_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Kill(sock interface{}, id interface{}) *ContainerRepo_Kill_Call {
	return &ContainerRepo_Kill_Call{Call: _e.mock.On("Kill", sock, id)}
}

func (_c *ContainerRepo_Kill_Call) Run(run func(sock string, id string)) *ContainerRepo_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Kill_Call) Return(_a0 error) *ContainerRepo_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Kill_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: sock
func (_m *ContainerRepo) ListAll(sock string) ([]types.Container, error) {
	ret := _m.Called(sock)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []types.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]types.Container, error)); ok {
		return rf(sock)
	}
	if rf, ok := ret.Get(0).(func(string) []types.Container); ok {
		r0 = rf(sock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerRepo_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type ContainerRepo_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - sock string
func (_e *ContainerRepo_Expecter) ListAll(sock interface{}) *ContainerRepo_ListAll_Call {
	return &ContainerRepo_ListAll_Call{Call: _e.mock.On("ListAll", sock)}
}

func (_c *ContainerRepo_ListAll_Call) Run(run func(sock string)) *ContainerRepo_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ContainerRepo_ListAll_Call) Return(_a0 []types.Container, _a1 error) *ContainerRepo_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerRepo_ListAll_Call) RunAndReturn(run func(string) ([]types.Container, error)) *ContainerRepo_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function with given fields: sock, id, tail
func (_m *ContainerRepo) Logs(sock string, id string, tail int) (string, error) {
	ret := _m.Called(sock, id, tail)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) (string, error)); ok {
		return rf(sock, id, tail)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) string); ok {
		r0 = rf(sock, id, tail)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(sock, id, tail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerRepo_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type ContainerRepo_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - sock string
//   - id string
//   - tail int
func (_e *ContainerRepo_Expecter) Logs(sock interface{}, id interface{}, tail interface{}) *ContainerRepo_Logs_Call {
	return &ContainerRepo_Logs_Call{Call: _e.mock.On("Logs", sock, id, tail)}
}

func (_c *ContainerRepo_Logs_Call) Run(run func(sock string, id string, tail int)) *ContainerRepo_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ContainerRepo_Logs_Call) Return(_a0 string, _a1 error) *ContainerRepo_Logs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerRepo_Logs_Call) RunAndReturn(run func(string, string, int) (string, error)) *ContainerRepo_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Pause(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type ContainerRepo_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Pause(sock interface{}, id interface{}) *ContainerRepo_Pause_Call {
	return &ContainerRepo_Pause_Call{Call: _e.mock.On("Pause", sock, id)}
}

func (_c *ContainerRepo_Pause_Call) Run(run func(sock string, id string)) *ContainerRepo_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Pause_Call) Return(_a0 error) *ContainerRepo_Pause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Pause_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function with given fields: sock
func (_m *ContainerRepo) Prune(sock string) error {
	ret := _m.Called(sock)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type ContainerRepo_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - sock string
func (_e *ContainerRepo_Expecter) Prune(sock interface{}) *ContainerRepo_Prune_Call {
	return &ContainerRepo_Prune_Call{Call: _e.mock.On("Prune", sock)}
}

func (_c *ContainerRepo_Prune_Call) Run(run func(sock string)) *ContainerRepo_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ContainerRepo_Prune_Call) Return(_a0 error) *ContainerRepo_Prune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Prune_Call) RunAndReturn(run func(string) error) *ContainerRepo_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Remove(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type ContainerRepo_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Remove(sock interface{}, id interface{}) *ContainerRepo_Remove_Call {
	return &ContainerRepo_Remove_Call{Call: _e.mock.On("Remove", sock, id)}
}

func (_c *ContainerRepo_Remove_Call) Run(run func(sock string, id string)) *ContainerRepo_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Remove_Call) Return(_a0 error) *ContainerRepo_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Remove_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function with given fields: sock, id, newName
func (_m *ContainerRepo) Rename(sock string, id string, newName string) error {
	ret := _m.Called(sock, id, newName)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(sock, id, newName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type ContainerRepo_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - sock string
//   - id string
//   - newName string
func (_e *ContainerRepo_Expecter) Rename(sock interface{}, id interface{}, newName interface{}) *ContainerRepo_Rename_Call {
	return &ContainerRepo_Rename_Call{Call: _e.mock.On("Rename", sock, id, newName)}
}

func (_c *ContainerRepo_Rename_Call) Run(run func(sock string, id string, newName string)) *ContainerRepo_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ContainerRepo_Rename_Call) Return(_a0 error) *ContainerRepo_Rename_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Rename_Call) RunAndReturn(run func(string, string, string) error) *ContainerRepo_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Restart(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type ContainerRepo_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Restart(sock interface{}, id interface{}) *ContainerRepo_Restart_Call {
	return &ContainerRepo_Restart_Call{Call: _e.mock.On("Restart", sock, id)}
}

func (_c *ContainerRepo_Restart_Call) Run(run func(sock string, id string)) *ContainerRepo_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Restart_Call) Return(_a0 error) *ContainerRepo_Restart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Restart_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Start(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ContainerRepo_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Start(sock interface{}, id interface{}) *ContainerRepo_Start_Call {
	return &ContainerRepo_Start_Call{Call: _e.mock.On("Start", sock, id)}
}

func (_c *ContainerRepo_Start_Call) Run(run func(sock string, id string)) *ContainerRepo_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Start_Call) Return(_a0 error) *ContainerRepo_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Start_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Stop(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ContainerRepo_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Stop(sock interface{}, id interface{}) *ContainerRepo_Stop_Call {
	return &ContainerRepo_Stop_Call{Call: _e.mock.On("Stop", sock, id)}
}

func (_c *ContainerRepo_Stop_Call) Run(run func(sock string, id string)) *ContainerRepo_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Stop_Call) Return(_a0 error) *ContainerRepo_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Stop_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Unpause provides a mock function with given fields: sock, id
func (_m *ContainerRepo) Unpause(sock string, id string) error {
	ret := _m.Called(sock, id)

	if len(ret) == 0 {
		panic("no return value specified for Unpause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sock, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerRepo_Unpause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpause'
type ContainerRepo_Unpause_Call struct {
	*mock.Call
}

// Unpause is a helper method to define mock.On call
//   - sock string
//   - id string
func (_e *ContainerRepo_Expecter) Unpause(sock interface{}, id interface{}) *ContainerRepo_Unpause_Call {
	return &ContainerRepo_Unpause_Call{Call: _e.mock.On("Unpause", sock, id)}
}

func (_c *ContainerRepo_Unpause_Call) Run(run func(sock string, id string)) *ContainerRepo_Unpause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContainerRepo_Unpause_Call) Return(_a0 error) *ContainerRepo_Unpause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerRepo_Unpause_Call) RunAndReturn(run func(string, string) error) *ContainerRepo_Unpause_Call {
	_c.Call.Return(run)
	return _c
}

// NewContainerRepo creates a new instance of ContainerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerRepo {
	mock := &ContainerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
