// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/internal/request"
	"github.com/acepanel/panel/v3/pkg/db"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabaseServerRepo creates a new instance of DatabaseServerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseServerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseServerRepo {
	mock := &DatabaseServerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseServerRepo is an autogenerated mock type for the DatabaseServerRepo type
type DatabaseServerRepo struct {
	mock.Mock
}

type DatabaseServerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseServerRepo) EXPECT() *DatabaseServerRepo_Expecter {
	return &DatabaseServerRepo_Expecter{mock: &_m.Mock}
}

// CheckServer provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) CheckServer(ctx context.Context, server *biz.DatabaseServer) bool {
	ret := _mock.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for CheckServer")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.DatabaseServer) bool); ok {
		r0 = returnFunc(ctx, server)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// DatabaseServerRepo_CheckServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckServer'
type DatabaseServerRepo_CheckServer_Call struct {
	*mock.Call
}

// CheckServer is a helper method to define mock.On call
//   - ctx context.Context
//   - server *biz.DatabaseServer
func (_e *DatabaseServerRepo_Expecter) CheckServer(ctx any, server any) *DatabaseServerRepo_CheckServer_Call {
	return &DatabaseServerRepo_CheckServer_Call{Call: _e.mock.On("CheckServer", ctx, server)}
}

func (_c *DatabaseServerRepo_CheckServer_Call) Run(run func(ctx context.Context, server *biz.DatabaseServer)) *DatabaseServerRepo_CheckServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.DatabaseServer
		if args[1] != nil {
			arg1 = args[1].(*biz.DatabaseServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_CheckServer_Call) Return(b bool) *DatabaseServerRepo_CheckServer_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *DatabaseServerRepo_CheckServer_Call) RunAndReturn(run func(ctx context.Context, server *biz.DatabaseServer) bool) *DatabaseServerRepo_CheckServer_Call {
	_c.Call.Return(run)
	return _c
}

// ClearUsers provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) ClearUsers(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ClearUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_ClearUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearUsers'
type DatabaseServerRepo_ClearUsers_Call struct {
	*mock.Call
}

// ClearUsers is a helper method to define mock.On call
//   - id uint
func (_e *DatabaseServerRepo_Expecter) ClearUsers(id any) *DatabaseServerRepo_ClearUsers_Call {
	return &DatabaseServerRepo_ClearUsers_Call{Call: _e.mock.On("ClearUsers", id)}
}

func (_c *DatabaseServerRepo_ClearUsers_Call) Run(run func(id uint)) *DatabaseServerRepo_ClearUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_ClearUsers_Call) Return(err error) *DatabaseServerRepo_ClearUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_ClearUsers_Call) RunAndReturn(run func(id uint) error) *DatabaseServerRepo_ClearUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) Count() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseServerRepo_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type DatabaseServerRepo_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *DatabaseServerRepo_Expecter) Count() *DatabaseServerRepo_Count_Call {
	return &DatabaseServerRepo_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *DatabaseServerRepo_Count_Call) Run(run func()) *DatabaseServerRepo_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseServerRepo_Count_Call) Return(n int64, err error) *DatabaseServerRepo_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatabaseServerRepo_Count_Call) RunAndReturn(run func() (int64, error)) *DatabaseServerRepo_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) Create(server *biz.DatabaseServer) error {
	ret := _mock.Called(server)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*biz.DatabaseServer) error); ok {
		r0 = returnFunc(server)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DatabaseServerRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - server *biz.DatabaseServer
func (_e *DatabaseServerRepo_Expecter) Create(server any) *DatabaseServerRepo_Create_Call {
	return &DatabaseServerRepo_Create_Call{Call: _e.mock.On("Create", server)}
}

func (_c *DatabaseServerRepo_Create_Call) Run(run func(server *biz.DatabaseServer)) *DatabaseServerRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *biz.DatabaseServer
		if args[0] != nil {
			arg0 = args[0].(*biz.DatabaseServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_Create_Call) Return(err error) *DatabaseServerRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_Create_Call) RunAndReturn(run func(server *biz.DatabaseServer) error) *DatabaseServerRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) CreateUser(user *biz.DatabaseUser) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*biz.DatabaseUser) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type DatabaseServerRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *biz.DatabaseUser
func (_e *DatabaseServerRepo_Expecter) CreateUser(user any) *DatabaseServerRepo_CreateUser_Call {
	return &DatabaseServerRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *DatabaseServerRepo_CreateUser_Call) Run(run func(user *biz.DatabaseUser)) *DatabaseServerRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *biz.DatabaseUser
		if args[0] != nil {
			arg0 = args[0].(*biz.DatabaseUser)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_CreateUser_Call) Return(err error) *DatabaseServerRepo_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_CreateUser_Call) RunAndReturn(run func(user *biz.DatabaseUser) error) *DatabaseServerRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) Delete(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DatabaseServerRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *DatabaseServerRepo_Expecter) Delete(id any) *DatabaseServerRepo_Delete_Call {
	return &DatabaseServerRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *DatabaseServerRepo_Delete_Call) Run(run func(id uint)) *DatabaseServerRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_Delete_Call) Return(err error) *DatabaseServerRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_Delete_Call) RunAndReturn(run func(id uint) error) *DatabaseServerRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) Get(ctx context.Context, id uint) (*biz.DatabaseServer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *biz.DatabaseServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*biz.DatabaseServer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *biz.DatabaseServer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.DatabaseServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseServerRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DatabaseServerRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *DatabaseServerRepo_Expecter) Get(ctx any, id any) *DatabaseServerRepo_Get_Call {
	return &DatabaseServerRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *DatabaseServerRepo_Get_Call) Run(run func(ctx context.Context, id uint)) *DatabaseServerRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_Get_Call) Return(databaseServer *biz.DatabaseServer, err error) *DatabaseServerRepo_Get_Call {
	_c.Call.Return(databaseServer, err)
	return _c
}

func (_c *DatabaseServerRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uint) (*biz.DatabaseServer, error)) *DatabaseServerRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) GetByName(ctx context.Context, name string) (*biz.DatabaseServer, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *biz.DatabaseServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*biz.DatabaseServer, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *biz.DatabaseServer); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.DatabaseServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseServerRepo_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type DatabaseServerRepo_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *DatabaseServerRepo_Expecter) GetByName(ctx any, name any) *DatabaseServerRepo_GetByName_Call {
	return &DatabaseServerRepo_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *DatabaseServerRepo_GetByName_Call) Run(run func(ctx context.Context, name string)) *DatabaseServerRepo_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_GetByName_Call) Return(databaseServer *biz.DatabaseServer, err error) *DatabaseServerRepo_GetByName_Call {
	_c.Call.Return(databaseServer, err)
	return _c
}

func (_c *DatabaseServerRepo_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*biz.DatabaseServer, error)) *DatabaseServerRepo_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) List(ctx context.Context, page uint, limit uint, typ string) ([]*biz.DatabaseServer, int64, error) {
	ret := _mock.Called(ctx, page, limit, typ)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*biz.DatabaseServer
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string) ([]*biz.DatabaseServer, int64, error)); ok {
		return returnFunc(ctx, page, limit, typ)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string) []*biz.DatabaseServer); ok {
		r0 = returnFunc(ctx, page, limit, typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.DatabaseServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, string) int64); ok {
		r1 = returnFunc(ctx, page, limit, typ)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, uint, string) error); ok {
		r2 = returnFunc(ctx, page, limit, typ)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DatabaseServerRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DatabaseServerRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint
//   - limit uint
//   - typ string
func (_e *DatabaseServerRepo_Expecter) List(ctx any, page any, limit any, typ any) *DatabaseServerRepo_List_Call {
	return &DatabaseServerRepo_List_Call{Call: _e.mock.On("List", ctx, page, limit, typ)}
}

func (_c *DatabaseServerRepo_List_Call) Run(run func(ctx context.Context, page uint, limit uint, typ string)) *DatabaseServerRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_List_Call) Return(databaseServers []*biz.DatabaseServer, n int64, err error) *DatabaseServerRepo_List_Call {
	_c.Call.Return(databaseServers, n, err)
	return _c
}

func (_c *DatabaseServerRepo_List_Call) RunAndReturn(run func(ctx context.Context, page uint, limit uint, typ string) ([]*biz.DatabaseServer, int64, error)) *DatabaseServerRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) ListUsers(serverID uint) ([]*biz.DatabaseUser, error) {
	ret := _mock.Called(serverID)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*biz.DatabaseUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]*biz.DatabaseUser, error)); ok {
		return returnFunc(serverID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []*biz.DatabaseUser); ok {
		r0 = returnFunc(serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.DatabaseUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(serverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseServerRepo_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type DatabaseServerRepo_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - serverID uint
func (_e *DatabaseServerRepo_Expecter) ListUsers(serverID any) *DatabaseServerRepo_ListUsers_Call {
	return &DatabaseServerRepo_ListUsers_Call{Call: _e.mock.On("ListUsers", serverID)}
}

func (_c *DatabaseServerRepo_ListUsers_Call) Run(run func(serverID uint)) *DatabaseServerRepo_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_ListUsers_Call) Return(databaseUsers []*biz.DatabaseUser, err error) *DatabaseServerRepo_ListUsers_Call {
	_c.Call.Return(databaseUsers, err)
	return _c
}

func (_c *DatabaseServerRepo_ListUsers_Call) RunAndReturn(run func(serverID uint) ([]*biz.DatabaseUser, error)) *DatabaseServerRepo_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Operator provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) Operator(ctx context.Context, server *biz.DatabaseServer) (db.Operator, error) {
	ret := _mock.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Operator")
	}

	var r0 db.Operator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.DatabaseServer) (db.Operator, error)); ok {
		return returnFunc(ctx, server)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.DatabaseServer) db.Operator); ok {
		r0 = returnFunc(ctx, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Operator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *biz.DatabaseServer) error); ok {
		r1 = returnFunc(ctx, server)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseServerRepo_Operator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operator'
type DatabaseServerRepo_Operator_Call struct {
	*mock.Call
}

// Operator is a helper method to define mock.On call
//   - ctx context.Context
//   - server *biz.DatabaseServer
func (_e *DatabaseServerRepo_Expecter) Operator(ctx any, server any) *DatabaseServerRepo_Operator_Call {
	return &DatabaseServerRepo_Operator_Call{Call: _e.mock.On("Operator", ctx, server)}
}

func (_c *DatabaseServerRepo_Operator_Call) Run(run func(ctx context.Context, server *biz.DatabaseServer)) *DatabaseServerRepo_Operator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.DatabaseServer
		if args[1] != nil {
			arg1 = args[1].(*biz.DatabaseServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_Operator_Call) Return(operator db.Operator, err error) *DatabaseServerRepo_Operator_Call {
	_c.Call.Return(operator, err)
	return _c
}

func (_c *DatabaseServerRepo_Operator_Call) RunAndReturn(run func(ctx context.Context, server *biz.DatabaseServer) (db.Operator, error)) *DatabaseServerRepo_Operator_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) Save(server *biz.DatabaseServer) error {
	ret := _mock.Called(server)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*biz.DatabaseServer) error); ok {
		r0 = returnFunc(server)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type DatabaseServerRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - server *biz.DatabaseServer
func (_e *DatabaseServerRepo_Expecter) Save(server any) *DatabaseServerRepo_Save_Call {
	return &DatabaseServerRepo_Save_Call{Call: _e.mock.On("Save", server)}
}

func (_c *DatabaseServerRepo_Save_Call) Run(run func(server *biz.DatabaseServer)) *DatabaseServerRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *biz.DatabaseServer
		if args[0] != nil {
			arg0 = args[0].(*biz.DatabaseServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_Save_Call) Return(err error) *DatabaseServerRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_Save_Call) RunAndReturn(run func(server *biz.DatabaseServer) error) *DatabaseServerRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) UpdatePassword(name string, password string) error {
	ret := _mock.Called(name, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(name, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type DatabaseServerRepo_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - name string
//   - password string
func (_e *DatabaseServerRepo_Expecter) UpdatePassword(name any, password any) *DatabaseServerRepo_UpdatePassword_Call {
	return &DatabaseServerRepo_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", name, password)}
}

func (_c *DatabaseServerRepo_UpdatePassword_Call) Run(run func(name string, password string)) *DatabaseServerRepo_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_UpdatePassword_Call) Return(err error) *DatabaseServerRepo_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_UpdatePassword_Call) RunAndReturn(run func(name string, password string) error) *DatabaseServerRepo_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePort provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) UpdatePort(name string, port uint) error {
	ret := _mock.Called(name, port)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = returnFunc(name, port)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_UpdatePort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePort'
type DatabaseServerRepo_UpdatePort_Call struct {
	*mock.Call
}

// UpdatePort is a helper method to define mock.On call
//   - name string
//   - port uint
func (_e *DatabaseServerRepo_Expecter) UpdatePort(name any, port any) *DatabaseServerRepo_UpdatePort_Call {
	return &DatabaseServerRepo_UpdatePort_Call{Call: _e.mock.On("UpdatePort", name, port)}
}

func (_c *DatabaseServerRepo_UpdatePort_Call) Run(run func(name string, port uint)) *DatabaseServerRepo_UpdatePort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_UpdatePort_Call) Return(err error) *DatabaseServerRepo_UpdatePort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_UpdatePort_Call) RunAndReturn(run func(name string, port uint) error) *DatabaseServerRepo_UpdatePort_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRemark provides a mock function for the type DatabaseServerRepo
func (_mock *DatabaseServerRepo) UpdateRemark(req *request.DatabaseServerUpdateRemark) error {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRemark")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*request.DatabaseServerUpdateRemark) error); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseServerRepo_UpdateRemark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRemark'
type DatabaseServerRepo_UpdateRemark_Call struct {
	*mock.Call
}

// UpdateRemark is a helper method to define mock.On call
//   - req *request.DatabaseServerUpdateRemark
func (_e *DatabaseServerRepo_Expecter) UpdateRemark(req any) *DatabaseServerRepo_UpdateRemark_Call {
	return &DatabaseServerRepo_UpdateRemark_Call{Call: _e.mock.On("UpdateRemark", req)}
}

func (_c *DatabaseServerRepo_UpdateRemark_Call) Run(run func(req *request.DatabaseServerUpdateRemark)) *DatabaseServerRepo_UpdateRemark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *request.DatabaseServerUpdateRemark
		if args[0] != nil {
			arg0 = args[0].(*request.DatabaseServerUpdateRemark)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseServerRepo_UpdateRemark_Call) Return(err error) *DatabaseServerRepo_UpdateRemark_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseServerRepo_UpdateRemark_Call) RunAndReturn(run func(req *request.DatabaseServerUpdateRemark) error) *DatabaseServerRepo_UpdateRemark_Call {
	_c.Call.Return(run)
	return _c
}
