// Code generated by mockery. DO NOT EDIT.

package biz

import (
	db "github.com/acepanel/panel/v3/pkg/db"
	mock "github.com/stretchr/testify/mock"

	request "github.com/acepanel/panel/v3/internal/http/request"
)

// DatabaseElasticsearchRepo is an autogenerated mock type for the DatabaseElasticsearchRepo type
type DatabaseElasticsearchRepo struct {
	mock.Mock
}

type DatabaseElasticsearchRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseElasticsearchRepo) EXPECT() *DatabaseElasticsearchRepo_Expecter {
	return &DatabaseElasticsearchRepo_Expecter{mock: &_m.Mock}
}

// Data provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) Data(req *request.DatabaseESData) ([]db.ESDocument, int64, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []db.ESDocument
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESData) ([]db.ESDocument, int64, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*request.DatabaseESData) []db.ESDocument); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ESDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(*request.DatabaseESData) int64); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(*request.DatabaseESData) error); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DatabaseElasticsearchRepo_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type DatabaseElasticsearchRepo_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - req *request.DatabaseESData
func (_e *DatabaseElasticsearchRepo_Expecter) Data(req interface{}) *DatabaseElasticsearchRepo_Data_Call {
	return &DatabaseElasticsearchRepo_Data_Call{Call: _e.mock.On("Data", req)}
}

func (_c *DatabaseElasticsearchRepo_Data_Call) Run(run func(req *request.DatabaseESData)) *DatabaseElasticsearchRepo_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESData))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_Data_Call) Return(_a0 []db.ESDocument, _a1 int64, _a2 error) *DatabaseElasticsearchRepo_Data_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DatabaseElasticsearchRepo_Data_Call) RunAndReturn(run func(*request.DatabaseESData) ([]db.ESDocument, int64, error)) *DatabaseElasticsearchRepo_Data_Call {
	_c.Call.Return(run)
	return _c
}

// DocumentDelete provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) DocumentDelete(req *request.DatabaseESDocumentDelete) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DocumentDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESDocumentDelete) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DatabaseElasticsearchRepo_DocumentDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentDelete'
type DatabaseElasticsearchRepo_DocumentDelete_Call struct {
	*mock.Call
}

// DocumentDelete is a helper method to define mock.On call
//   - req *request.DatabaseESDocumentDelete
func (_e *DatabaseElasticsearchRepo_Expecter) DocumentDelete(req interface{}) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	return &DatabaseElasticsearchRepo_DocumentDelete_Call{Call: _e.mock.On("DocumentDelete", req)}
}

func (_c *DatabaseElasticsearchRepo_DocumentDelete_Call) Run(run func(req *request.DatabaseESDocumentDelete)) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESDocumentDelete))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentDelete_Call) Return(_a0 error) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentDelete_Call) RunAndReturn(run func(*request.DatabaseESDocumentDelete) error) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	_c.Call.Return(run)
	return _c
}

// DocumentGet provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) DocumentGet(req *request.DatabaseESDocumentGet) (*db.ESDocument, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DocumentGet")
	}

	var r0 *db.ESDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESDocumentGet) (*db.ESDocument, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*request.DatabaseESDocumentGet) *db.ESDocument); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.ESDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(*request.DatabaseESDocumentGet) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DatabaseElasticsearchRepo_DocumentGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentGet'
type DatabaseElasticsearchRepo_DocumentGet_Call struct {
	*mock.Call
}

// DocumentGet is a helper method to define mock.On call
//   - req *request.DatabaseESDocumentGet
func (_e *DatabaseElasticsearchRepo_Expecter) DocumentGet(req interface{}) *DatabaseElasticsearchRepo_DocumentGet_Call {
	return &DatabaseElasticsearchRepo_DocumentGet_Call{Call: _e.mock.On("DocumentGet", req)}
}

func (_c *DatabaseElasticsearchRepo_DocumentGet_Call) Run(run func(req *request.DatabaseESDocumentGet)) *DatabaseElasticsearchRepo_DocumentGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESDocumentGet))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentGet_Call) Return(_a0 *db.ESDocument, _a1 error) *DatabaseElasticsearchRepo_DocumentGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentGet_Call) RunAndReturn(run func(*request.DatabaseESDocumentGet) (*db.ESDocument, error)) *DatabaseElasticsearchRepo_DocumentGet_Call {
	_c.Call.Return(run)
	return _c
}

// DocumentSet provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) DocumentSet(req *request.DatabaseESDocumentSet) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DocumentSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESDocumentSet) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DatabaseElasticsearchRepo_DocumentSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentSet'
type DatabaseElasticsearchRepo_DocumentSet_Call struct {
	*mock.Call
}

// DocumentSet is a helper method to define mock.On call
//   - req *request.DatabaseESDocumentSet
func (_e *DatabaseElasticsearchRepo_Expecter) DocumentSet(req interface{}) *DatabaseElasticsearchRepo_DocumentSet_Call {
	return &DatabaseElasticsearchRepo_DocumentSet_Call{Call: _e.mock.On("DocumentSet", req)}
}

func (_c *DatabaseElasticsearchRepo_DocumentSet_Call) Run(run func(req *request.DatabaseESDocumentSet)) *DatabaseElasticsearchRepo_DocumentSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESDocumentSet))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentSet_Call) Return(_a0 error) *DatabaseElasticsearchRepo_DocumentSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentSet_Call) RunAndReturn(run func(*request.DatabaseESDocumentSet) error) *DatabaseElasticsearchRepo_DocumentSet_Call {
	_c.Call.Return(run)
	return _c
}

// IndexCreate provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) IndexCreate(req *request.DatabaseESIndexCreate) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for IndexCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESIndexCreate) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DatabaseElasticsearchRepo_IndexCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexCreate'
type DatabaseElasticsearchRepo_IndexCreate_Call struct {
	*mock.Call
}

// IndexCreate is a helper method to define mock.On call
//   - req *request.DatabaseESIndexCreate
func (_e *DatabaseElasticsearchRepo_Expecter) IndexCreate(req interface{}) *DatabaseElasticsearchRepo_IndexCreate_Call {
	return &DatabaseElasticsearchRepo_IndexCreate_Call{Call: _e.mock.On("IndexCreate", req)}
}

func (_c *DatabaseElasticsearchRepo_IndexCreate_Call) Run(run func(req *request.DatabaseESIndexCreate)) *DatabaseElasticsearchRepo_IndexCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESIndexCreate))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexCreate_Call) Return(_a0 error) *DatabaseElasticsearchRepo_IndexCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexCreate_Call) RunAndReturn(run func(*request.DatabaseESIndexCreate) error) *DatabaseElasticsearchRepo_IndexCreate_Call {
	_c.Call.Return(run)
	return _c
}

// IndexDelete provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) IndexDelete(req *request.DatabaseESIndexDelete) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for IndexDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESIndexDelete) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DatabaseElasticsearchRepo_IndexDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexDelete'
type DatabaseElasticsearchRepo_IndexDelete_Call struct {
	*mock.Call
}

// IndexDelete is a helper method to define mock.On call
//   - req *request.DatabaseESIndexDelete
func (_e *DatabaseElasticsearchRepo_Expecter) IndexDelete(req interface{}) *DatabaseElasticsearchRepo_IndexDelete_Call {
	return &DatabaseElasticsearchRepo_IndexDelete_Call{Call: _e.mock.On("IndexDelete", req)}
}

func (_c *DatabaseElasticsearchRepo_IndexDelete_Call) Run(run func(req *request.DatabaseESIndexDelete)) *DatabaseElasticsearchRepo_IndexDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESIndexDelete))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexDelete_Call) Return(_a0 error) *DatabaseElasticsearchRepo_IndexDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexDelete_Call) RunAndReturn(run func(*request.DatabaseESIndexDelete) error) *DatabaseElasticsearchRepo_IndexDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Indices provides a mock function with given fields: req
func (_m *DatabaseElasticsearchRepo) Indices(req *request.DatabaseESIndices) ([]db.ESIndex, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Indices")
	}

	var r0 []db.ESIndex
	var r1 error
	if rf, ok := ret.Get(0).(func(*request.DatabaseESIndices) ([]db.ESIndex, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*request.DatabaseESIndices) []db.ESIndex); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ESIndex)
		}
	}

	if rf, ok := ret.Get(1).(func(*request.DatabaseESIndices) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DatabaseElasticsearchRepo_Indices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Indices'
type DatabaseElasticsearchRepo_Indices_Call struct {
	*mock.Call
}

// Indices is a helper method to define mock.On call
//   - req *request.DatabaseESIndices
func (_e *DatabaseElasticsearchRepo_Expecter) Indices(req interface{}) *DatabaseElasticsearchRepo_Indices_Call {
	return &DatabaseElasticsearchRepo_Indices_Call{Call: _e.mock.On("Indices", req)}
}

func (_c *DatabaseElasticsearchRepo_Indices_Call) Run(run func(req *request.DatabaseESIndices)) *DatabaseElasticsearchRepo_Indices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.DatabaseESIndices))
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_Indices_Call) Return(_a0 []db.ESIndex, _a1 error) *DatabaseElasticsearchRepo_Indices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DatabaseElasticsearchRepo_Indices_Call) RunAndReturn(run func(*request.DatabaseESIndices) ([]db.ESIndex, error)) *DatabaseElasticsearchRepo_Indices_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabaseElasticsearchRepo creates a new instance of DatabaseElasticsearchRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseElasticsearchRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseElasticsearchRepo {
	mock := &DatabaseElasticsearchRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
