// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	"github.com/acepanel/panel/v3/internal/request"
	"github.com/acepanel/panel/v3/pkg/db"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabaseRedisRepo creates a new instance of DatabaseRedisRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseRedisRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseRedisRepo {
	mock := &DatabaseRedisRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseRedisRepo is an autogenerated mock type for the DatabaseRedisRepo type
type DatabaseRedisRepo struct {
	mock.Mock
}

type DatabaseRedisRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseRedisRepo) EXPECT() *DatabaseRedisRepo_Expecter {
	return &DatabaseRedisRepo_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) Clear(ctx context.Context, req *request.DatabaseRedisClear) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisClear) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRedisRepo_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type DatabaseRedisRepo_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisClear
func (_e *DatabaseRedisRepo_Expecter) Clear(ctx any, req any) *DatabaseRedisRepo_Clear_Call {
	return &DatabaseRedisRepo_Clear_Call{Call: _e.mock.On("Clear", ctx, req)}
}

func (_c *DatabaseRedisRepo_Clear_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisClear)) *DatabaseRedisRepo_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisClear
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisClear)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_Clear_Call) Return(err error) *DatabaseRedisRepo_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRedisRepo_Clear_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisClear) error) *DatabaseRedisRepo_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) Data(ctx context.Context, req *request.DatabaseRedisData) ([]db.RedisKV, int, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []db.RedisKV
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisData) ([]db.RedisKV, int, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisData) []db.RedisKV); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.RedisKV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *request.DatabaseRedisData) int); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *request.DatabaseRedisData) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DatabaseRedisRepo_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type DatabaseRedisRepo_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisData
func (_e *DatabaseRedisRepo_Expecter) Data(ctx any, req any) *DatabaseRedisRepo_Data_Call {
	return &DatabaseRedisRepo_Data_Call{Call: _e.mock.On("Data", ctx, req)}
}

func (_c *DatabaseRedisRepo_Data_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisData)) *DatabaseRedisRepo_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisData
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_Data_Call) Return(redisKVs []db.RedisKV, n int, err error) *DatabaseRedisRepo_Data_Call {
	_c.Call.Return(redisKVs, n, err)
	return _c
}

func (_c *DatabaseRedisRepo_Data_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisData) ([]db.RedisKV, int, error)) *DatabaseRedisRepo_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Databases provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) Databases(ctx context.Context, req *request.DatabaseRedisDatabases) (int, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Databases")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisDatabases) (int, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisDatabases) int); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *request.DatabaseRedisDatabases) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseRedisRepo_Databases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Databases'
type DatabaseRedisRepo_Databases_Call struct {
	*mock.Call
}

// Databases is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisDatabases
func (_e *DatabaseRedisRepo_Expecter) Databases(ctx any, req any) *DatabaseRedisRepo_Databases_Call {
	return &DatabaseRedisRepo_Databases_Call{Call: _e.mock.On("Databases", ctx, req)}
}

func (_c *DatabaseRedisRepo_Databases_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisDatabases)) *DatabaseRedisRepo_Databases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisDatabases
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisDatabases)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_Databases_Call) Return(n int, err error) *DatabaseRedisRepo_Databases_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatabaseRedisRepo_Databases_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisDatabases) (int, error)) *DatabaseRedisRepo_Databases_Call {
	_c.Call.Return(run)
	return _c
}

// KeyDelete provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) KeyDelete(ctx context.Context, req *request.DatabaseRedisKeyDelete) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for KeyDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisKeyDelete) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRedisRepo_KeyDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyDelete'
type DatabaseRedisRepo_KeyDelete_Call struct {
	*mock.Call
}

// KeyDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisKeyDelete
func (_e *DatabaseRedisRepo_Expecter) KeyDelete(ctx any, req any) *DatabaseRedisRepo_KeyDelete_Call {
	return &DatabaseRedisRepo_KeyDelete_Call{Call: _e.mock.On("KeyDelete", ctx, req)}
}

func (_c *DatabaseRedisRepo_KeyDelete_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisKeyDelete)) *DatabaseRedisRepo_KeyDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisKeyDelete
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisKeyDelete)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_KeyDelete_Call) Return(err error) *DatabaseRedisRepo_KeyDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRedisRepo_KeyDelete_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisKeyDelete) error) *DatabaseRedisRepo_KeyDelete_Call {
	_c.Call.Return(run)
	return _c
}

// KeyGet provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) KeyGet(ctx context.Context, req *request.DatabaseRedisKeyGet) (*db.RedisKV, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for KeyGet")
	}

	var r0 *db.RedisKV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisKeyGet) (*db.RedisKV, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisKeyGet) *db.RedisKV); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.RedisKV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *request.DatabaseRedisKeyGet) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseRedisRepo_KeyGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyGet'
type DatabaseRedisRepo_KeyGet_Call struct {
	*mock.Call
}

// KeyGet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisKeyGet
func (_e *DatabaseRedisRepo_Expecter) KeyGet(ctx any, req any) *DatabaseRedisRepo_KeyGet_Call {
	return &DatabaseRedisRepo_KeyGet_Call{Call: _e.mock.On("KeyGet", ctx, req)}
}

func (_c *DatabaseRedisRepo_KeyGet_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisKeyGet)) *DatabaseRedisRepo_KeyGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisKeyGet
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisKeyGet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_KeyGet_Call) Return(redisKV *db.RedisKV, err error) *DatabaseRedisRepo_KeyGet_Call {
	_c.Call.Return(redisKV, err)
	return _c
}

func (_c *DatabaseRedisRepo_KeyGet_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisKeyGet) (*db.RedisKV, error)) *DatabaseRedisRepo_KeyGet_Call {
	_c.Call.Return(run)
	return _c
}

// KeyRename provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) KeyRename(ctx context.Context, req *request.DatabaseRedisKeyRename) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for KeyRename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisKeyRename) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRedisRepo_KeyRename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyRename'
type DatabaseRedisRepo_KeyRename_Call struct {
	*mock.Call
}

// KeyRename is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisKeyRename
func (_e *DatabaseRedisRepo_Expecter) KeyRename(ctx any, req any) *DatabaseRedisRepo_KeyRename_Call {
	return &DatabaseRedisRepo_KeyRename_Call{Call: _e.mock.On("KeyRename", ctx, req)}
}

func (_c *DatabaseRedisRepo_KeyRename_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisKeyRename)) *DatabaseRedisRepo_KeyRename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisKeyRename
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisKeyRename)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_KeyRename_Call) Return(err error) *DatabaseRedisRepo_KeyRename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRedisRepo_KeyRename_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisKeyRename) error) *DatabaseRedisRepo_KeyRename_Call {
	_c.Call.Return(run)
	return _c
}

// KeySet provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) KeySet(ctx context.Context, req *request.DatabaseRedisKeySet) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for KeySet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisKeySet) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRedisRepo_KeySet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeySet'
type DatabaseRedisRepo_KeySet_Call struct {
	*mock.Call
}

// KeySet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisKeySet
func (_e *DatabaseRedisRepo_Expecter) KeySet(ctx any, req any) *DatabaseRedisRepo_KeySet_Call {
	return &DatabaseRedisRepo_KeySet_Call{Call: _e.mock.On("KeySet", ctx, req)}
}

func (_c *DatabaseRedisRepo_KeySet_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisKeySet)) *DatabaseRedisRepo_KeySet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisKeySet
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisKeySet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_KeySet_Call) Return(err error) *DatabaseRedisRepo_KeySet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRedisRepo_KeySet_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisKeySet) error) *DatabaseRedisRepo_KeySet_Call {
	_c.Call.Return(run)
	return _c
}

// KeyTTL provides a mock function for the type DatabaseRedisRepo
func (_mock *DatabaseRedisRepo) KeyTTL(ctx context.Context, req *request.DatabaseRedisKeyTTL) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for KeyTTL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseRedisKeyTTL) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRedisRepo_KeyTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyTTL'
type DatabaseRedisRepo_KeyTTL_Call struct {
	*mock.Call
}

// KeyTTL is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseRedisKeyTTL
func (_e *DatabaseRedisRepo_Expecter) KeyTTL(ctx any, req any) *DatabaseRedisRepo_KeyTTL_Call {
	return &DatabaseRedisRepo_KeyTTL_Call{Call: _e.mock.On("KeyTTL", ctx, req)}
}

func (_c *DatabaseRedisRepo_KeyTTL_Call) Run(run func(ctx context.Context, req *request.DatabaseRedisKeyTTL)) *DatabaseRedisRepo_KeyTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseRedisKeyTTL
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseRedisKeyTTL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseRedisRepo_KeyTTL_Call) Return(err error) *DatabaseRedisRepo_KeyTTL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRedisRepo_KeyTTL_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseRedisKeyTTL) error) *DatabaseRedisRepo_KeyTTL_Call {
	_c.Call.Return(run)
	return _c
}
