// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	"github.com/acepanel/panel/v3/internal/request"
	"github.com/acepanel/panel/v3/pkg/db"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabaseElasticsearchRepo creates a new instance of DatabaseElasticsearchRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseElasticsearchRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseElasticsearchRepo {
	mock := &DatabaseElasticsearchRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseElasticsearchRepo is an autogenerated mock type for the DatabaseElasticsearchRepo type
type DatabaseElasticsearchRepo struct {
	mock.Mock
}

type DatabaseElasticsearchRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseElasticsearchRepo) EXPECT() *DatabaseElasticsearchRepo_Expecter {
	return &DatabaseElasticsearchRepo_Expecter{mock: &_m.Mock}
}

// Data provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) Data(ctx context.Context, req *request.DatabaseESData) ([]db.ESDocument, int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []db.ESDocument
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESData) ([]db.ESDocument, int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESData) []db.ESDocument); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ESDocument)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *request.DatabaseESData) int64); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *request.DatabaseESData) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DatabaseElasticsearchRepo_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type DatabaseElasticsearchRepo_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESData
func (_e *DatabaseElasticsearchRepo_Expecter) Data(ctx any, req any) *DatabaseElasticsearchRepo_Data_Call {
	return &DatabaseElasticsearchRepo_Data_Call{Call: _e.mock.On("Data", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_Data_Call) Run(run func(ctx context.Context, req *request.DatabaseESData)) *DatabaseElasticsearchRepo_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESData
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_Data_Call) Return(eSDocuments []db.ESDocument, n int64, err error) *DatabaseElasticsearchRepo_Data_Call {
	_c.Call.Return(eSDocuments, n, err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_Data_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESData) ([]db.ESDocument, int64, error)) *DatabaseElasticsearchRepo_Data_Call {
	_c.Call.Return(run)
	return _c
}

// DocumentDelete provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) DocumentDelete(ctx context.Context, req *request.DatabaseESDocumentDelete) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DocumentDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESDocumentDelete) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseElasticsearchRepo_DocumentDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentDelete'
type DatabaseElasticsearchRepo_DocumentDelete_Call struct {
	*mock.Call
}

// DocumentDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESDocumentDelete
func (_e *DatabaseElasticsearchRepo_Expecter) DocumentDelete(ctx any, req any) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	return &DatabaseElasticsearchRepo_DocumentDelete_Call{Call: _e.mock.On("DocumentDelete", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_DocumentDelete_Call) Run(run func(ctx context.Context, req *request.DatabaseESDocumentDelete)) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESDocumentDelete
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESDocumentDelete)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentDelete_Call) Return(err error) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentDelete_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESDocumentDelete) error) *DatabaseElasticsearchRepo_DocumentDelete_Call {
	_c.Call.Return(run)
	return _c
}

// DocumentGet provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) DocumentGet(ctx context.Context, req *request.DatabaseESDocumentGet) (*db.ESDocument, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DocumentGet")
	}

	var r0 *db.ESDocument
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESDocumentGet) (*db.ESDocument, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESDocumentGet) *db.ESDocument); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.ESDocument)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *request.DatabaseESDocumentGet) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseElasticsearchRepo_DocumentGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentGet'
type DatabaseElasticsearchRepo_DocumentGet_Call struct {
	*mock.Call
}

// DocumentGet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESDocumentGet
func (_e *DatabaseElasticsearchRepo_Expecter) DocumentGet(ctx any, req any) *DatabaseElasticsearchRepo_DocumentGet_Call {
	return &DatabaseElasticsearchRepo_DocumentGet_Call{Call: _e.mock.On("DocumentGet", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_DocumentGet_Call) Run(run func(ctx context.Context, req *request.DatabaseESDocumentGet)) *DatabaseElasticsearchRepo_DocumentGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESDocumentGet
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESDocumentGet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentGet_Call) Return(eSDocument *db.ESDocument, err error) *DatabaseElasticsearchRepo_DocumentGet_Call {
	_c.Call.Return(eSDocument, err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentGet_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESDocumentGet) (*db.ESDocument, error)) *DatabaseElasticsearchRepo_DocumentGet_Call {
	_c.Call.Return(run)
	return _c
}

// DocumentSet provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) DocumentSet(ctx context.Context, req *request.DatabaseESDocumentSet) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DocumentSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESDocumentSet) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseElasticsearchRepo_DocumentSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentSet'
type DatabaseElasticsearchRepo_DocumentSet_Call struct {
	*mock.Call
}

// DocumentSet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESDocumentSet
func (_e *DatabaseElasticsearchRepo_Expecter) DocumentSet(ctx any, req any) *DatabaseElasticsearchRepo_DocumentSet_Call {
	return &DatabaseElasticsearchRepo_DocumentSet_Call{Call: _e.mock.On("DocumentSet", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_DocumentSet_Call) Run(run func(ctx context.Context, req *request.DatabaseESDocumentSet)) *DatabaseElasticsearchRepo_DocumentSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESDocumentSet
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESDocumentSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentSet_Call) Return(err error) *DatabaseElasticsearchRepo_DocumentSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_DocumentSet_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESDocumentSet) error) *DatabaseElasticsearchRepo_DocumentSet_Call {
	_c.Call.Return(run)
	return _c
}

// IndexCreate provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) IndexCreate(ctx context.Context, req *request.DatabaseESIndexCreate) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IndexCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESIndexCreate) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseElasticsearchRepo_IndexCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexCreate'
type DatabaseElasticsearchRepo_IndexCreate_Call struct {
	*mock.Call
}

// IndexCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESIndexCreate
func (_e *DatabaseElasticsearchRepo_Expecter) IndexCreate(ctx any, req any) *DatabaseElasticsearchRepo_IndexCreate_Call {
	return &DatabaseElasticsearchRepo_IndexCreate_Call{Call: _e.mock.On("IndexCreate", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_IndexCreate_Call) Run(run func(ctx context.Context, req *request.DatabaseESIndexCreate)) *DatabaseElasticsearchRepo_IndexCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESIndexCreate
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESIndexCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexCreate_Call) Return(err error) *DatabaseElasticsearchRepo_IndexCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexCreate_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESIndexCreate) error) *DatabaseElasticsearchRepo_IndexCreate_Call {
	_c.Call.Return(run)
	return _c
}

// IndexDelete provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) IndexDelete(ctx context.Context, req *request.DatabaseESIndexDelete) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IndexDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESIndexDelete) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseElasticsearchRepo_IndexDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexDelete'
type DatabaseElasticsearchRepo_IndexDelete_Call struct {
	*mock.Call
}

// IndexDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESIndexDelete
func (_e *DatabaseElasticsearchRepo_Expecter) IndexDelete(ctx any, req any) *DatabaseElasticsearchRepo_IndexDelete_Call {
	return &DatabaseElasticsearchRepo_IndexDelete_Call{Call: _e.mock.On("IndexDelete", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_IndexDelete_Call) Run(run func(ctx context.Context, req *request.DatabaseESIndexDelete)) *DatabaseElasticsearchRepo_IndexDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESIndexDelete
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESIndexDelete)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexDelete_Call) Return(err error) *DatabaseElasticsearchRepo_IndexDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_IndexDelete_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESIndexDelete) error) *DatabaseElasticsearchRepo_IndexDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Indices provides a mock function for the type DatabaseElasticsearchRepo
func (_mock *DatabaseElasticsearchRepo) Indices(ctx context.Context, req *request.DatabaseESIndices) ([]db.ESIndex, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Indices")
	}

	var r0 []db.ESIndex
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESIndices) ([]db.ESIndex, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.DatabaseESIndices) []db.ESIndex); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ESIndex)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *request.DatabaseESIndices) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseElasticsearchRepo_Indices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Indices'
type DatabaseElasticsearchRepo_Indices_Call struct {
	*mock.Call
}

// Indices is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.DatabaseESIndices
func (_e *DatabaseElasticsearchRepo_Expecter) Indices(ctx any, req any) *DatabaseElasticsearchRepo_Indices_Call {
	return &DatabaseElasticsearchRepo_Indices_Call{Call: _e.mock.On("Indices", ctx, req)}
}

func (_c *DatabaseElasticsearchRepo_Indices_Call) Run(run func(ctx context.Context, req *request.DatabaseESIndices)) *DatabaseElasticsearchRepo_Indices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.DatabaseESIndices
		if args[1] != nil {
			arg1 = args[1].(*request.DatabaseESIndices)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseElasticsearchRepo_Indices_Call) Return(eSIndexs []db.ESIndex, err error) *DatabaseElasticsearchRepo_Indices_Call {
	_c.Call.Return(eSIndexs, err)
	return _c
}

func (_c *DatabaseElasticsearchRepo_Indices_Call) RunAndReturn(run func(ctx context.Context, req *request.DatabaseESIndices) ([]db.ESIndex, error)) *DatabaseElasticsearchRepo_Indices_Call {
	_c.Call.Return(run)
	return _c
}
