// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	mock "github.com/stretchr/testify/mock"
)

// NewEnvironmentRepo creates a new instance of EnvironmentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnvironmentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnvironmentRepo {
	mock := &EnvironmentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EnvironmentRepo is an autogenerated mock type for the EnvironmentRepo type
type EnvironmentRepo struct {
	mock.Mock
}

type EnvironmentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *EnvironmentRepo) EXPECT() *EnvironmentRepo_Expecter {
	return &EnvironmentRepo_Expecter{mock: &_m.Mock}
}

// ExecScript provides a mock function for the type EnvironmentRepo
func (_mock *EnvironmentRepo) ExecScript(cmd string) error {
	ret := _mock.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExecScript")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EnvironmentRepo_ExecScript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecScript'
type EnvironmentRepo_ExecScript_Call struct {
	*mock.Call
}

// ExecScript is a helper method to define mock.On call
//   - cmd string
func (_e *EnvironmentRepo_Expecter) ExecScript(cmd any) *EnvironmentRepo_ExecScript_Call {
	return &EnvironmentRepo_ExecScript_Call{Call: _e.mock.On("ExecScript", cmd)}
}

func (_c *EnvironmentRepo_ExecScript_Call) Run(run func(cmd string)) *EnvironmentRepo_ExecScript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EnvironmentRepo_ExecScript_Call) Return(err error) *EnvironmentRepo_ExecScript_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnvironmentRepo_ExecScript_Call) RunAndReturn(run func(cmd string) error) *EnvironmentRepo_ExecScript_Call {
	_c.Call.Return(run)
	return _c
}

// InstalledVersion provides a mock function for the type EnvironmentRepo
func (_mock *EnvironmentRepo) InstalledVersion(typ string, slug string) string {
	ret := _mock.Called(typ, slug)

	if len(ret) == 0 {
		panic("no return value specified for InstalledVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(typ, slug)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// EnvironmentRepo_InstalledVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstalledVersion'
type EnvironmentRepo_InstalledVersion_Call struct {
	*mock.Call
}

// InstalledVersion is a helper method to define mock.On call
//   - typ string
//   - slug string
func (_e *EnvironmentRepo_Expecter) InstalledVersion(typ any, slug any) *EnvironmentRepo_InstalledVersion_Call {
	return &EnvironmentRepo_InstalledVersion_Call{Call: _e.mock.On("InstalledVersion", typ, slug)}
}

func (_c *EnvironmentRepo_InstalledVersion_Call) Run(run func(typ string, slug string)) *EnvironmentRepo_InstalledVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EnvironmentRepo_InstalledVersion_Call) Return(s string) *EnvironmentRepo_InstalledVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *EnvironmentRepo_InstalledVersion_Call) RunAndReturn(run func(typ string, slug string) string) *EnvironmentRepo_InstalledVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsInstalled provides a mock function for the type EnvironmentRepo
func (_mock *EnvironmentRepo) IsInstalled(typ string, slug string) bool {
	ret := _mock.Called(typ, slug)

	if len(ret) == 0 {
		panic("no return value specified for IsInstalled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(typ, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// EnvironmentRepo_IsInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInstalled'
type EnvironmentRepo_IsInstalled_Call struct {
	*mock.Call
}

// IsInstalled is a helper method to define mock.On call
//   - typ string
//   - slug string
func (_e *EnvironmentRepo_Expecter) IsInstalled(typ any, slug any) *EnvironmentRepo_IsInstalled_Call {
	return &EnvironmentRepo_IsInstalled_Call{Call: _e.mock.On("IsInstalled", typ, slug)}
}

func (_c *EnvironmentRepo_IsInstalled_Call) Run(run func(typ string, slug string)) *EnvironmentRepo_IsInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EnvironmentRepo_IsInstalled_Call) Return(b bool) *EnvironmentRepo_IsInstalled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *EnvironmentRepo_IsInstalled_Call) RunAndReturn(run func(typ string, slug string) bool) *EnvironmentRepo_IsInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// ScriptCommand provides a mock function for the type EnvironmentRepo
func (_mock *EnvironmentRepo) ScriptCommand(typ string, action string, slug string, version string) string {
	ret := _mock.Called(typ, action, slug, version)

	if len(ret) == 0 {
		panic("no return value specified for ScriptCommand")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = returnFunc(typ, action, slug, version)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// EnvironmentRepo_ScriptCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScriptCommand'
type EnvironmentRepo_ScriptCommand_Call struct {
	*mock.Call
}

// ScriptCommand is a helper method to define mock.On call
//   - typ string
//   - action string
//   - slug string
//   - version string
func (_e *EnvironmentRepo_Expecter) ScriptCommand(typ any, action any, slug any, version any) *EnvironmentRepo_ScriptCommand_Call {
	return &EnvironmentRepo_ScriptCommand_Call{Call: _e.mock.On("ScriptCommand", typ, action, slug, version)}
}

func (_c *EnvironmentRepo_ScriptCommand_Call) Run(run func(typ string, action string, slug string, version string)) *EnvironmentRepo_ScriptCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EnvironmentRepo_ScriptCommand_Call) Return(s string) *EnvironmentRepo_ScriptCommand_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *EnvironmentRepo_ScriptCommand_Call) RunAndReturn(run func(typ string, action string, slug string, version string) string) *EnvironmentRepo_ScriptCommand_Call {
	_c.Call.Return(run)
	return _c
}
