// Code generated by mockery. DO NOT EDIT.

package biz

import (
	context "context"

	request "github.com/acepanel/panel/v3/internal/request"
	mock "github.com/stretchr/testify/mock"

	types "github.com/acepanel/panel/v3/pkg/types"
)

// MigrationSourceRepo is an autogenerated mock type for the MigrationSourceRepo type
type MigrationSourceRepo struct {
	mock.Mock
}

type MigrationSourceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MigrationSourceRepo) EXPECT() *MigrationSourceRepo_Expecter {
	return &MigrationSourceRepo_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function with given fields: ctx, conn, detail
func (_m *MigrationSourceRepo) Backup(ctx context.Context, conn *request.ToolboxMigrationConnection, detail *types.MigrationDetail) (string, error) {
	ret := _m.Called(ctx, conn, detail)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection, *types.MigrationDetail) (string, error)); ok {
		return rf(ctx, conn, detail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection, *types.MigrationDetail) string); ok {
		r0 = rf(ctx, conn, detail)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ToolboxMigrationConnection, *types.MigrationDetail) error); ok {
		r1 = rf(ctx, conn, detail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrationSourceRepo_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MigrationSourceRepo_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *request.ToolboxMigrationConnection
//   - detail *types.MigrationDetail
func (_e *MigrationSourceRepo_Expecter) Backup(ctx interface{}, conn interface{}, detail interface{}) *MigrationSourceRepo_Backup_Call {
	return &MigrationSourceRepo_Backup_Call{Call: _e.mock.On("Backup", ctx, conn, detail)}
}

func (_c *MigrationSourceRepo_Backup_Call) Run(run func(ctx context.Context, conn *request.ToolboxMigrationConnection, detail *types.MigrationDetail)) *MigrationSourceRepo_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.ToolboxMigrationConnection), args[2].(*types.MigrationDetail))
	})
	return _c
}

func (_c *MigrationSourceRepo_Backup_Call) Return(_a0 string, _a1 error) *MigrationSourceRepo_Backup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MigrationSourceRepo_Backup_Call) RunAndReturn(run func(context.Context, *request.ToolboxMigrationConnection, *types.MigrationDetail) (string, error)) *MigrationSourceRepo_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// Detail provides a mock function with given fields: ctx, conn, item
func (_m *MigrationSourceRepo) Detail(ctx context.Context, conn *request.ToolboxMigrationConnection, item types.MigrationItem) (*types.MigrationDetail, error) {
	ret := _m.Called(ctx, conn, item)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *types.MigrationDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection, types.MigrationItem) (*types.MigrationDetail, error)); ok {
		return rf(ctx, conn, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection, types.MigrationItem) *types.MigrationDetail); ok {
		r0 = rf(ctx, conn, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MigrationDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ToolboxMigrationConnection, types.MigrationItem) error); ok {
		r1 = rf(ctx, conn, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrationSourceRepo_Detail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detail'
type MigrationSourceRepo_Detail_Call struct {
	*mock.Call
}

// Detail is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *request.ToolboxMigrationConnection
//   - item types.MigrationItem
func (_e *MigrationSourceRepo_Expecter) Detail(ctx interface{}, conn interface{}, item interface{}) *MigrationSourceRepo_Detail_Call {
	return &MigrationSourceRepo_Detail_Call{Call: _e.mock.On("Detail", ctx, conn, item)}
}

func (_c *MigrationSourceRepo_Detail_Call) Run(run func(ctx context.Context, conn *request.ToolboxMigrationConnection, item types.MigrationItem)) *MigrationSourceRepo_Detail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.ToolboxMigrationConnection), args[2].(types.MigrationItem))
	})
	return _c
}

func (_c *MigrationSourceRepo_Detail_Call) Return(_a0 *types.MigrationDetail, _a1 error) *MigrationSourceRepo_Detail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MigrationSourceRepo_Detail_Call) RunAndReturn(run func(context.Context, *request.ToolboxMigrationConnection, types.MigrationItem) (*types.MigrationDetail, error)) *MigrationSourceRepo_Detail_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, conn, remote, local, progress
func (_m *MigrationSourceRepo) Download(ctx context.Context, conn *request.ToolboxMigrationConnection, remote string, local string, progress types.MigrationProgress) error {
	ret := _m.Called(ctx, conn, remote, local, progress)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection, string, string, types.MigrationProgress) error); ok {
		r0 = rf(ctx, conn, remote, local, progress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MigrationSourceRepo_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MigrationSourceRepo_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *request.ToolboxMigrationConnection
//   - remote string
//   - local string
//   - progress types.MigrationProgress
func (_e *MigrationSourceRepo_Expecter) Download(ctx interface{}, conn interface{}, remote interface{}, local interface{}, progress interface{}) *MigrationSourceRepo_Download_Call {
	return &MigrationSourceRepo_Download_Call{Call: _e.mock.On("Download", ctx, conn, remote, local, progress)}
}

func (_c *MigrationSourceRepo_Download_Call) Run(run func(ctx context.Context, conn *request.ToolboxMigrationConnection, remote string, local string, progress types.MigrationProgress)) *MigrationSourceRepo_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.ToolboxMigrationConnection), args[2].(string), args[3].(string), args[4].(types.MigrationProgress))
	})
	return _c
}

func (_c *MigrationSourceRepo_Download_Call) Return(_a0 error) *MigrationSourceRepo_Download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MigrationSourceRepo_Download_Call) RunAndReturn(run func(context.Context, *request.ToolboxMigrationConnection, string, string, types.MigrationProgress) error) *MigrationSourceRepo_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Items provides a mock function with given fields: ctx, conn
func (_m *MigrationSourceRepo) Items(ctx context.Context, conn *request.ToolboxMigrationConnection) ([]types.MigrationItem, error) {
	ret := _m.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for Items")
	}

	var r0 []types.MigrationItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection) ([]types.MigrationItem, error)); ok {
		return rf(ctx, conn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection) []types.MigrationItem); ok {
		r0 = rf(ctx, conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MigrationItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ToolboxMigrationConnection) error); ok {
		r1 = rf(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrationSourceRepo_Items_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Items'
type MigrationSourceRepo_Items_Call struct {
	*mock.Call
}

// Items is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *request.ToolboxMigrationConnection
func (_e *MigrationSourceRepo_Expecter) Items(ctx interface{}, conn interface{}) *MigrationSourceRepo_Items_Call {
	return &MigrationSourceRepo_Items_Call{Call: _e.mock.On("Items", ctx, conn)}
}

func (_c *MigrationSourceRepo_Items_Call) Run(run func(ctx context.Context, conn *request.ToolboxMigrationConnection)) *MigrationSourceRepo_Items_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.ToolboxMigrationConnection))
	})
	return _c
}

func (_c *MigrationSourceRepo_Items_Call) Return(_a0 []types.MigrationItem, _a1 error) *MigrationSourceRepo_Items_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MigrationSourceRepo_Items_Call) RunAndReturn(run func(context.Context, *request.ToolboxMigrationConnection) ([]types.MigrationItem, error)) *MigrationSourceRepo_Items_Call {
	_c.Call.Return(run)
	return _c
}

// Probe provides a mock function with given fields: ctx, conn
func (_m *MigrationSourceRepo) Probe(ctx context.Context, conn *request.ToolboxMigrationConnection) (*types.MigrationSource, error) {
	ret := _m.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for Probe")
	}

	var r0 *types.MigrationSource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection) (*types.MigrationSource, error)); ok {
		return rf(ctx, conn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection) *types.MigrationSource); ok {
		r0 = rf(ctx, conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MigrationSource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ToolboxMigrationConnection) error); ok {
		r1 = rf(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrationSourceRepo_Probe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Probe'
type MigrationSourceRepo_Probe_Call struct {
	*mock.Call
}

// Probe is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *request.ToolboxMigrationConnection
func (_e *MigrationSourceRepo_Expecter) Probe(ctx interface{}, conn interface{}) *MigrationSourceRepo_Probe_Call {
	return &MigrationSourceRepo_Probe_Call{Call: _e.mock.On("Probe", ctx, conn)}
}

func (_c *MigrationSourceRepo_Probe_Call) Run(run func(ctx context.Context, conn *request.ToolboxMigrationConnection)) *MigrationSourceRepo_Probe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.ToolboxMigrationConnection))
	})
	return _c
}

func (_c *MigrationSourceRepo_Probe_Call) Return(_a0 *types.MigrationSource, _a1 error) *MigrationSourceRepo_Probe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MigrationSourceRepo_Probe_Call) RunAndReturn(run func(context.Context, *request.ToolboxMigrationConnection) (*types.MigrationSource, error)) *MigrationSourceRepo_Probe_Call {
	_c.Call.Return(run)
	return _c
}

// SetRunning provides a mock function with given fields: ctx, conn, item, running
func (_m *MigrationSourceRepo) SetRunning(ctx context.Context, conn *request.ToolboxMigrationConnection, item types.MigrationItem, running bool) error {
	ret := _m.Called(ctx, conn, item, running)

	if len(ret) == 0 {
		panic("no return value specified for SetRunning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ToolboxMigrationConnection, types.MigrationItem, bool) error); ok {
		r0 = rf(ctx, conn, item, running)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MigrationSourceRepo_SetRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRunning'
type MigrationSourceRepo_SetRunning_Call struct {
	*mock.Call
}

// SetRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *request.ToolboxMigrationConnection
//   - item types.MigrationItem
//   - running bool
func (_e *MigrationSourceRepo_Expecter) SetRunning(ctx interface{}, conn interface{}, item interface{}, running interface{}) *MigrationSourceRepo_SetRunning_Call {
	return &MigrationSourceRepo_SetRunning_Call{Call: _e.mock.On("SetRunning", ctx, conn, item, running)}
}

func (_c *MigrationSourceRepo_SetRunning_Call) Run(run func(ctx context.Context, conn *request.ToolboxMigrationConnection, item types.MigrationItem, running bool)) *MigrationSourceRepo_SetRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.ToolboxMigrationConnection), args[2].(types.MigrationItem), args[3].(bool))
	})
	return _c
}

func (_c *MigrationSourceRepo_SetRunning_Call) Return(_a0 error) *MigrationSourceRepo_SetRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MigrationSourceRepo_SetRunning_Call) RunAndReturn(run func(context.Context, *request.ToolboxMigrationConnection, types.MigrationItem, bool) error) *MigrationSourceRepo_SetRunning_Call {
	_c.Call.Return(run)
	return _c
}

// NewMigrationSourceRepo creates a new instance of MigrationSourceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMigrationSourceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MigrationSourceRepo {
	mock := &MigrationSourceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
