// Code generated by mockery. DO NOT EDIT.

package biz

import mock "github.com/stretchr/testify/mock"

// SafeRepo is an autogenerated mock type for the SafeRepo type
type SafeRepo struct {
	mock.Mock
}

type SafeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SafeRepo) EXPECT() *SafeRepo_Expecter {
	return &SafeRepo_Expecter{mock: &_m.Mock}
}

// FirewallRunning provides a mock function with no fields
func (_m *SafeRepo) FirewallRunning() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FirewallRunning")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SafeRepo_FirewallRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirewallRunning'
type SafeRepo_FirewallRunning_Call struct {
	*mock.Call
}

// FirewallRunning is a helper method to define mock.On call
func (_e *SafeRepo_Expecter) FirewallRunning() *SafeRepo_FirewallRunning_Call {
	return &SafeRepo_FirewallRunning_Call{Call: _e.mock.On("FirewallRunning")}
}

func (_c *SafeRepo_FirewallRunning_Call) Run(run func()) *SafeRepo_FirewallRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SafeRepo_FirewallRunning_Call) Return(_a0 bool, _a1 error) *SafeRepo_FirewallRunning_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SafeRepo_FirewallRunning_Call) RunAndReturn(run func() (bool, error)) *SafeRepo_FirewallRunning_Call {
	_c.Call.Return(run)
	return _c
}

// GetPingStatus provides a mock function with no fields
func (_m *SafeRepo) GetPingStatus() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPingStatus")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SafeRepo_GetPingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPingStatus'
type SafeRepo_GetPingStatus_Call struct {
	*mock.Call
}

// GetPingStatus is a helper method to define mock.On call
func (_e *SafeRepo_Expecter) GetPingStatus() *SafeRepo_GetPingStatus_Call {
	return &SafeRepo_GetPingStatus_Call{Call: _e.mock.On("GetPingStatus")}
}

func (_c *SafeRepo_GetPingStatus_Call) Run(run func()) *SafeRepo_GetPingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SafeRepo_GetPingStatus_Call) Return(_a0 bool, _a1 error) *SafeRepo_GetPingStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SafeRepo_GetPingStatus_Call) RunAndReturn(run func() (bool, error)) *SafeRepo_GetPingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetPingStatus provides a mock function with given fields: status
func (_m *SafeRepo) SetPingStatus(status bool) error {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for SetPingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SafeRepo_SetPingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPingStatus'
type SafeRepo_SetPingStatus_Call struct {
	*mock.Call
}

// SetPingStatus is a helper method to define mock.On call
//   - status bool
func (_e *SafeRepo_Expecter) SetPingStatus(status interface{}) *SafeRepo_SetPingStatus_Call {
	return &SafeRepo_SetPingStatus_Call{Call: _e.mock.On("SetPingStatus", status)}
}

func (_c *SafeRepo_SetPingStatus_Call) Run(run func(status bool)) *SafeRepo_SetPingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *SafeRepo_SetPingStatus_Call) Return(_a0 error) *SafeRepo_SetPingStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SafeRepo_SetPingStatus_Call) RunAndReturn(run func(bool) error) *SafeRepo_SetPingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewSafeRepo creates a new instance of SafeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSafeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SafeRepo {
	mock := &SafeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
