// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/internal/request"
	mock "github.com/stretchr/testify/mock"
)

// NewSettingRepo creates a new instance of SettingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingRepo {
	mock := &SettingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SettingRepo is an autogenerated mock type for the SettingRepo type
type SettingRepo struct {
	mock.Mock
}

type SettingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SettingRepo) EXPECT() *SettingRepo_Expecter {
	return &SettingRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type SettingRepo
func (_mock *SettingRepo) Delete(key biz.SettingKey) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SettingRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SettingRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key biz.SettingKey
func (_e *SettingRepo_Expecter) Delete(key any) *SettingRepo_Delete_Call {
	return &SettingRepo_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *SettingRepo_Delete_Call) Run(run func(key biz.SettingKey)) *SettingRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SettingRepo_Delete_Call) Return(err error) *SettingRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SettingRepo_Delete_Call) RunAndReturn(run func(key biz.SettingKey) error) *SettingRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SettingRepo
func (_mock *SettingRepo) Get(key biz.SettingKey, defaultValue ...string) (string, error) {
	// string
	_va := make([]any, len(defaultValue))
	for _i := range defaultValue {
		_va[_i] = defaultValue[_i]
	}
	var _ca []any
	_ca = append(_ca, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...string) (string, error)); ok {
		return returnFunc(key, defaultValue...)
	}
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...string) string); ok {
		r0 = returnFunc(key, defaultValue...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(biz.SettingKey, ...string) error); ok {
		r1 = returnFunc(key, defaultValue...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SettingRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SettingRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key biz.SettingKey
//   - defaultValue ...string
func (_e *SettingRepo_Expecter) Get(key any, defaultValue ...any) *SettingRepo_Get_Call {
	return &SettingRepo_Get_Call{Call: _e.mock.On("Get",
		append([]any{key}, defaultValue...)...)}
}

func (_c *SettingRepo_Get_Call) Run(run func(key biz.SettingKey, defaultValue ...string)) *SettingRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		var arg1 []string
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SettingRepo_Get_Call) Return(s string, err error) *SettingRepo_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SettingRepo_Get_Call) RunAndReturn(run func(key biz.SettingKey, defaultValue ...string) (string, error)) *SettingRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function for the type SettingRepo
func (_mock *SettingRepo) GetBool(key biz.SettingKey, defaultValue ...bool) (bool, error) {
	// bool
	_va := make([]any, len(defaultValue))
	for _i := range defaultValue {
		_va[_i] = defaultValue[_i]
	}
	var _ca []any
	_ca = append(_ca, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...bool) (bool, error)); ok {
		return returnFunc(key, defaultValue...)
	}
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...bool) bool); ok {
		r0 = returnFunc(key, defaultValue...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(biz.SettingKey, ...bool) error); ok {
		r1 = returnFunc(key, defaultValue...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SettingRepo_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type SettingRepo_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - key biz.SettingKey
//   - defaultValue ...bool
func (_e *SettingRepo_Expecter) GetBool(key any, defaultValue ...any) *SettingRepo_GetBool_Call {
	return &SettingRepo_GetBool_Call{Call: _e.mock.On("GetBool",
		append([]any{key}, defaultValue...)...)}
}

func (_c *SettingRepo_GetBool_Call) Run(run func(key biz.SettingKey, defaultValue ...bool)) *SettingRepo_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		var arg1 []bool
		variadicArgs := make([]bool, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(bool)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SettingRepo_GetBool_Call) Return(b bool, err error) *SettingRepo_GetBool_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *SettingRepo_GetBool_Call) RunAndReturn(run func(key biz.SettingKey, defaultValue ...bool) (bool, error)) *SettingRepo_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function for the type SettingRepo
func (_mock *SettingRepo) GetInt(key biz.SettingKey, defaultValue ...int) (int, error) {
	// int
	_va := make([]any, len(defaultValue))
	for _i := range defaultValue {
		_va[_i] = defaultValue[_i]
	}
	var _ca []any
	_ca = append(_ca, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...int) (int, error)); ok {
		return returnFunc(key, defaultValue...)
	}
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...int) int); ok {
		r0 = returnFunc(key, defaultValue...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(biz.SettingKey, ...int) error); ok {
		r1 = returnFunc(key, defaultValue...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SettingRepo_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type SettingRepo_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - key biz.SettingKey
//   - defaultValue ...int
func (_e *SettingRepo_Expecter) GetInt(key any, defaultValue ...any) *SettingRepo_GetInt_Call {
	return &SettingRepo_GetInt_Call{Call: _e.mock.On("GetInt",
		append([]any{key}, defaultValue...)...)}
}

func (_c *SettingRepo_GetInt_Call) Run(run func(key biz.SettingKey, defaultValue ...int)) *SettingRepo_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		var arg1 []int
		variadicArgs := make([]int, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(int)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SettingRepo_GetInt_Call) Return(n int, err error) *SettingRepo_GetInt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SettingRepo_GetInt_Call) RunAndReturn(run func(key biz.SettingKey, defaultValue ...int) (int, error)) *SettingRepo_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetPanel provides a mock function for the type SettingRepo
func (_mock *SettingRepo) GetPanel() (*request.SettingPanel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPanel")
	}

	var r0 *request.SettingPanel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*request.SettingPanel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *request.SettingPanel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.SettingPanel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SettingRepo_GetPanel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPanel'
type SettingRepo_GetPanel_Call struct {
	*mock.Call
}

// GetPanel is a helper method to define mock.On call
func (_e *SettingRepo_Expecter) GetPanel() *SettingRepo_GetPanel_Call {
	return &SettingRepo_GetPanel_Call{Call: _e.mock.On("GetPanel")}
}

func (_c *SettingRepo_GetPanel_Call) Run(run func()) *SettingRepo_GetPanel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SettingRepo_GetPanel_Call) Return(settingPanel *request.SettingPanel, err error) *SettingRepo_GetPanel_Call {
	_c.Call.Return(settingPanel, err)
	return _c
}

func (_c *SettingRepo_GetPanel_Call) RunAndReturn(run func() (*request.SettingPanel, error)) *SettingRepo_GetPanel_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlice provides a mock function for the type SettingRepo
func (_mock *SettingRepo) GetSlice(key biz.SettingKey, defaultValue ...[]string) ([]string, error) {
	// []string
	_va := make([]any, len(defaultValue))
	for _i := range defaultValue {
		_va[_i] = defaultValue[_i]
	}
	var _ca []any
	_ca = append(_ca, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSlice")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...[]string) ([]string, error)); ok {
		return returnFunc(key, defaultValue...)
	}
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, ...[]string) []string); ok {
		r0 = returnFunc(key, defaultValue...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(biz.SettingKey, ...[]string) error); ok {
		r1 = returnFunc(key, defaultValue...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SettingRepo_GetSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlice'
type SettingRepo_GetSlice_Call struct {
	*mock.Call
}

// GetSlice is a helper method to define mock.On call
//   - key biz.SettingKey
//   - defaultValue ...[]string
func (_e *SettingRepo_Expecter) GetSlice(key any, defaultValue ...any) *SettingRepo_GetSlice_Call {
	return &SettingRepo_GetSlice_Call{Call: _e.mock.On("GetSlice",
		append([]any{key}, defaultValue...)...)}
}

func (_c *SettingRepo_GetSlice_Call) Run(run func(key biz.SettingKey, defaultValue ...[]string)) *SettingRepo_GetSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		var arg1 [][]string
		variadicArgs := make([][]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.([]string)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SettingRepo_GetSlice_Call) Return(strings []string, err error) *SettingRepo_GetSlice_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *SettingRepo_GetSlice_Call) RunAndReturn(run func(key biz.SettingKey, defaultValue ...[]string) ([]string, error)) *SettingRepo_GetSlice_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type SettingRepo
func (_mock *SettingRepo) Set(key biz.SettingKey, value string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SettingRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type SettingRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key biz.SettingKey
//   - value string
func (_e *SettingRepo_Expecter) Set(key any, value any) *SettingRepo_Set_Call {
	return &SettingRepo_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *SettingRepo_Set_Call) Run(run func(key biz.SettingKey, value string)) *SettingRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SettingRepo_Set_Call) Return(err error) *SettingRepo_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SettingRepo_Set_Call) RunAndReturn(run func(key biz.SettingKey, value string) error) *SettingRepo_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetSlice provides a mock function for the type SettingRepo
func (_mock *SettingRepo) SetSlice(key biz.SettingKey, value []string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetSlice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(biz.SettingKey, []string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SettingRepo_SetSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSlice'
type SettingRepo_SetSlice_Call struct {
	*mock.Call
}

// SetSlice is a helper method to define mock.On call
//   - key biz.SettingKey
//   - value []string
func (_e *SettingRepo_Expecter) SetSlice(key any, value any) *SettingRepo_SetSlice_Call {
	return &SettingRepo_SetSlice_Call{Call: _e.mock.On("SetSlice", key, value)}
}

func (_c *SettingRepo_SetSlice_Call) Run(run func(key biz.SettingKey, value []string)) *SettingRepo_SetSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 biz.SettingKey
		if args[0] != nil {
			arg0 = args[0].(biz.SettingKey)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SettingRepo_SetSlice_Call) Return(err error) *SettingRepo_SetSlice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SettingRepo_SetSlice_Call) RunAndReturn(run func(key biz.SettingKey, value []string) error) *SettingRepo_SetSlice_Call {
	_c.Call.Return(run)
	return _c
}
