template: matryer
dir: internal/mocks/{{.InterfaceDirRelative | trimPrefix "internal/"}}
structname: "{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "{{.InterfaceName}}.go"
all: true
packages:
  github.com/acepanel/panel/v3/internal/biz: {}
