package openlitespeed

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"github.com/acepanel/panel/v3/pkg/cert"
)

var syncMu sync.Mutex

// 默认证书，供尚无站点证书的 HTTPS 监听器握手
const (
	defaultCert = PanelConfDir + "/default.crt"
	defaultKey  = PanelConfDir + "/default.key"
)

// SyncListeners 汇总所有站点记录的监听地址与域名，重新生成面板托管的监听器配置
// OpenLiteSpeed 的端口与域名映射位于主配置的 listener 块，无法拆分到站点文件，因此每次保存站点后整体重建
func SyncListeners() error {
	syncMu.Lock()
	defer syncMu.Unlock()

	// 未安装时跳过
	if _, err := os.Stat(PanelConfDir); err != nil {
		return nil
	}
	if err := ensureDefaultCert(); err != nil {
		return err
	}

	type listener struct {
		address string
		secure  bool
		maps    []string
	}
	byAddr := make(map[string]*listener)
	var order []string
	get := func(addr string) *listener {
		if l, ok := byAddr[addr]; ok {
			return l
		}
		l := &listener{address: addr}
		byAddr[addr] = l
		order = append(order, addr)
		return l
	}
	get("*:80")
	get("*:443").secure = true

	matches, _ := filepath.Glob(filepath.Join(SitesPath, "*", "config", ListenConfName))
	sort.Strings(matches)
	for _, path := range matches {
		cfg, err := ParseFile(path)
		if err != nil {
			continue
		}
		site := filepath.Base(filepath.Dir(filepath.Dir(path)))
		domains := strings.Fields(cfg.Value("domain"))
		if len(domains) == 0 {
			continue
		}
		for _, d := range cfg.Directives("listen") {
			fields := strings.Fields(d.Value)
			if len(fields) == 0 {
				continue
			}
			l := get(listenerAddress(fields[0]))
			for _, arg := range fields[1:] {
				if arg == "ssl" {
					l.secure = true
				}
			}
			l.maps = append(l.maps, site+" "+strings.Join(domains, ", "))
		}
	}

	cfg := &Config{}
	cfg.Append(&Comment{Text: " Auto-generated by AcePanel. DO NOT EDIT MANUALLY!"})
	for _, addr := range order {
		l := byAddr[addr]
		b := cfg.AddBlock("listener", listenerName(addr))
		b.Add("address", addr)
		if l.secure {
			b.Add("secure", "1")
			b.Add("keyFile", defaultKey)
			b.Add("certFile", defaultCert)
		} else {
			b.Add("secure", "0")
		}
		catchAll := false
		for _, m := range l.maps {
			b.Add("map", m)
			catchAll = catchAll || strings.HasSuffix(m, " *")
		}
		// 未匹配任何站点域名的请求交给面板默认站点，每个监听器只允许一个通配映射
		if !catchAll {
			b.Add("map", "default *")
		}
	}

	if err := os.WriteFile(ListenersConf, []byte(cfg.String()), 0600); err != nil {
		return fmt.Errorf("failed to write listeners config: %w", err)
	}

	return nil
}

// ensureDefaultCert 生成缺失的默认自签名证书
func ensureDefaultCert() error {
	if _, err := os.Stat(defaultCert); err == nil {
		if _, err = os.Stat(defaultKey); err == nil {
			return nil
		}
	}
	crt, key, err := cert.GenerateSelfSigned([]string{"localhost"})
	if err != nil {
		return err
	}
	if err = os.WriteFile(defaultCert, crt, 0600); err != nil {
		return err
	}
	return os.WriteFile(defaultKey, key, 0600)
}

// listenerAddress 将站点监听地址规整为 listener 的 address
func listenerAddress(addr string) string {
	if !strings.Contains(addr, ":") {
		return "*:" + addr
	}
	if port, ok := strings.CutPrefix(addr, "0.0.0.0:"); ok {
		return "*:" + port
	}
	return addr
}

// listenerName 由地址派生唯一的 listener 名称
func listenerName(addr string) string {
	name := strings.NewReplacer("*", "any", "[::]", "ip6").Replace(addr)
	return "ace_" + safeName(name)
}
