package openlitespeed

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"

	"github.com/acepanel/panel/v3/pkg/systemctl"
	"github.com/acepanel/panel/v3/pkg/webserver/conf"
)

// PHP 外部应用定义在服务器级，每版本一个，站点只 include 脚本处理器行，切换协议无需改站点配置

const (
	phpConf       = PanelConfDir + "/php.conf" // 各版本外部应用
	phpHandlerDir = PanelConfDir + "/php"      // 各版本脚本处理器行，供站点 include
	lsapiDir      = PanelConfDir + "/lsapi"    // 已切换为 LSAPI 的版本标记
)

var phpHandlerPattern = regexp.MustCompile(`/php/(\d+)\.conf$`)

func phpHandlerFile(version uint) string {
	return filepath.Join(phpHandlerDir, strconv.FormatUint(uint64(version), 10)+".conf")
}

func LSPHPPath(version uint) string {
	return fmt.Sprintf("/opt/ace/server/php/%d/bin/lsphp", version)
}

// LSAPIEnabled 标记在但 lsphp 不在时要当作没开，否则外部应用会指向不存在的二进制，
// 而 php-fpm 又被停掉，该版本 PHP 就整体不可用了
func LSAPIEnabled(version uint) bool {
	if _, err := os.Stat(filepath.Join(lsapiDir, strconv.FormatUint(uint64(version), 10))); err != nil {
		return false
	}
	_, err := os.Stat(LSPHPPath(version))
	return err == nil
}

// SetLSAPI 切换 PHP 版本的运行协议，调用方负责重载
func SetLSAPI(version uint, enabled bool) error {
	marker := filepath.Join(lsapiDir, strconv.FormatUint(uint64(version), 10))
	if enabled {
		if _, err := os.Stat(LSPHPPath(version)); err != nil {
			return errors.New("lsphp binary not found")
		}
		if err := os.MkdirAll(lsapiDir, 0755); err != nil {
			return err
		}
		if err := os.WriteFile(marker, []byte(""), 0600); err != nil {
			return err
		}
	} else if err := os.Remove(marker); err != nil && !os.IsNotExist(err) {
		return err
	}

	return Sync()
}

// syncPHP 为已安装及站点引用的 PHP 版本生成外部应用与处理器行，未安装的也生成以免 PHP 源码被当静态文件输出
func syncPHP() error {
	if err := os.MkdirAll(phpHandlerDir, 0755); err != nil {
		return err
	}

	versions := installedPHPVersions()
	sites, _ := filepath.Glob(filepath.Join(SitesPath, "*", "config", VhostConfName))
	for _, path := range sites {
		if vhost, err := NewPHPVhost(filepath.Dir(path)); err == nil && vhost.PHP() > 0 {
			versions = append(versions, vhost.PHP())
		}
	}
	slices.Sort(versions)
	versions = slices.Compact(versions)

	cfg := &conf.Config{}
	cfg.Append(conf.Cmt("Auto-generated by AcePanel. DO NOT EDIT MANUALLY!"))
	for _, version := range versions {
		name := fmt.Sprintf("php%d", version)
		ext := cfg.AddBlock("extprocessor", name)
		handler := "fcgi:" + name
		if LSAPIEnabled(version) {
			handler = "lsapi:" + name
			children := fpmMaxChildren(version)
			ext.Add("type", "lsapi")
			ext.Add("address", "uds:/"+LSAPISocket(version))
			ext.Add("maxConns", strconv.Itoa(children))
			ext.Add("env", fmt.Sprintf("PHP_LSAPI_CHILDREN=%d", children))
			ext.Add("env", "LSAPI_AVOID_FORK=200M")
			ext.Add("initTimeout", "300")
			ext.Add("retryTimeout", "0")
			ext.Add("persistConn", "1")
			ext.Add("respBuffer", "0")
			ext.Add("autoStart", "1")
			ext.Add("path", LSPHPPath(version))
			ext.Add("backlog", "100")
			ext.Add("instances", "1")
		} else {
			ext.Add("type", "fcgi")
			ext.Add("address", fmt.Sprintf("uds://tmp/php-cgi-%d.sock", version))
			ext.Add("maxConns", strconv.Itoa(fpmMaxChildren(version)))
			ext.Add("initTimeout", "300")
			ext.Add("retryTimeout", "0")
			ext.Add("persistConn", "0")
			ext.Add("respBuffer", "0")
			ext.Add("autoStart", "0")
		}

		line := &conf.Config{}
		line.Add("add", handler+" php")
		if err := os.WriteFile(phpHandlerFile(version), []byte(Export(line)), 0600); err != nil {
			return err
		}
	}

	return os.WriteFile(phpConf, []byte(Export(cfg)), 0600)
}

// LSAPISocket lsphp 监听的套接字
func LSAPISocket(version uint) string {
	return fmt.Sprintf("/tmp/lshttpd/php%d.sock", version)
}

// SyncFPM 按 LSAPI 的启用情况开停 php-fpm
func SyncFPM(ctx context.Context, active bool) error {
	var errs []error
	for _, version := range installedPHPVersions() {
		name := fmt.Sprintf("php-fpm-%d", version)
		// 服务不存在时 enable/disable 会报错，这里只关心开停结果
		if active && LSAPIEnabled(version) {
			_ = systemctl.Disable(ctx, name)
			if running, _ := systemctl.Status(ctx, name); running {
				errs = append(errs, systemctl.Stop(ctx, name))
			}
			continue
		}
		_ = systemctl.Enable(ctx, name)
		if running, _ := systemctl.Status(ctx, name); !running {
			errs = append(errs, systemctl.Start(ctx, name))
		}
	}

	return errors.Join(errs...)
}

func installedPHPVersions() []uint {
	var versions []uint
	matches, _ := filepath.Glob("/opt/ace/server/php/*/bin/php")
	for _, match := range matches {
		if version, err := strconv.ParseUint(filepath.Base(filepath.Dir(filepath.Dir(match))), 10, 32); err == nil {
			versions = append(versions, uint(version))
		}
	}
	return versions
}

var maxChildrenPattern = regexp.MustCompile(`(?m)^\s*pm\.max_children\s*=\s*(\d+)`)

// fpmMaxChildren 取 php-fpm 的进程上限，LSAPI 与 FastCGI 并发都用它
func fpmMaxChildren(version uint) int {
	raw, err := os.ReadFile(fmt.Sprintf("/opt/ace/server/php/%d/etc/php-fpm.conf", version))
	if err == nil {
		if m := maxChildrenPattern.FindSubmatch(raw); m != nil {
			if n, _ := strconv.Atoi(string(m[1])); n > 0 {
				return n
			}
		}
	}
	return 30
}
