package request

import "github.com/leonelquinteros/gotext"

// Attributes 校验消息中 {field} 的显示名称
func Attributes(t *gotext.Locale) map[string]string {
	return map[string]string{
		"Access":                t.Get("Access Mode"),
		"Address":               t.Get("Address"),
		"Ak":                    t.Get("Access Key"),
		"AlertDays":             t.Get("Alert Days"),
		"AnonymousOnly":         t.Get("Anonymous Only"),
		"AuthMethod":            t.Get("Authentication Method"),
		"Authorization":         t.Get("Authorization"),
		"BackupFormat":          t.Get("Backup Format"),
		"BackupPath":            t.Get("Backup Path"),
		"BanTime":               t.Get("Ban Time"),
		"BindIP":                t.Get("Bind IP"),
		"BlockDuration":         t.Get("Block Duration"),
		"BlockThreshold":        t.Get("Block Threshold"),
		"BlockWindow":           t.Get("Block Window"),
		"Body":                  t.Get("Body"),
		"Bucket":                t.Get("Bucket"),
		"CA":                    t.Get("CA"),
		"Cert":                  t.Get("Certificate"),
		"Channel":               t.Get("Channel"),
		"ChunkCount":            t.Get("Chunk Count"),
		"Command":               t.Get("Command"),
		"Compose":               t.Get("Compose"),
		"Config":                t.Get("Config"),
		"CustomLogo":            t.Get("Custom Logo"),
		"DBName":                t.Get("Database Name"),
		"DBPassword":            t.Get("Database Password"),
		"DBType":                t.Get("Database Type"),
		"DBUser":                t.Get("Database User"),
		"Data":                  t.Get("Data"),
		"Database":              t.Get("Database"),
		"Databases":             t.Get("Databases"),
		"Date":                  t.Get("Date"),
		"Days":                  t.Get("Days"),
		"DbPath":                t.Get("Database Path"),
		"DetailMaxKeys":         t.Get("Detail Max Keys"),
		"Device":                t.Get("Device"),
		"Devices":               t.Get("Devices"),
		"Dir":                   t.Get("Directory"),
		"Direction":             t.Get("Direction"),
		"Domains":               t.Get("Domains"),
		"Driver":                t.Get("Driver"),
		"Duration":              t.Get("Duration"),
		"Email":                 t.Get("Email"),
		"End":                   t.Get("End"),
		"Entrance":              t.Get("Entrance"),
		"EntranceError":         t.Get("Entrance Error"),
		"Env":                   t.Get("Environment"),
		"ErrBufMax":             t.Get("Error Buffer Max"),
		"ExpireHours":           t.Get("Expire Hours"),
		"ExpiredAt":             t.Get("Expiration Time"),
		"Family":                t.Get("Family"),
		"File":                  t.Get("File"),
		"FileHash":              t.Get("File Hash"),
		"FileName":              t.Get("File Name"),
		"FindTime":              t.Get("Find Time"),
		"FsType":                t.Get("Filesystem Type"),
		"Group":                 t.Get("Group"),
		"HTTPPort":              t.Get("HTTP Port"),
		"Host":                  t.Get("Host"),
		"Hostname":              t.Get("Hostname"),
		"ID":                    t.Get("ID"),
		"IP":                    t.Get("IP"),
		"IPDBType":              t.Get("IP Database Type"),
		"IPMaxKeys":             t.Get("IP Max Keys"),
		"IPs":                   t.Get("IP List"),
		"Image":                 t.Get("Image"),
		"Index":                 t.Get("Index"),
		"Interfaces":            t.Get("Interfaces"),
		"Interval":              t.Get("Interval"),
		"Items":                 t.Get("Items"),
		"Keep":                  t.Get("Keep"),
		"Key":                   t.Get("Key"),
		"KeyType":               t.Get("Key Type"),
		"Lifetime":              t.Get("Lifetime"),
		"Limit":                 t.Get("Limit"),
		"Listen":                t.Get("Listen Address"),
		"ListenPort":            t.Get("Listen Port"),
		"Listens":               t.Get("Listen Addresses"),
		"Locale":                t.Get("Locale"),
		"LogLevel":              t.Get("Log Level"),
		"MaxClientsNumber":      t.Get("Max Clients"),
		"MaxClientsPerIP":       t.Get("Max Clients Per IP"),
		"MaxConnections":        t.Get("Max Connections"),
		"MaxDiskUsage":          t.Get("Max Disk Usage"),
		"MaxExecutionTime":      t.Get("Max Execution Time"),
		"MaxFileUploads":        t.Get("Max File Uploads"),
		"MaxIdleTime":           t.Get("Max Idle Time"),
		"MaxInputTime":          t.Get("Max Input Time"),
		"MaxInputVars":          t.Get("Max Input Vars"),
		"MaxMessageSize":        t.Get("Max Message Size"),
		"MaxRetry":              t.Get("Max Retry"),
		"Memory":                t.Get("Memory"),
		"MemoryLimit":           t.Get("Memory Limit"),
		"Mirror":                t.Get("Mirror"),
		"Mode":                  t.Get("Mode"),
		"MountPoint":            t.Get("Mount Point"),
		"Name":                  t.Get("Name"),
		"NewKey":                t.Get("New Key"),
		"NewStrategy":           t.Get("New Strategy"),
		"NoAnonymous":           t.Get("No Anonymous"),
		"Num":                   t.Get("Number"),
		"OldKey":                t.Get("Old Key"),
		"Operation":             t.Get("Operation"),
		"Operator":              t.Get("Operator"),
		"Order":                 t.Get("Order"),
		"Owner":                 t.Get("Owner"),
		"PID":                   t.Get("PID"),
		"Page":                  t.Get("Page"),
		"Password":              t.Get("Password"),
		"Path":                  t.Get("Path"),
		"Paths":                 t.Get("Paths"),
		"Pm":                    t.Get("Process Manager"),
		"PmMaxChildren":         t.Get("Max Children"),
		"PmMaxSpareServers":     t.Get("Max Spare Servers"),
		"PmMinSpareServers":     t.Get("Min Spare Servers"),
		"PmStartServers":        t.Get("Start Servers"),
		"Port":                  t.Get("Port"),
		"PortEnd":               t.Get("End Port"),
		"PortStart":             t.Get("Start Port"),
		"Process":               t.Get("Process"),
		"ProjectPath":           t.Get("Project Path"),
		"Protocol":              t.Get("Protocol"),
		"Proxy":                 t.Get("Proxy"),
		"ProxyPass":             t.Get("Proxy Pass"),
		"Registry":              t.Get("Registry"),
		"RestartMax":            t.Get("Max Restarts"),
		"RestartPolicy":         t.Get("Restart Policy"),
		"Root":                  t.Get("Root"),
		"RootDir":               t.Get("Root Directory"),
		"SSLCertificate":        t.Get("SSL Certificate"),
		"SSLCertificateKey":     t.Get("SSL Certificate Key"),
		"Schema":                t.Get("Schema"),
		"Scope":                 t.Get("Scope"),
		"Script":                t.Get("Script"),
		"ServerID":              t.Get("Server"),
		"Servers":               t.Get("Servers"),
		"Service":               t.Get("Service"),
		"SessionCookieLifetime": t.Get("Session Cookie Lifetime"),
		"SessionGcMaxlifetime":  t.Get("Session GC Max Lifetime"),
		"Settings":              t.Get("Settings"),
		"Signal":                t.Get("Signal"),
		"Silence":               t.Get("Silence"),
		"Size":                  t.Get("Size"),
		"Sk":                    t.Get("Secret Key"),
		"Slug":                  t.Get("Slug"),
		"Slugs":                 t.Get("Slugs"),
		"Sort":                  t.Get("Sort"),
		"Source":                t.Get("Source"),
		"SourcePanel":           t.Get("Source Panel"),
		"Start":                 t.Get("Start"),
		"Status":                t.Get("Status"),
		"Stop":                  t.Get("Stop"),
		"Strategy":              t.Get("Strategy"),
		"SubType":               t.Get("Sub Type"),
		"SystemLogPath":         t.Get("System Log Path"),
		"TCPPort":               t.Get("TCP Port"),
		"TLS":                   t.Get("TLS"),
		"TLSVersions":           t.Get("TLS Versions"),
		"Table":                 t.Get("Table"),
		"Target":                t.Get("Target"),
		"TargetIP":              t.Get("Target IP"),
		"TargetPort":            t.Get("Target Port"),
		"Targets":               t.Get("Targets"),
		"Threads":               t.Get("Threads"),
		"Time":                  t.Get("Time"),
		"Timeout":               t.Get("Timeout"),
		"TimeoutStartSec":       t.Get("Start Timeout"),
		"TimeoutStopSec":        t.Get("Stop Timeout"),
		"Timezone":              t.Get("Timezone"),
		"TmpPath":               t.Get("Temp Path"),
		"Token":                 t.Get("Token"),
		"Type":                  t.Get("Type"),
		"UDPPort":               t.Get("UDP Port"),
		"URL":                   t.Get("URL"),
		"UVMaxKeys":             t.Get("UV Max Keys"),
		"User":                  t.Get("User"),
		"UserID":                t.Get("User"),
		"Username":              t.Get("Username"),
		"VGName":                t.Get("Volume Group"),
		"Value":                 t.Get("Value"),
		"WebsiteIDs":            t.Get("Websites"),
		"WebsiteMode":           t.Get("Website Mode"),
		"WebsiteName":           t.Get("Website Name"),
		"WebsitePath":           t.Get("Website Path"),
		"Whitelist":             t.Get("Whitelist"),
	}
}
