package service

import "github.com/google/wire"

// ProviderSet is service providers.
var ProviderSet = wire.NewSet(
	NewAppService,
	NewBackupService,
	NewCertService,
	NewCertAccountService,
	NewCertDNSService,
	NewCliService,
	NewContainerService,
	NewContainerComposeService,
	NewContainerImageService,
	NewContainerNetworkService,
	NewContainerVolumeService,
	NewCronService,
	NewDatabaseService,
	NewDatabaseServerService,
	NewDatabaseUserService,
	NewEnvironmentService,
	NewEnvironmentPHPService,
	NewFileService,
	NewFirewallService,
	NewHomeService,
	NewMonitorService,
	NewProcessService,
	NewSafeService,
	NewSettingService,
	NewSSHService,
	NewSystemctlService,
	NewTaskService,
	NewUserService,
	NewUserTokenService,
	NewWebHookService,
	NewWebsiteService,
	NewToolboxSystemService,
	NewToolboxBenchmarkService,
	NewToolboxSSHService,
	NewToolboxDiskService,
	NewWsService,
)
