package service

import "github.com/google/wire"

// ProviderSet is service providers.
var ProviderSet = wire.NewSet(
	NewAppService,
	NewBackupService,
	NewBackupStorageService,
	NewCertService,
	NewCertAccountService,
	NewCertDNSService,
	NewCliService,
	NewContainerService,
	NewContainerComposeService,
	NewContainerImageService,
	NewContainerNetworkService,
	NewContainerVolumeService,
	NewCronService,
	NewDatabaseService,
	NewDatabaseRedisService,
	NewDatabaseServerService,
	NewDatabaseUserService,
	NewEnvironmentService,
	NewEnvironmentGoService,
	NewEnvironmentJavaService,
	NewEnvironmentNodejsService,
	NewEnvironmentPHPService,
	NewEnvironmentPythonService,
	NewEnvironmentDotnetService,
	NewFileService,
	NewFirewallService,
	NewHomeService,
	NewLogService,
	NewMonitorService,
	NewProcessService,
	NewProjectService,
	NewSafeService,
	NewSettingService,
	NewSSHService,
	NewSystemctlService,
	NewTaskService,
	NewTemplateService,
	NewUserService,
	NewUserTokenService,
	NewWebHookService,
	NewWebsiteService,
	NewToolboxNetworkService,
	NewToolboxSystemService,
	NewToolboxBenchmarkService,
	NewToolboxSSHService,
	NewToolboxDiskService,
	NewToolboxLogService,
	NewToolboxMigrationService,
	NewWsService,
)
