//go:build wireinject

package service

import "github.com/libtnb/wire"

// Module 装配服务层
var Module = wire.New().
	Provide(NewAlertService).
	Provide(NewAppService).
	Provide(NewBackupService).
	Provide(NewBackupStorageService).
	Provide(NewCertService).
	Provide(NewCertAccountService).
	Provide(NewCertDNSService).
	Provide(NewCliService).
	Provide(NewContainerService).
	Provide(NewContainerComposeService).
	Provide(NewContainerImageService).
	Provide(NewContainerNetworkService).
	Provide(NewContainerVolumeService).
	Provide(NewCronService).
	Provide(NewDatabaseService).
	Provide(NewDatabaseRedisService).
	Provide(NewDatabaseElasticsearchService).
	Provide(NewDatabaseServerService).
	Provide(NewDatabaseUserService).
	Provide(NewEnvironmentService).
	Provide(NewEnvironmentGoService).
	Provide(NewEnvironmentJavaService).
	Provide(NewEnvironmentNodejsService).
	Provide(NewEnvironmentPHPService).
	Provide(NewEnvironmentPythonService).
	Provide(NewEnvironmentDotnetService).
	Provide(NewFileService).
	Provide(NewFileShareService).
	Provide(NewFirewallService).
	Provide(NewFirewallScanService).
	Provide(NewHomeService).
	Provide(NewLogService).
	Provide(NewMonitorService).
	Provide(NewNotifyService).
	Provide(NewProcessService).
	Provide(NewProjectService).
	Provide(NewSafeService).
	Provide(NewSettingService).
	Provide(NewSSHService).
	Provide(NewSystemctlService).
	Provide(NewTamperService).
	Provide(NewTaskService).
	Provide(NewTemplateService).
	Provide(NewUserService).
	Provide(NewUserPasskeyService).
	Provide(NewUserTokenService).
	Provide(NewWebHookService).
	Provide(NewWebsiteService).
	Provide(NewWebsiteStatService).
	Provide(NewToolboxNetworkService).
	Provide(NewToolboxSystemService).
	Provide(NewToolboxBenchmarkService).
	Provide(NewToolboxSSHService).
	Provide(NewToolboxDiskService).
	Provide(NewToolboxLogService).
	Provide(NewToolboxMigrationService).
	Provide(NewWsService).
	Export[*AlertService]().
	Export[*AppService]().
	Export[*BackupService]().
	Export[*BackupStorageService]().
	Export[*CertService]().
	Export[*CertAccountService]().
	Export[*CertDNSService]().
	Export[*CliService]().
	Export[*ContainerService]().
	Export[*ContainerComposeService]().
	Export[*ContainerImageService]().
	Export[*ContainerNetworkService]().
	Export[*ContainerVolumeService]().
	Export[*CronService]().
	Export[*DatabaseService]().
	Export[*DatabaseRedisService]().
	Export[*DatabaseElasticsearchService]().
	Export[*DatabaseServerService]().
	Export[*DatabaseUserService]().
	Export[*EnvironmentService]().
	Export[*EnvironmentGoService]().
	Export[*EnvironmentJavaService]().
	Export[*EnvironmentNodejsService]().
	Export[*EnvironmentPHPService]().
	Export[*EnvironmentPythonService]().
	Export[*EnvironmentDotnetService]().
	Export[*FileService]().
	Export[*FileShareService]().
	Export[*FirewallService]().
	Export[*FirewallScanService]().
	Export[*HomeService]().
	Export[*LogService]().
	Export[*MonitorService]().
	Export[*NotifyService]().
	Export[*ProcessService]().
	Export[*ProjectService]().
	Export[*SafeService]().
	Export[*SettingService]().
	Export[*SSHService]().
	Export[*SystemctlService]().
	Export[*TamperService]().
	Export[*TaskService]().
	Export[*TemplateService]().
	Export[*UserService]().
	Export[*UserPasskeyService]().
	Export[*UserTokenService]().
	Export[*WebHookService]().
	Export[*WebsiteService]().
	Export[*WebsiteStatService]().
	Export[*ToolboxNetworkService]().
	Export[*ToolboxSystemService]().
	Export[*ToolboxBenchmarkService]().
	Export[*ToolboxSSHService]().
	Export[*ToolboxDiskService]().
	Export[*ToolboxLogService]().
	Export[*ToolboxMigrationService]().
	Export[*WsService]()
