@list path_regexp list ^/list-([0-9]+)\.html$
rewrite @list /plus/list.php?tid={re.list.1}&{query}
@listpage path_regexp listpage ^/list-([0-9]+)-([0-9]+)-([0-9]+)\.html$
rewrite @listpage /plus/list.php?tid={re.listpage.1}&totalresult={re.listpage.2}&PageNo={re.listpage.3}&{query}
@view path_regexp view ^/view-([0-9]+)-1\.html$
rewrite @view /plus/view.php?arcID={re.view.1}&{query}
@viewpage path_regexp viewpage ^/view-([0-9]+)-([0-9]+)\.html$
rewrite @viewpage /plus/view.php?aid={re.viewpage.1}&pageno={re.viewpage.2}&{query}
@pluslist path_regexp pluslist ^/plus/list-([0-9]+)\.html$
rewrite @pluslist /plus/list.php?tid={re.pluslist.1}&{query}
@pluslistpage path_regexp pluslistpage ^/plus/list-([0-9]+)-([0-9]+)-([0-9]+)\.html$
rewrite @pluslistpage /plus/list.php?tid={re.pluslistpage.1}&totalresult={re.pluslistpage.2}&PageNo={re.pluslistpage.3}&{query}
@plusview path_regexp plusview ^/plus/view-([0-9]+)-1\.html$
rewrite @plusview /plus/view.php?arcID={re.plusview.1}&{query}
@plusviewpage path_regexp plusviewpage ^/plus/view-([0-9]+)-([0-9]+)\.html$
rewrite @plusviewpage /plus/view.php?aid={re.plusviewpage.1}&pageno={re.plusviewpage.2}&{query}
@tags path_regexp tags ^/tags\.html$
rewrite @tags /tags.php
@tag path_regexp tag ^/tag-([0-9]+)-([0-9]+)\.html$
rewrite @tag /tags.php?/{re.tag.1}/{re.tag.2}/&{query}
