@archiver path_regexp archiver ^/archiver/((fid|tid)-[\w\-]+\.html)$
rewrite @archiver /archiver/index.php?{re.archiver.1}&{query}
@forum path_regexp forum ^/forum-([0-9]+)-([0-9]+)\.html$
rewrite @forum /forumdisplay.php?fid={re.forum.1}&page={re.forum.2}&{query}
@thread path_regexp thread ^/thread-([0-9]+)-([0-9]+)-([0-9]+)\.html$
rewrite @thread /viewthread.php?tid={re.thread.1}&extra=page%3D{re.thread.3}&page={re.thread.2}&{query}
@space path_regexp space ^/space-(username|uid)-(.+)\.html$
rewrite @space /space.php?{re.space.1}={re.space.2}&{query}
@tag path_regexp tag ^/tag-(.+)\.html$
rewrite @tag /tag.php?name={re.tag.1}&{query}
