@listinfo path_regexp listinfo ^([^\.]*)/listinfo-(.+?)-(.+?)\.html$
rewrite @listinfo {re.listinfo.1}/e/action/ListInfo/index.php?classid={re.listinfo.2}&page={re.listinfo.3}&{query}
@showinfo path_regexp showinfo ^([^\.]*)/showinfo-(.+?)-(.+?)-(.+?)\.html$
rewrite @showinfo {re.showinfo.1}/e/action/ShowInfo.php?classid={re.showinfo.2}&id={re.showinfo.3}&page={re.showinfo.4}&{query}
@infotype path_regexp infotype ^([^\.]*)/infotype-(.+?)-(.+?)\.html$
rewrite @infotype {re.infotype.1}/e/action/InfoType/index.php?ttid={re.infotype.2}&page={re.infotype.3}&{query}
@tags path_regexp tags ^([^\.]*)/tags-(.+?)-(.+?)\.html$
rewrite @tags {re.tags.1}/e/tags/index.php?tagname={re.tags.2}&page={re.tags.3}&{query}
@comment path_regexp comment ^([^\.]*)/comment-(.+?)-(.+?)-(.+?)-(.+?)-(.+?)-(.+?)\.html$
rewrite @comment {re.comment.1}/e/pl/index.php?doaction={re.comment.2}&classid={re.comment.3}&id={re.comment.4}&page={re.comment.5}&myorder={re.comment.6}&tempid={re.comment.7}&{query}
# Anything left that isn't a real file or directory is a 404
@notfound {
	not file {
		try_files {path} {path}/
	}
}
respond @notfound 404
