@vod path_regexp vod ^/vod-(.*)$
rewrite @vod /index.php?m=vod-{re.vod.1}&{query}
@art path_regexp art ^/art-(.*)$
rewrite @art /index.php?m=art-{re.art.1}&{query}
@gbook path_regexp gbook ^/gbook-(.*)$
rewrite @gbook /index.php?m=gbook-{re.gbook.1}&{query}
@label path_regexp label ^/label-(.*)$
rewrite @label /index.php?m=label-{re.label.1}&{query}
@map path_regexp map ^/map-(.*)$
rewrite @map /index.php?m=map-{re.map.1}&{query}
