# /index.php/xxx that isn't a real file goes to index.php?p=xxx
@pathinfo {
	not file {
		try_files {path} {path}/
	}
	path_regexp pathinfo ^/index\.php(.*)$
}
rewrite @pathinfo /index.php?p={re.pathinfo.1}&{query}
# Route everything else that isn't a real file or directory to index.php
try_files {path} {path}/ /index.php?s={path}&{query}
