@pathinfo {
	not file {
		try_files {path} {path}/
	}
	path_regexp pathinfo ^/index\.php(.*)$
}
rewrite @pathinfo /index.php?p={re.pathinfo.1}&{query}
try_files {path} {path}/ /index.php?s={path}&{query}
