# PHPCMS rewrite rules
@show path_regexp show ^(.*)show-([0-9]+)-([0-9]+)\.html$
rewrite @show {re.show.1}/show.php?itemid={re.show.2}&page={re.show.3}&{query}
@list path_regexp list ^(.*)list-([0-9]+)-([0-9]+)\.html$
rewrite @list {re.list.1}/list.php?catid={re.list.2}&page={re.list.3}&{query}
@special path_regexp special ^(.*)show-([0-9]+)\.html$
rewrite @special {re.special.1}/show.php?specialid={re.special.2}&{query}
# PHPWind rewrite rules
@htm path_regexp htm ^(.*)-htm-(.*)$
rewrite @htm {re.htm.1}.php?{re.htm.2}&{query}
@simple path_regexp simple ^(.*)/simple/([a-z0-9\_]+\.html)$
rewrite @simple {re.simple.1}/simple/index.php?{re.simple.2}&{query}
