@htm path_regexp htm ^(.*)-htm-(.*)$
rewrite @htm {re.htm.1}.php?{re.htm.2}&{query}
@simple path_regexp simple ^(.*)/simple/([a-z0-9\_]+\.html)$
rewrite @simple {re.simple.1}/simple/index.php?{re.simple.2}&{query}
