@date path_regexp date ^/date/([0-9]{6})/?([0-9]+)?/?$
rewrite @date /index.php?action=article&setdate={re.date.1}&page={re.date.2}&{query}
@page path_regexp page ^/page/([0-9]+)?/?$
rewrite @page /index.php?action=article&page={re.page.1}&{query}
@cid path_regexp cid ^/category/([0-9]+)/?([0-9]+)?/?$
rewrite @cid /index.php?action=article&cid={re.cid.1}&page={re.cid.2}&{query}
@curl path_regexp curl ^/category/([^/]+)/?([0-9]+)?/?$
rewrite @curl /index.php?action=article&curl={re.curl.1}&page={re.curl.2}&{query}
@action path_regexp action ^/(archives|search|article|links)/?$
rewrite @action /index.php?action={re.action.1}&{query}
@actionpage path_regexp actionpage ^/(comments|tagslist|trackbacks|article)/?([0-9]+)?/?$
rewrite @actionpage /index.php?action={re.actionpage.1}&page={re.actionpage.2}&{query}
@tag path_regexp tag ^/tag/([^/]+)/?([0-9]+)?/?$
rewrite @tag /index.php?action=article&item={re.tag.1}&page={re.tag.2}&{query}
@archives path_regexp archives ^/archives/([0-9]+)/?([0-9]+)?/?$
rewrite @archives /index.php?action=show&id={re.archives.1}&page={re.archives.2}&{query}
@rsscid path_regexp rsscid ^/rss/([0-9]+)?/?$
rewrite @rsscid /rss.php?cid={re.rsscid.1}&{query}
@rssurl path_regexp rssurl ^/rss/([^/]+)/?$
rewrite @rssurl /rss.php?url={re.rssurl.1}&{query}
@uid path_regexp uid ^/uid/([0-9]+)/?([0-9]+)?/?$
rewrite @uid /index.php?action=article&uid={re.uid.1}&page={re.uid.2}&{query}
@user path_regexp user ^/user/([^/]+)/?([0-9]+)?/?$
rewrite @user /index.php?action=article&user={re.user.1}&page={re.user.2}&{query}
@sitemap path_regexp sitemap ^/sitemap\.xml$
rewrite @sitemap /sitemap.php
@alias path_regexp alias ^(.*)/([0-9a-zA-Z-\_]+)/?([0-9]+)?/?$
rewrite @alias {re.alias.1}/index.php?action=show&alias={re.alias.2}&page={re.alias.3}&{query}
