@frim path_regexp frim ^/frim/index(.+?)\.html$
rewrite @frim /list/index.php?{re.frim.1}&{query}
@movie path_regexp movie ^/movie/index(.+?)\.html$
rewrite @movie /detail/index.php?{re.movie.1}&{query}
@play path_regexp play ^/play/([0-9]+)-([0-9]+)-([0-9]+)\.html$
rewrite @play /video/index.php?{re.play.1}-{re.play.2}-{re.play.3}&{query}
@topic path_regexp topic ^/topic/index(.+?)\.html$
rewrite @topic /topic/index.php?{re.topic.1}&{query}
@topiclist path_regexp topiclist ^/topiclist/index(.+?)\.html$
rewrite @topiclist /topiclist/index.php?{re.topiclist.1}&{query}
@index path_regexp index ^/index\.html$
redir @index /index.php 301
@news path_regexp news ^/news\.html$
redir @news /news/ 301
@part path_regexp part ^/part/index(.+?)\.html$
rewrite @part /articlelist/index.php?{re.part.1}&{query}
@article path_regexp article ^/article/index(.+?)\.html$
rewrite @article /article/index.php?{re.article.1}&{query}
