# Route everything that isn't a real file or directory to index.php
@notfound {
	not file {
		try_files {path} {path}/
	}
	path_regexp ext ^/(.+\.(html|xml|json|htm|php|jsp|asp|shtml))$
}
rewrite @notfound /index.php?{re.ext.1}&{query}
