# If you want a single domain name at the front and back ends
@admin {
	path /admin*
	not file {
		try_files {path} {path}/
	}
}
rewrite @admin /admin/index.php?{query}
@mobile {
	path /mobile*
	not file {
		try_files {path} {path}/
	}
}
rewrite @mobile /mobile/index.php?{query}
@api {
	path /api*
	not file {
		try_files {path} {path}/
	}
}
rewrite @api /api/index.php?{query}
# Redirect everything that isn't a real file to index.php
try_files {path} {path}/ /index.php?{query}
