try_files {path} {path}/ /index.php?{query}
# Add a trailing slash to /wp-admin when it isn't a real path
@wpadmin {
	path */wp-admin
	not file {
		try_files {path} {path}/
	}
}
redir @wpadmin {path}/{?query} 301
# Serve wp-content, wp-admin and wp-includes of the main site for sub-directory sites
@wpfiles {
	path_regexp wpfiles ^/([^/]+)?(/wp-(content|admin|includes).*)
	not file {
		try_files {path} {path}/
	}
}
rewrite @wpfiles {re.wpfiles.2}
@wpphp {
	path_regexp wpphp ^/([^/]+)?(/[^/]+\.php)$
	not file {
		try_files {path} {path}/
	}
}
rewrite @wpphp {re.wpphp.2}
