//go:build wireinject

package apps

import (
	"github.com/libtnb/wire"

	"github.com/acepanel/panel/v3/internal/apps/apache"
	"github.com/acepanel/panel/v3/internal/apps/caddy"
	"github.com/acepanel/panel/v3/internal/apps/clickhouse"
	"github.com/acepanel/panel/v3/internal/apps/codeserver"
	"github.com/acepanel/panel/v3/internal/apps/docker"
	"github.com/acepanel/panel/v3/internal/apps/elasticsearch"
	"github.com/acepanel/panel/v3/internal/apps/fail2ban"
	"github.com/acepanel/panel/v3/internal/apps/frp"
	"github.com/acepanel/panel/v3/internal/apps/gitea"
	"github.com/acepanel/panel/v3/internal/apps/grafana"
	"github.com/acepanel/panel/v3/internal/apps/kafka"
	"github.com/acepanel/panel/v3/internal/apps/mariadb"
	"github.com/acepanel/panel/v3/internal/apps/memcached"
	"github.com/acepanel/panel/v3/internal/apps/minio"
	"github.com/acepanel/panel/v3/internal/apps/mongodb"
	"github.com/acepanel/panel/v3/internal/apps/mysql"
	"github.com/acepanel/panel/v3/internal/apps/nginx"
	"github.com/acepanel/panel/v3/internal/apps/openlitespeed"
	"github.com/acepanel/panel/v3/internal/apps/openresty"
	"github.com/acepanel/panel/v3/internal/apps/opensearch"
	"github.com/acepanel/panel/v3/internal/apps/percona"
	"github.com/acepanel/panel/v3/internal/apps/pgadmin"
	"github.com/acepanel/panel/v3/internal/apps/phpmyadmin"
	"github.com/acepanel/panel/v3/internal/apps/podman"
	"github.com/acepanel/panel/v3/internal/apps/postgresql"
	"github.com/acepanel/panel/v3/internal/apps/prometheus"
	"github.com/acepanel/panel/v3/internal/apps/pureftpd"
	"github.com/acepanel/panel/v3/internal/apps/redis"
	"github.com/acepanel/panel/v3/internal/apps/rocketmq"
	"github.com/acepanel/panel/v3/internal/apps/rsync"
	"github.com/acepanel/panel/v3/internal/apps/s3fs"
	"github.com/acepanel/panel/v3/internal/apps/supervisor"
	"github.com/acepanel/panel/v3/internal/apps/valkey"
)

// Module 装配全部子应用
var Module = wire.New().
	Provide(apache.NewApp).
	Provide(caddy.NewApp).
	Provide(clickhouse.NewApp).
	Provide(codeserver.NewApp).
	Provide(docker.NewApp).
	Provide(elasticsearch.NewApp).
	Provide(fail2ban.NewApp).
	Provide(frp.NewApp).
	Provide(gitea.NewApp).
	Provide(grafana.NewApp).
	Provide(kafka.NewApp).
	Provide(mariadb.NewApp).
	Provide(memcached.NewApp).
	Provide(minio.NewApp).
	Provide(mongodb.NewApp).
	Provide(mysql.NewApp).
	Provide(nginx.NewApp).
	Provide(openlitespeed.NewApp).
	Provide(openresty.NewApp).
	Provide(opensearch.NewApp).
	Provide(percona.NewApp).
	Provide(pgadmin.NewApp).
	Provide(phpmyadmin.NewApp).
	Provide(podman.NewApp).
	Provide(postgresql.NewApp).
	Provide(prometheus.NewApp).
	Provide(pureftpd.NewApp).
	Provide(redis.NewApp).
	Provide(rocketmq.NewApp).
	Provide(rsync.NewApp).
	Provide(s3fs.NewApp).
	Provide(supervisor.NewApp).
	Provide(valkey.NewApp).
	Export[*apache.App]().
	Export[*caddy.App]().
	Export[*clickhouse.App]().
	Export[*codeserver.App]().
	Export[*docker.App]().
	Export[*elasticsearch.App]().
	Export[*fail2ban.App]().
	Export[*frp.App]().
	Export[*gitea.App]().
	Export[*grafana.App]().
	Export[*kafka.App]().
	Export[*mariadb.App]().
	Export[*memcached.App]().
	Export[*minio.App]().
	Export[*mongodb.App]().
	Export[*mysql.App]().
	Export[*nginx.App]().
	Export[*openlitespeed.App]().
	Export[*openresty.App]().
	Export[*opensearch.App]().
	Export[*percona.App]().
	Export[*pgadmin.App]().
	Export[*phpmyadmin.App]().
	Export[*podman.App]().
	Export[*postgresql.App]().
	Export[*prometheus.App]().
	Export[*pureftpd.App]().
	Export[*redis.App]().
	Export[*rocketmq.App]().
	Export[*rsync.App]().
	Export[*s3fs.App]().
	Export[*supervisor.App]().
	Export[*valkey.App]()
