RewriteRule ^/list-([0-9]+)\.html$ /plus/list.php?tid=$1 [QSA,L]
RewriteRule ^/list-([0-9]+)-([0-9]+)-([0-9]+)\.html$ /plus/list.php?tid=$1&totalresult=$2&PageNo=$3 [QSA,L]
RewriteRule ^/view-([0-9]+)-1\.html$ /plus/view.php?arcID=$1 [QSA,L]
RewriteRule ^/view-([0-9]+)-([0-9]+)\.html$ /plus/view.php?aid=$1&pageno=$2 [QSA,L]
RewriteRule ^/plus/list-([0-9]+)\.html$ /plus/list.php?tid=$1 [QSA,L]
RewriteRule ^/plus/list-([0-9]+)-([0-9]+)-([0-9]+)\.html$ /plus/list.php?tid=$1&totalresult=$2&PageNo=$3 [QSA,L]
RewriteRule ^/plus/view-([0-9]+)-1\.html$ /plus/view.php?arcID=$1 [QSA,L]
RewriteRule ^/plus/view-([0-9]+)-([0-9]+)\.html$ /plus/view.php?aid=$1&pageno=$2 [QSA,L]
RewriteRule ^/tags\.html$ /tags.php [QSA,L]
RewriteRule ^/tag-([0-9]+)-([0-9]+)\.html$ /tags.php?/$1/$2/ [QSA,L]
