RewriteRule ^/vod-(.*)$ /index.php?m=vod-$1 [QSA,L]
RewriteRule ^/art-(.*)$ /index.php?m=art-$1 [QSA,L]
RewriteRule ^/gbook-(.*)$ /index.php?m=gbook-$1 [QSA,L]
RewriteRule ^/label-(.*)$ /index.php?m=label-$1 [QSA,L]
RewriteRule ^/map-(.*)$ /index.php?m=map-$1 [QSA,L]
