RewriteRule ^/date/([0-9]{6})/?([0-9]+)?/?$ /index.php?action=article&setdate=$1&page=$2 [QSA,L]
RewriteRule ^/page/([0-9]+)?/?$ /index.php?action=article&page=$1 [QSA,L]
RewriteRule ^/category/([0-9]+)/?([0-9]+)?/?$ /index.php?action=article&cid=$1&page=$2 [QSA,L]
RewriteRule ^/category/([^/]+)/?([0-9]+)?/?$ /index.php?action=article&curl=$1&page=$2 [QSA,L]
RewriteRule ^/(archives|search|article|links)/?$ /index.php?action=$1 [QSA,L]
RewriteRule ^/(comments|tagslist|trackbacks|article)/?([0-9]+)?/?$ /index.php?action=$1&page=$2 [QSA,L]
RewriteRule ^/tag/([^/]+)/?([0-9]+)?/?$ /index.php?action=article&item=$1&page=$2 [QSA,L]
RewriteRule ^/archives/([0-9]+)/?([0-9]+)?/?$ /index.php?action=show&id=$1&page=$2 [QSA,L]
RewriteRule ^/rss/([0-9]+)?/?$ /rss.php?cid=$1 [QSA,L]
RewriteRule ^/rss/([^/]+)/?$ /rss.php?url=$1 [QSA,L]
RewriteRule ^/uid/([0-9]+)/?([0-9]+)?/?$ /index.php?action=article&uid=$1&page=$2 [QSA,L]
RewriteRule ^/user/([^/]+)/?([0-9]+)?/?$ /index.php?action=article&user=$1&page=$2 [QSA,L]
RewriteRule ^/sitemap\.xml$ /sitemap.php [L]
RewriteRule ^(.*)/([0-9a-zA-Z\-\_]+)/?([0-9]+)?/?$ $1/index.php?action=show&alias=$2&page=$3 [QSA,L]
