// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/pkg/api"
)

// Ensure that AppRepo does implement biz.AppRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.AppRepo = &AppRepo{}

// AppRepo is a mock implementation of biz.AppRepo.
//
//	func TestSomethingThatUsesAppRepo(t *testing.T) {
//
//		// make and configure a mocked biz.AppRepo
//		mockedAppRepo := &AppRepo{
//			CheckPanelVersionFunc: func() error {
//				panic("mock out the CheckPanelVersion method")
//			},
//			DownloadCallbackFunc: func(slug string)  {
//				panic("mock out the DownloadCallback method")
//			},
//			ExecScriptFunc: func(script string) error {
//				panic("mock out the ExecScript method")
//			},
//			GetCustomFunc: func(slug string) (*biz.AppCustom, error) {
//				panic("mock out the GetCustom method")
//			},
//			GetInstalledFunc: func(slug string) (*biz.App, error) {
//				panic("mock out the GetInstalled method")
//			},
//			GetInstalledAllFunc: func(query string, cond ...string) ([]*biz.App, error) {
//				panic("mock out the GetInstalledAll method")
//			},
//			InstalledFunc: func() ([]*biz.App, error) {
//				panic("mock out the Installed method")
//			},
//			IsInstalledFunc: func(query string, cond ...any) (bool, error) {
//				panic("mock out the IsInstalled method")
//			},
//			ListHomeShowFunc: func() ([]*biz.App, error) {
//				panic("mock out the ListHomeShow method")
//			},
//			PreCheckFunc: func(item *api.App, catalog api.Apps) error {
//				panic("mock out the PreCheck method")
//			},
//			ResolveScriptFunc: func(item *api.App, matchChannel string, action string, execVersion string) (string, error) {
//				panic("mock out the ResolveScript method")
//			},
//			SaveCustomFunc: func(slug string, custom *biz.AppCustom) error {
//				panic("mock out the SaveCustom method")
//			},
//			UpdateOrderFunc: func(slugs []string) error {
//				panic("mock out the UpdateOrder method")
//			},
//			UpdateShowFunc: func(slug string, show bool) error {
//				panic("mock out the UpdateShow method")
//			},
//		}
//
//		// use mockedAppRepo in code that requires biz.AppRepo
//		// and then make assertions.
//
//	}
type AppRepo struct {
	// CheckPanelVersionFunc mocks the CheckPanelVersion method.
	CheckPanelVersionFunc func() error

	// DownloadCallbackFunc mocks the DownloadCallback method.
	DownloadCallbackFunc func(slug string)

	// ExecScriptFunc mocks the ExecScript method.
	ExecScriptFunc func(script string) error

	// GetCustomFunc mocks the GetCustom method.
	GetCustomFunc func(slug string) (*biz.AppCustom, error)

	// GetInstalledFunc mocks the GetInstalled method.
	GetInstalledFunc func(slug string) (*biz.App, error)

	// GetInstalledAllFunc mocks the GetInstalledAll method.
	GetInstalledAllFunc func(query string, cond ...string) ([]*biz.App, error)

	// InstalledFunc mocks the Installed method.
	InstalledFunc func() ([]*biz.App, error)

	// IsInstalledFunc mocks the IsInstalled method.
	IsInstalledFunc func(query string, cond ...any) (bool, error)

	// ListHomeShowFunc mocks the ListHomeShow method.
	ListHomeShowFunc func() ([]*biz.App, error)

	// PreCheckFunc mocks the PreCheck method.
	PreCheckFunc func(item *api.App, catalog api.Apps) error

	// ResolveScriptFunc mocks the ResolveScript method.
	ResolveScriptFunc func(item *api.App, matchChannel string, action string, execVersion string) (string, error)

	// SaveCustomFunc mocks the SaveCustom method.
	SaveCustomFunc func(slug string, custom *biz.AppCustom) error

	// UpdateOrderFunc mocks the UpdateOrder method.
	UpdateOrderFunc func(slugs []string) error

	// UpdateShowFunc mocks the UpdateShow method.
	UpdateShowFunc func(slug string, show bool) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckPanelVersion holds details about calls to the CheckPanelVersion method.
		CheckPanelVersion []struct {
		}
		// DownloadCallback holds details about calls to the DownloadCallback method.
		DownloadCallback []struct {
			// Slug is the slug argument value.
			Slug string
		}
		// ExecScript holds details about calls to the ExecScript method.
		ExecScript []struct {
			// Script is the script argument value.
			Script string
		}
		// GetCustom holds details about calls to the GetCustom method.
		GetCustom []struct {
			// Slug is the slug argument value.
			Slug string
		}
		// GetInstalled holds details about calls to the GetInstalled method.
		GetInstalled []struct {
			// Slug is the slug argument value.
			Slug string
		}
		// GetInstalledAll holds details about calls to the GetInstalledAll method.
		GetInstalledAll []struct {
			// Query is the query argument value.
			Query string
			// Cond is the cond argument value.
			Cond []string
		}
		// Installed holds details about calls to the Installed method.
		Installed []struct {
		}
		// IsInstalled holds details about calls to the IsInstalled method.
		IsInstalled []struct {
			// Query is the query argument value.
			Query string
			// Cond is the cond argument value.
			Cond []any
		}
		// ListHomeShow holds details about calls to the ListHomeShow method.
		ListHomeShow []struct {
		}
		// PreCheck holds details about calls to the PreCheck method.
		PreCheck []struct {
			// Item is the item argument value.
			Item *api.App
			// Catalog is the catalog argument value.
			Catalog api.Apps
		}
		// ResolveScript holds details about calls to the ResolveScript method.
		ResolveScript []struct {
			// Item is the item argument value.
			Item *api.App
			// MatchChannel is the matchChannel argument value.
			MatchChannel string
			// Action is the action argument value.
			Action string
			// ExecVersion is the execVersion argument value.
			ExecVersion string
		}
		// SaveCustom holds details about calls to the SaveCustom method.
		SaveCustom []struct {
			// Slug is the slug argument value.
			Slug string
			// Custom is the custom argument value.
			Custom *biz.AppCustom
		}
		// UpdateOrder holds details about calls to the UpdateOrder method.
		UpdateOrder []struct {
			// Slugs is the slugs argument value.
			Slugs []string
		}
		// UpdateShow holds details about calls to the UpdateShow method.
		UpdateShow []struct {
			// Slug is the slug argument value.
			Slug string
			// Show is the show argument value.
			Show bool
		}
	}
	lockCheckPanelVersion sync.RWMutex
	lockDownloadCallback  sync.RWMutex
	lockExecScript        sync.RWMutex
	lockGetCustom         sync.RWMutex
	lockGetInstalled      sync.RWMutex
	lockGetInstalledAll   sync.RWMutex
	lockInstalled         sync.RWMutex
	lockIsInstalled       sync.RWMutex
	lockListHomeShow      sync.RWMutex
	lockPreCheck          sync.RWMutex
	lockResolveScript     sync.RWMutex
	lockSaveCustom        sync.RWMutex
	lockUpdateOrder       sync.RWMutex
	lockUpdateShow        sync.RWMutex
}

// CheckPanelVersion calls CheckPanelVersionFunc.
func (mock *AppRepo) CheckPanelVersion() error {
	if mock.CheckPanelVersionFunc == nil {
		panic("AppRepo.CheckPanelVersionFunc: method is nil but AppRepo.CheckPanelVersion was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCheckPanelVersion.Lock()
	mock.calls.CheckPanelVersion = append(mock.calls.CheckPanelVersion, callInfo)
	mock.lockCheckPanelVersion.Unlock()
	return mock.CheckPanelVersionFunc()
}

// CheckPanelVersionCalls gets all the calls that were made to CheckPanelVersion.
// Check the length with:
//
//	len(mockedAppRepo.CheckPanelVersionCalls())
func (mock *AppRepo) CheckPanelVersionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCheckPanelVersion.RLock()
	calls = mock.calls.CheckPanelVersion
	mock.lockCheckPanelVersion.RUnlock()
	return calls
}

// DownloadCallback calls DownloadCallbackFunc.
func (mock *AppRepo) DownloadCallback(slug string) {
	if mock.DownloadCallbackFunc == nil {
		panic("AppRepo.DownloadCallbackFunc: method is nil but AppRepo.DownloadCallback was just called")
	}
	callInfo := struct {
		Slug string
	}{
		Slug: slug,
	}
	mock.lockDownloadCallback.Lock()
	mock.calls.DownloadCallback = append(mock.calls.DownloadCallback, callInfo)
	mock.lockDownloadCallback.Unlock()
	mock.DownloadCallbackFunc(slug)
}

// DownloadCallbackCalls gets all the calls that were made to DownloadCallback.
// Check the length with:
//
//	len(mockedAppRepo.DownloadCallbackCalls())
func (mock *AppRepo) DownloadCallbackCalls() []struct {
	Slug string
} {
	var calls []struct {
		Slug string
	}
	mock.lockDownloadCallback.RLock()
	calls = mock.calls.DownloadCallback
	mock.lockDownloadCallback.RUnlock()
	return calls
}

// ExecScript calls ExecScriptFunc.
func (mock *AppRepo) ExecScript(script string) error {
	if mock.ExecScriptFunc == nil {
		panic("AppRepo.ExecScriptFunc: method is nil but AppRepo.ExecScript was just called")
	}
	callInfo := struct {
		Script string
	}{
		Script: script,
	}
	mock.lockExecScript.Lock()
	mock.calls.ExecScript = append(mock.calls.ExecScript, callInfo)
	mock.lockExecScript.Unlock()
	return mock.ExecScriptFunc(script)
}

// ExecScriptCalls gets all the calls that were made to ExecScript.
// Check the length with:
//
//	len(mockedAppRepo.ExecScriptCalls())
func (mock *AppRepo) ExecScriptCalls() []struct {
	Script string
} {
	var calls []struct {
		Script string
	}
	mock.lockExecScript.RLock()
	calls = mock.calls.ExecScript
	mock.lockExecScript.RUnlock()
	return calls
}

// GetCustom calls GetCustomFunc.
func (mock *AppRepo) GetCustom(slug string) (*biz.AppCustom, error) {
	if mock.GetCustomFunc == nil {
		panic("AppRepo.GetCustomFunc: method is nil but AppRepo.GetCustom was just called")
	}
	callInfo := struct {
		Slug string
	}{
		Slug: slug,
	}
	mock.lockGetCustom.Lock()
	mock.calls.GetCustom = append(mock.calls.GetCustom, callInfo)
	mock.lockGetCustom.Unlock()
	return mock.GetCustomFunc(slug)
}

// GetCustomCalls gets all the calls that were made to GetCustom.
// Check the length with:
//
//	len(mockedAppRepo.GetCustomCalls())
func (mock *AppRepo) GetCustomCalls() []struct {
	Slug string
} {
	var calls []struct {
		Slug string
	}
	mock.lockGetCustom.RLock()
	calls = mock.calls.GetCustom
	mock.lockGetCustom.RUnlock()
	return calls
}

// GetInstalled calls GetInstalledFunc.
func (mock *AppRepo) GetInstalled(slug string) (*biz.App, error) {
	if mock.GetInstalledFunc == nil {
		panic("AppRepo.GetInstalledFunc: method is nil but AppRepo.GetInstalled was just called")
	}
	callInfo := struct {
		Slug string
	}{
		Slug: slug,
	}
	mock.lockGetInstalled.Lock()
	mock.calls.GetInstalled = append(mock.calls.GetInstalled, callInfo)
	mock.lockGetInstalled.Unlock()
	return mock.GetInstalledFunc(slug)
}

// GetInstalledCalls gets all the calls that were made to GetInstalled.
// Check the length with:
//
//	len(mockedAppRepo.GetInstalledCalls())
func (mock *AppRepo) GetInstalledCalls() []struct {
	Slug string
} {
	var calls []struct {
		Slug string
	}
	mock.lockGetInstalled.RLock()
	calls = mock.calls.GetInstalled
	mock.lockGetInstalled.RUnlock()
	return calls
}

// GetInstalledAll calls GetInstalledAllFunc.
func (mock *AppRepo) GetInstalledAll(query string, cond ...string) ([]*biz.App, error) {
	if mock.GetInstalledAllFunc == nil {
		panic("AppRepo.GetInstalledAllFunc: method is nil but AppRepo.GetInstalledAll was just called")
	}
	callInfo := struct {
		Query string
		Cond  []string
	}{
		Query: query,
		Cond:  cond,
	}
	mock.lockGetInstalledAll.Lock()
	mock.calls.GetInstalledAll = append(mock.calls.GetInstalledAll, callInfo)
	mock.lockGetInstalledAll.Unlock()
	return mock.GetInstalledAllFunc(query, cond...)
}

// GetInstalledAllCalls gets all the calls that were made to GetInstalledAll.
// Check the length with:
//
//	len(mockedAppRepo.GetInstalledAllCalls())
func (mock *AppRepo) GetInstalledAllCalls() []struct {
	Query string
	Cond  []string
} {
	var calls []struct {
		Query string
		Cond  []string
	}
	mock.lockGetInstalledAll.RLock()
	calls = mock.calls.GetInstalledAll
	mock.lockGetInstalledAll.RUnlock()
	return calls
}

// Installed calls InstalledFunc.
func (mock *AppRepo) Installed() ([]*biz.App, error) {
	if mock.InstalledFunc == nil {
		panic("AppRepo.InstalledFunc: method is nil but AppRepo.Installed was just called")
	}
	callInfo := struct {
	}{}
	mock.lockInstalled.Lock()
	mock.calls.Installed = append(mock.calls.Installed, callInfo)
	mock.lockInstalled.Unlock()
	return mock.InstalledFunc()
}

// InstalledCalls gets all the calls that were made to Installed.
// Check the length with:
//
//	len(mockedAppRepo.InstalledCalls())
func (mock *AppRepo) InstalledCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockInstalled.RLock()
	calls = mock.calls.Installed
	mock.lockInstalled.RUnlock()
	return calls
}

// IsInstalled calls IsInstalledFunc.
func (mock *AppRepo) IsInstalled(query string, cond ...any) (bool, error) {
	if mock.IsInstalledFunc == nil {
		panic("AppRepo.IsInstalledFunc: method is nil but AppRepo.IsInstalled was just called")
	}
	callInfo := struct {
		Query string
		Cond  []any
	}{
		Query: query,
		Cond:  cond,
	}
	mock.lockIsInstalled.Lock()
	mock.calls.IsInstalled = append(mock.calls.IsInstalled, callInfo)
	mock.lockIsInstalled.Unlock()
	return mock.IsInstalledFunc(query, cond...)
}

// IsInstalledCalls gets all the calls that were made to IsInstalled.
// Check the length with:
//
//	len(mockedAppRepo.IsInstalledCalls())
func (mock *AppRepo) IsInstalledCalls() []struct {
	Query string
	Cond  []any
} {
	var calls []struct {
		Query string
		Cond  []any
	}
	mock.lockIsInstalled.RLock()
	calls = mock.calls.IsInstalled
	mock.lockIsInstalled.RUnlock()
	return calls
}

// ListHomeShow calls ListHomeShowFunc.
func (mock *AppRepo) ListHomeShow() ([]*biz.App, error) {
	if mock.ListHomeShowFunc == nil {
		panic("AppRepo.ListHomeShowFunc: method is nil but AppRepo.ListHomeShow was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListHomeShow.Lock()
	mock.calls.ListHomeShow = append(mock.calls.ListHomeShow, callInfo)
	mock.lockListHomeShow.Unlock()
	return mock.ListHomeShowFunc()
}

// ListHomeShowCalls gets all the calls that were made to ListHomeShow.
// Check the length with:
//
//	len(mockedAppRepo.ListHomeShowCalls())
func (mock *AppRepo) ListHomeShowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListHomeShow.RLock()
	calls = mock.calls.ListHomeShow
	mock.lockListHomeShow.RUnlock()
	return calls
}

// PreCheck calls PreCheckFunc.
func (mock *AppRepo) PreCheck(item *api.App, catalog api.Apps) error {
	if mock.PreCheckFunc == nil {
		panic("AppRepo.PreCheckFunc: method is nil but AppRepo.PreCheck was just called")
	}
	callInfo := struct {
		Item    *api.App
		Catalog api.Apps
	}{
		Item:    item,
		Catalog: catalog,
	}
	mock.lockPreCheck.Lock()
	mock.calls.PreCheck = append(mock.calls.PreCheck, callInfo)
	mock.lockPreCheck.Unlock()
	return mock.PreCheckFunc(item, catalog)
}

// PreCheckCalls gets all the calls that were made to PreCheck.
// Check the length with:
//
//	len(mockedAppRepo.PreCheckCalls())
func (mock *AppRepo) PreCheckCalls() []struct {
	Item    *api.App
	Catalog api.Apps
} {
	var calls []struct {
		Item    *api.App
		Catalog api.Apps
	}
	mock.lockPreCheck.RLock()
	calls = mock.calls.PreCheck
	mock.lockPreCheck.RUnlock()
	return calls
}

// ResolveScript calls ResolveScriptFunc.
func (mock *AppRepo) ResolveScript(item *api.App, matchChannel string, action string, execVersion string) (string, error) {
	if mock.ResolveScriptFunc == nil {
		panic("AppRepo.ResolveScriptFunc: method is nil but AppRepo.ResolveScript was just called")
	}
	callInfo := struct {
		Item         *api.App
		MatchChannel string
		Action       string
		ExecVersion  string
	}{
		Item:         item,
		MatchChannel: matchChannel,
		Action:       action,
		ExecVersion:  execVersion,
	}
	mock.lockResolveScript.Lock()
	mock.calls.ResolveScript = append(mock.calls.ResolveScript, callInfo)
	mock.lockResolveScript.Unlock()
	return mock.ResolveScriptFunc(item, matchChannel, action, execVersion)
}

// ResolveScriptCalls gets all the calls that were made to ResolveScript.
// Check the length with:
//
//	len(mockedAppRepo.ResolveScriptCalls())
func (mock *AppRepo) ResolveScriptCalls() []struct {
	Item         *api.App
	MatchChannel string
	Action       string
	ExecVersion  string
} {
	var calls []struct {
		Item         *api.App
		MatchChannel string
		Action       string
		ExecVersion  string
	}
	mock.lockResolveScript.RLock()
	calls = mock.calls.ResolveScript
	mock.lockResolveScript.RUnlock()
	return calls
}

// SaveCustom calls SaveCustomFunc.
func (mock *AppRepo) SaveCustom(slug string, custom *biz.AppCustom) error {
	if mock.SaveCustomFunc == nil {
		panic("AppRepo.SaveCustomFunc: method is nil but AppRepo.SaveCustom was just called")
	}
	callInfo := struct {
		Slug   string
		Custom *biz.AppCustom
	}{
		Slug:   slug,
		Custom: custom,
	}
	mock.lockSaveCustom.Lock()
	mock.calls.SaveCustom = append(mock.calls.SaveCustom, callInfo)
	mock.lockSaveCustom.Unlock()
	return mock.SaveCustomFunc(slug, custom)
}

// SaveCustomCalls gets all the calls that were made to SaveCustom.
// Check the length with:
//
//	len(mockedAppRepo.SaveCustomCalls())
func (mock *AppRepo) SaveCustomCalls() []struct {
	Slug   string
	Custom *biz.AppCustom
} {
	var calls []struct {
		Slug   string
		Custom *biz.AppCustom
	}
	mock.lockSaveCustom.RLock()
	calls = mock.calls.SaveCustom
	mock.lockSaveCustom.RUnlock()
	return calls
}

// UpdateOrder calls UpdateOrderFunc.
func (mock *AppRepo) UpdateOrder(slugs []string) error {
	if mock.UpdateOrderFunc == nil {
		panic("AppRepo.UpdateOrderFunc: method is nil but AppRepo.UpdateOrder was just called")
	}
	callInfo := struct {
		Slugs []string
	}{
		Slugs: slugs,
	}
	mock.lockUpdateOrder.Lock()
	mock.calls.UpdateOrder = append(mock.calls.UpdateOrder, callInfo)
	mock.lockUpdateOrder.Unlock()
	return mock.UpdateOrderFunc(slugs)
}

// UpdateOrderCalls gets all the calls that were made to UpdateOrder.
// Check the length with:
//
//	len(mockedAppRepo.UpdateOrderCalls())
func (mock *AppRepo) UpdateOrderCalls() []struct {
	Slugs []string
} {
	var calls []struct {
		Slugs []string
	}
	mock.lockUpdateOrder.RLock()
	calls = mock.calls.UpdateOrder
	mock.lockUpdateOrder.RUnlock()
	return calls
}

// UpdateShow calls UpdateShowFunc.
func (mock *AppRepo) UpdateShow(slug string, show bool) error {
	if mock.UpdateShowFunc == nil {
		panic("AppRepo.UpdateShowFunc: method is nil but AppRepo.UpdateShow was just called")
	}
	callInfo := struct {
		Slug string
		Show bool
	}{
		Slug: slug,
		Show: show,
	}
	mock.lockUpdateShow.Lock()
	mock.calls.UpdateShow = append(mock.calls.UpdateShow, callInfo)
	mock.lockUpdateShow.Unlock()
	return mock.UpdateShowFunc(slug, show)
}

// UpdateShowCalls gets all the calls that were made to UpdateShow.
// Check the length with:
//
//	len(mockedAppRepo.UpdateShowCalls())
func (mock *AppRepo) UpdateShowCalls() []struct {
	Slug string
	Show bool
} {
	var calls []struct {
		Slug string
		Show bool
	}
	mock.lockUpdateShow.RLock()
	calls = mock.calls.UpdateShow
	mock.lockUpdateShow.RUnlock()
	return calls
}
