// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/pkg/types"
)

// Ensure that BackupRepo does implement biz.BackupRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.BackupRepo = &BackupRepo{}

// BackupRepo is a mock implementation of biz.BackupRepo.
//
//	func TestSomethingThatUsesBackupRepo(t *testing.T) {
//
//		// make and configure a mocked biz.BackupRepo
//		mockedBackupRepo := &BackupRepo{
//			ClearExpiredFunc: func(path string, prefix string, save uint) error {
//				panic("mock out the ClearExpired method")
//			},
//			ClearStorageExpiredFunc: func(account uint, dir string, prefix string, save uint) error {
//				panic("mock out the ClearStorageExpired method")
//			},
//			CreateFunc: func(ctx context.Context, typ biz.BackupType, target string, account uint) error {
//				panic("mock out the Create method")
//			},
//			CreatePanelFunc: func(ctx context.Context) error {
//				panic("mock out the CreatePanel method")
//			},
//			CutoffLogFunc: func(ctx context.Context, path string, target string) (string, error) {
//				panic("mock out the CutoffLog method")
//			},
//			CutoffUploadFunc: func(account uint, typ biz.BackupType, name string, files []string) error {
//				panic("mock out the CutoffUpload method")
//			},
//			DeleteFunc: func(ctx context.Context, typ biz.BackupType, name string) error {
//				panic("mock out the Delete method")
//			},
//			FixPanelFunc: func(ctx context.Context) error {
//				panic("mock out the FixPanel method")
//			},
//			GetDefaultPathFunc: func(typ biz.BackupType) string {
//				panic("mock out the GetDefaultPath method")
//			},
//			GetStorageFunc: func(id uint) (*biz.BackupStorage, error) {
//				panic("mock out the GetStorage method")
//			},
//			ListFunc: func(typ biz.BackupType) ([]*types.BackupFile, error) {
//				panic("mock out the List method")
//			},
//			RestoreFunc: func(ctx context.Context, typ biz.BackupType, backup string, target string) error {
//				panic("mock out the Restore method")
//			},
//			UpdatePanelFunc: func(ctx context.Context, version string, url string, checksum string, progress func(string)) error {
//				panic("mock out the UpdatePanel method")
//			},
//		}
//
//		// use mockedBackupRepo in code that requires biz.BackupRepo
//		// and then make assertions.
//
//	}
type BackupRepo struct {
	// ClearExpiredFunc mocks the ClearExpired method.
	ClearExpiredFunc func(path string, prefix string, save uint) error

	// ClearStorageExpiredFunc mocks the ClearStorageExpired method.
	ClearStorageExpiredFunc func(account uint, dir string, prefix string, save uint) error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, typ biz.BackupType, target string, account uint) error

	// CreatePanelFunc mocks the CreatePanel method.
	CreatePanelFunc func(ctx context.Context) error

	// CutoffLogFunc mocks the CutoffLog method.
	CutoffLogFunc func(ctx context.Context, path string, target string) (string, error)

	// CutoffUploadFunc mocks the CutoffUpload method.
	CutoffUploadFunc func(account uint, typ biz.BackupType, name string, files []string) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, typ biz.BackupType, name string) error

	// FixPanelFunc mocks the FixPanel method.
	FixPanelFunc func(ctx context.Context) error

	// GetDefaultPathFunc mocks the GetDefaultPath method.
	GetDefaultPathFunc func(typ biz.BackupType) string

	// GetStorageFunc mocks the GetStorage method.
	GetStorageFunc func(id uint) (*biz.BackupStorage, error)

	// ListFunc mocks the List method.
	ListFunc func(typ biz.BackupType) ([]*types.BackupFile, error)

	// RestoreFunc mocks the Restore method.
	RestoreFunc func(ctx context.Context, typ biz.BackupType, backup string, target string) error

	// UpdatePanelFunc mocks the UpdatePanel method.
	UpdatePanelFunc func(ctx context.Context, version string, url string, checksum string, progress func(string)) error

	// calls tracks calls to the methods.
	calls struct {
		// ClearExpired holds details about calls to the ClearExpired method.
		ClearExpired []struct {
			// Path is the path argument value.
			Path string
			// Prefix is the prefix argument value.
			Prefix string
			// Save is the save argument value.
			Save uint
		}
		// ClearStorageExpired holds details about calls to the ClearStorageExpired method.
		ClearStorageExpired []struct {
			// Account is the account argument value.
			Account uint
			// Dir is the dir argument value.
			Dir string
			// Prefix is the prefix argument value.
			Prefix string
			// Save is the save argument value.
			Save uint
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Typ is the typ argument value.
			Typ biz.BackupType
			// Target is the target argument value.
			Target string
			// Account is the account argument value.
			Account uint
		}
		// CreatePanel holds details about calls to the CreatePanel method.
		CreatePanel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CutoffLog holds details about calls to the CutoffLog method.
		CutoffLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Target is the target argument value.
			Target string
		}
		// CutoffUpload holds details about calls to the CutoffUpload method.
		CutoffUpload []struct {
			// Account is the account argument value.
			Account uint
			// Typ is the typ argument value.
			Typ biz.BackupType
			// Name is the name argument value.
			Name string
			// Files is the files argument value.
			Files []string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Typ is the typ argument value.
			Typ biz.BackupType
			// Name is the name argument value.
			Name string
		}
		// FixPanel holds details about calls to the FixPanel method.
		FixPanel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetDefaultPath holds details about calls to the GetDefaultPath method.
		GetDefaultPath []struct {
			// Typ is the typ argument value.
			Typ biz.BackupType
		}
		// GetStorage holds details about calls to the GetStorage method.
		GetStorage []struct {
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
			// Typ is the typ argument value.
			Typ biz.BackupType
		}
		// Restore holds details about calls to the Restore method.
		Restore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Typ is the typ argument value.
			Typ biz.BackupType
			// Backup is the backup argument value.
			Backup string
			// Target is the target argument value.
			Target string
		}
		// UpdatePanel holds details about calls to the UpdatePanel method.
		UpdatePanel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Version is the version argument value.
			Version string
			// URL is the url argument value.
			URL string
			// Checksum is the checksum argument value.
			Checksum string
			// Progress is the progress argument value.
			Progress func(string)
		}
	}
	lockClearExpired        sync.RWMutex
	lockClearStorageExpired sync.RWMutex
	lockCreate              sync.RWMutex
	lockCreatePanel         sync.RWMutex
	lockCutoffLog           sync.RWMutex
	lockCutoffUpload        sync.RWMutex
	lockDelete              sync.RWMutex
	lockFixPanel            sync.RWMutex
	lockGetDefaultPath      sync.RWMutex
	lockGetStorage          sync.RWMutex
	lockList                sync.RWMutex
	lockRestore             sync.RWMutex
	lockUpdatePanel         sync.RWMutex
}

// ClearExpired calls ClearExpiredFunc.
func (mock *BackupRepo) ClearExpired(path string, prefix string, save uint) error {
	if mock.ClearExpiredFunc == nil {
		panic("BackupRepo.ClearExpiredFunc: method is nil but BackupRepo.ClearExpired was just called")
	}
	callInfo := struct {
		Path   string
		Prefix string
		Save   uint
	}{
		Path:   path,
		Prefix: prefix,
		Save:   save,
	}
	mock.lockClearExpired.Lock()
	mock.calls.ClearExpired = append(mock.calls.ClearExpired, callInfo)
	mock.lockClearExpired.Unlock()
	return mock.ClearExpiredFunc(path, prefix, save)
}

// ClearExpiredCalls gets all the calls that were made to ClearExpired.
// Check the length with:
//
//	len(mockedBackupRepo.ClearExpiredCalls())
func (mock *BackupRepo) ClearExpiredCalls() []struct {
	Path   string
	Prefix string
	Save   uint
} {
	var calls []struct {
		Path   string
		Prefix string
		Save   uint
	}
	mock.lockClearExpired.RLock()
	calls = mock.calls.ClearExpired
	mock.lockClearExpired.RUnlock()
	return calls
}

// ClearStorageExpired calls ClearStorageExpiredFunc.
func (mock *BackupRepo) ClearStorageExpired(account uint, dir string, prefix string, save uint) error {
	if mock.ClearStorageExpiredFunc == nil {
		panic("BackupRepo.ClearStorageExpiredFunc: method is nil but BackupRepo.ClearStorageExpired was just called")
	}
	callInfo := struct {
		Account uint
		Dir     string
		Prefix  string
		Save    uint
	}{
		Account: account,
		Dir:     dir,
		Prefix:  prefix,
		Save:    save,
	}
	mock.lockClearStorageExpired.Lock()
	mock.calls.ClearStorageExpired = append(mock.calls.ClearStorageExpired, callInfo)
	mock.lockClearStorageExpired.Unlock()
	return mock.ClearStorageExpiredFunc(account, dir, prefix, save)
}

// ClearStorageExpiredCalls gets all the calls that were made to ClearStorageExpired.
// Check the length with:
//
//	len(mockedBackupRepo.ClearStorageExpiredCalls())
func (mock *BackupRepo) ClearStorageExpiredCalls() []struct {
	Account uint
	Dir     string
	Prefix  string
	Save    uint
} {
	var calls []struct {
		Account uint
		Dir     string
		Prefix  string
		Save    uint
	}
	mock.lockClearStorageExpired.RLock()
	calls = mock.calls.ClearStorageExpired
	mock.lockClearStorageExpired.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *BackupRepo) Create(ctx context.Context, typ biz.BackupType, target string, account uint) error {
	if mock.CreateFunc == nil {
		panic("BackupRepo.CreateFunc: method is nil but BackupRepo.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Typ     biz.BackupType
		Target  string
		Account uint
	}{
		Ctx:     ctx,
		Typ:     typ,
		Target:  target,
		Account: account,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, typ, target, account)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedBackupRepo.CreateCalls())
func (mock *BackupRepo) CreateCalls() []struct {
	Ctx     context.Context
	Typ     biz.BackupType
	Target  string
	Account uint
} {
	var calls []struct {
		Ctx     context.Context
		Typ     biz.BackupType
		Target  string
		Account uint
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// CreatePanel calls CreatePanelFunc.
func (mock *BackupRepo) CreatePanel(ctx context.Context) error {
	if mock.CreatePanelFunc == nil {
		panic("BackupRepo.CreatePanelFunc: method is nil but BackupRepo.CreatePanel was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCreatePanel.Lock()
	mock.calls.CreatePanel = append(mock.calls.CreatePanel, callInfo)
	mock.lockCreatePanel.Unlock()
	return mock.CreatePanelFunc(ctx)
}

// CreatePanelCalls gets all the calls that were made to CreatePanel.
// Check the length with:
//
//	len(mockedBackupRepo.CreatePanelCalls())
func (mock *BackupRepo) CreatePanelCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCreatePanel.RLock()
	calls = mock.calls.CreatePanel
	mock.lockCreatePanel.RUnlock()
	return calls
}

// CutoffLog calls CutoffLogFunc.
func (mock *BackupRepo) CutoffLog(ctx context.Context, path string, target string) (string, error) {
	if mock.CutoffLogFunc == nil {
		panic("BackupRepo.CutoffLogFunc: method is nil but BackupRepo.CutoffLog was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Path   string
		Target string
	}{
		Ctx:    ctx,
		Path:   path,
		Target: target,
	}
	mock.lockCutoffLog.Lock()
	mock.calls.CutoffLog = append(mock.calls.CutoffLog, callInfo)
	mock.lockCutoffLog.Unlock()
	return mock.CutoffLogFunc(ctx, path, target)
}

// CutoffLogCalls gets all the calls that were made to CutoffLog.
// Check the length with:
//
//	len(mockedBackupRepo.CutoffLogCalls())
func (mock *BackupRepo) CutoffLogCalls() []struct {
	Ctx    context.Context
	Path   string
	Target string
} {
	var calls []struct {
		Ctx    context.Context
		Path   string
		Target string
	}
	mock.lockCutoffLog.RLock()
	calls = mock.calls.CutoffLog
	mock.lockCutoffLog.RUnlock()
	return calls
}

// CutoffUpload calls CutoffUploadFunc.
func (mock *BackupRepo) CutoffUpload(account uint, typ biz.BackupType, name string, files []string) error {
	if mock.CutoffUploadFunc == nil {
		panic("BackupRepo.CutoffUploadFunc: method is nil but BackupRepo.CutoffUpload was just called")
	}
	callInfo := struct {
		Account uint
		Typ     biz.BackupType
		Name    string
		Files   []string
	}{
		Account: account,
		Typ:     typ,
		Name:    name,
		Files:   files,
	}
	mock.lockCutoffUpload.Lock()
	mock.calls.CutoffUpload = append(mock.calls.CutoffUpload, callInfo)
	mock.lockCutoffUpload.Unlock()
	return mock.CutoffUploadFunc(account, typ, name, files)
}

// CutoffUploadCalls gets all the calls that were made to CutoffUpload.
// Check the length with:
//
//	len(mockedBackupRepo.CutoffUploadCalls())
func (mock *BackupRepo) CutoffUploadCalls() []struct {
	Account uint
	Typ     biz.BackupType
	Name    string
	Files   []string
} {
	var calls []struct {
		Account uint
		Typ     biz.BackupType
		Name    string
		Files   []string
	}
	mock.lockCutoffUpload.RLock()
	calls = mock.calls.CutoffUpload
	mock.lockCutoffUpload.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *BackupRepo) Delete(ctx context.Context, typ biz.BackupType, name string) error {
	if mock.DeleteFunc == nil {
		panic("BackupRepo.DeleteFunc: method is nil but BackupRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Typ  biz.BackupType
		Name string
	}{
		Ctx:  ctx,
		Typ:  typ,
		Name: name,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, typ, name)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedBackupRepo.DeleteCalls())
func (mock *BackupRepo) DeleteCalls() []struct {
	Ctx  context.Context
	Typ  biz.BackupType
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Typ  biz.BackupType
		Name string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FixPanel calls FixPanelFunc.
func (mock *BackupRepo) FixPanel(ctx context.Context) error {
	if mock.FixPanelFunc == nil {
		panic("BackupRepo.FixPanelFunc: method is nil but BackupRepo.FixPanel was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFixPanel.Lock()
	mock.calls.FixPanel = append(mock.calls.FixPanel, callInfo)
	mock.lockFixPanel.Unlock()
	return mock.FixPanelFunc(ctx)
}

// FixPanelCalls gets all the calls that were made to FixPanel.
// Check the length with:
//
//	len(mockedBackupRepo.FixPanelCalls())
func (mock *BackupRepo) FixPanelCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFixPanel.RLock()
	calls = mock.calls.FixPanel
	mock.lockFixPanel.RUnlock()
	return calls
}

// GetDefaultPath calls GetDefaultPathFunc.
func (mock *BackupRepo) GetDefaultPath(typ biz.BackupType) string {
	if mock.GetDefaultPathFunc == nil {
		panic("BackupRepo.GetDefaultPathFunc: method is nil but BackupRepo.GetDefaultPath was just called")
	}
	callInfo := struct {
		Typ biz.BackupType
	}{
		Typ: typ,
	}
	mock.lockGetDefaultPath.Lock()
	mock.calls.GetDefaultPath = append(mock.calls.GetDefaultPath, callInfo)
	mock.lockGetDefaultPath.Unlock()
	return mock.GetDefaultPathFunc(typ)
}

// GetDefaultPathCalls gets all the calls that were made to GetDefaultPath.
// Check the length with:
//
//	len(mockedBackupRepo.GetDefaultPathCalls())
func (mock *BackupRepo) GetDefaultPathCalls() []struct {
	Typ biz.BackupType
} {
	var calls []struct {
		Typ biz.BackupType
	}
	mock.lockGetDefaultPath.RLock()
	calls = mock.calls.GetDefaultPath
	mock.lockGetDefaultPath.RUnlock()
	return calls
}

// GetStorage calls GetStorageFunc.
func (mock *BackupRepo) GetStorage(id uint) (*biz.BackupStorage, error) {
	if mock.GetStorageFunc == nil {
		panic("BackupRepo.GetStorageFunc: method is nil but BackupRepo.GetStorage was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGetStorage.Lock()
	mock.calls.GetStorage = append(mock.calls.GetStorage, callInfo)
	mock.lockGetStorage.Unlock()
	return mock.GetStorageFunc(id)
}

// GetStorageCalls gets all the calls that were made to GetStorage.
// Check the length with:
//
//	len(mockedBackupRepo.GetStorageCalls())
func (mock *BackupRepo) GetStorageCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGetStorage.RLock()
	calls = mock.calls.GetStorage
	mock.lockGetStorage.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *BackupRepo) List(typ biz.BackupType) ([]*types.BackupFile, error) {
	if mock.ListFunc == nil {
		panic("BackupRepo.ListFunc: method is nil but BackupRepo.List was just called")
	}
	callInfo := struct {
		Typ biz.BackupType
	}{
		Typ: typ,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(typ)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedBackupRepo.ListCalls())
func (mock *BackupRepo) ListCalls() []struct {
	Typ biz.BackupType
} {
	var calls []struct {
		Typ biz.BackupType
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Restore calls RestoreFunc.
func (mock *BackupRepo) Restore(ctx context.Context, typ biz.BackupType, backup string, target string) error {
	if mock.RestoreFunc == nil {
		panic("BackupRepo.RestoreFunc: method is nil but BackupRepo.Restore was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Typ    biz.BackupType
		Backup string
		Target string
	}{
		Ctx:    ctx,
		Typ:    typ,
		Backup: backup,
		Target: target,
	}
	mock.lockRestore.Lock()
	mock.calls.Restore = append(mock.calls.Restore, callInfo)
	mock.lockRestore.Unlock()
	return mock.RestoreFunc(ctx, typ, backup, target)
}

// RestoreCalls gets all the calls that were made to Restore.
// Check the length with:
//
//	len(mockedBackupRepo.RestoreCalls())
func (mock *BackupRepo) RestoreCalls() []struct {
	Ctx    context.Context
	Typ    biz.BackupType
	Backup string
	Target string
} {
	var calls []struct {
		Ctx    context.Context
		Typ    biz.BackupType
		Backup string
		Target string
	}
	mock.lockRestore.RLock()
	calls = mock.calls.Restore
	mock.lockRestore.RUnlock()
	return calls
}

// UpdatePanel calls UpdatePanelFunc.
func (mock *BackupRepo) UpdatePanel(ctx context.Context, version string, url string, checksum string, progress func(string)) error {
	if mock.UpdatePanelFunc == nil {
		panic("BackupRepo.UpdatePanelFunc: method is nil but BackupRepo.UpdatePanel was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Version  string
		URL      string
		Checksum string
		Progress func(string)
	}{
		Ctx:      ctx,
		Version:  version,
		URL:      url,
		Checksum: checksum,
		Progress: progress,
	}
	mock.lockUpdatePanel.Lock()
	mock.calls.UpdatePanel = append(mock.calls.UpdatePanel, callInfo)
	mock.lockUpdatePanel.Unlock()
	return mock.UpdatePanelFunc(ctx, version, url, checksum, progress)
}

// UpdatePanelCalls gets all the calls that were made to UpdatePanel.
// Check the length with:
//
//	len(mockedBackupRepo.UpdatePanelCalls())
func (mock *BackupRepo) UpdatePanelCalls() []struct {
	Ctx      context.Context
	Version  string
	URL      string
	Checksum string
	Progress func(string)
} {
	var calls []struct {
		Ctx      context.Context
		Version  string
		URL      string
		Checksum string
		Progress func(string)
	}
	mock.lockUpdatePanel.RLock()
	calls = mock.calls.UpdatePanel
	mock.lockUpdatePanel.RUnlock()
	return calls
}
