// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/internal/request"
)

// Ensure that CertDNSRepo does implement biz.CertDNSRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.CertDNSRepo = &CertDNSRepo{}

// CertDNSRepo is a mock implementation of biz.CertDNSRepo.
//
//	func TestSomethingThatUsesCertDNSRepo(t *testing.T) {
//
//		// make and configure a mocked biz.CertDNSRepo
//		mockedCertDNSRepo := &CertDNSRepo{
//			CreateFunc: func(req *request.CertDNSCreate) (*biz.CertDNS, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(id uint) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(id uint) (*biz.CertDNS, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(page uint, limit uint) ([]*biz.CertDNS, int64, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(req *request.CertDNSUpdate) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedCertDNSRepo in code that requires biz.CertDNSRepo
//		// and then make assertions.
//
//	}
type CertDNSRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(req *request.CertDNSCreate) (*biz.CertDNS, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uint) error

	// GetFunc mocks the Get method.
	GetFunc func(id uint) (*biz.CertDNS, error)

	// ListFunc mocks the List method.
	ListFunc func(page uint, limit uint) ([]*biz.CertDNS, int64, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(req *request.CertDNSUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Req is the req argument value.
			Req *request.CertDNSCreate
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uint
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
			// Page is the page argument value.
			Page uint
			// Limit is the limit argument value.
			Limit uint
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Req is the req argument value.
			Req *request.CertDNSUpdate
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *CertDNSRepo) Create(req *request.CertDNSCreate) (*biz.CertDNS, error) {
	if mock.CreateFunc == nil {
		panic("CertDNSRepo.CreateFunc: method is nil but CertDNSRepo.Create was just called")
	}
	callInfo := struct {
		Req *request.CertDNSCreate
	}{
		Req: req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedCertDNSRepo.CreateCalls())
func (mock *CertDNSRepo) CreateCalls() []struct {
	Req *request.CertDNSCreate
} {
	var calls []struct {
		Req *request.CertDNSCreate
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *CertDNSRepo) Delete(id uint) error {
	if mock.DeleteFunc == nil {
		panic("CertDNSRepo.DeleteFunc: method is nil but CertDNSRepo.Delete was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedCertDNSRepo.DeleteCalls())
func (mock *CertDNSRepo) DeleteCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *CertDNSRepo) Get(id uint) (*biz.CertDNS, error) {
	if mock.GetFunc == nil {
		panic("CertDNSRepo.GetFunc: method is nil but CertDNSRepo.Get was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCertDNSRepo.GetCalls())
func (mock *CertDNSRepo) GetCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *CertDNSRepo) List(page uint, limit uint) ([]*biz.CertDNS, int64, error) {
	if mock.ListFunc == nil {
		panic("CertDNSRepo.ListFunc: method is nil but CertDNSRepo.List was just called")
	}
	callInfo := struct {
		Page  uint
		Limit uint
	}{
		Page:  page,
		Limit: limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(page, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedCertDNSRepo.ListCalls())
func (mock *CertDNSRepo) ListCalls() []struct {
	Page  uint
	Limit uint
} {
	var calls []struct {
		Page  uint
		Limit uint
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *CertDNSRepo) Update(req *request.CertDNSUpdate) error {
	if mock.UpdateFunc == nil {
		panic("CertDNSRepo.UpdateFunc: method is nil but CertDNSRepo.Update was just called")
	}
	callInfo := struct {
		Req *request.CertDNSUpdate
	}{
		Req: req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedCertDNSRepo.UpdateCalls())
func (mock *CertDNSRepo) UpdateCalls() []struct {
	Req *request.CertDNSUpdate
} {
	var calls []struct {
		Req *request.CertDNSUpdate
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
