// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/internal/request"
	"github.com/acepanel/panel/v3/pkg/types"
)

// Ensure that ContainerImageRepo does implement biz.ContainerImageRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.ContainerImageRepo = &ContainerImageRepo{}

// ContainerImageRepo is a mock implementation of biz.ContainerImageRepo.
//
//	func TestSomethingThatUsesContainerImageRepo(t *testing.T) {
//
//		// make and configure a mocked biz.ContainerImageRepo
//		mockedContainerImageRepo := &ContainerImageRepo{
//			ExistFunc: func(ctx context.Context, sock string, name string) (bool, error) {
//				panic("mock out the Exist method")
//			},
//			ListFunc: func(ctx context.Context, sock string) ([]types.ContainerImage, error) {
//				panic("mock out the List method")
//			},
//			PruneFunc: func(ctx context.Context, sock string) error {
//				panic("mock out the Prune method")
//			},
//			PullFunc: func(ctx context.Context, sock string, req *request.ContainerImagePull) error {
//				panic("mock out the Pull method")
//			},
//			RemoveFunc: func(ctx context.Context, sock string, id string) error {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedContainerImageRepo in code that requires biz.ContainerImageRepo
//		// and then make assertions.
//
//	}
type ContainerImageRepo struct {
	// ExistFunc mocks the Exist method.
	ExistFunc func(ctx context.Context, sock string, name string) (bool, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, sock string) ([]types.ContainerImage, error)

	// PruneFunc mocks the Prune method.
	PruneFunc func(ctx context.Context, sock string) error

	// PullFunc mocks the Pull method.
	PullFunc func(ctx context.Context, sock string, req *request.ContainerImagePull) error

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, sock string, id string) error

	// calls tracks calls to the methods.
	calls struct {
		// Exist holds details about calls to the Exist method.
		Exist []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sock is the sock argument value.
			Sock string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sock is the sock argument value.
			Sock string
		}
		// Prune holds details about calls to the Prune method.
		Prune []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sock is the sock argument value.
			Sock string
		}
		// Pull holds details about calls to the Pull method.
		Pull []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sock is the sock argument value.
			Sock string
			// Req is the req argument value.
			Req *request.ContainerImagePull
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sock is the sock argument value.
			Sock string
			// ID is the id argument value.
			ID string
		}
	}
	lockExist  sync.RWMutex
	lockList   sync.RWMutex
	lockPrune  sync.RWMutex
	lockPull   sync.RWMutex
	lockRemove sync.RWMutex
}

// Exist calls ExistFunc.
func (mock *ContainerImageRepo) Exist(ctx context.Context, sock string, name string) (bool, error) {
	if mock.ExistFunc == nil {
		panic("ContainerImageRepo.ExistFunc: method is nil but ContainerImageRepo.Exist was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Sock string
		Name string
	}{
		Ctx:  ctx,
		Sock: sock,
		Name: name,
	}
	mock.lockExist.Lock()
	mock.calls.Exist = append(mock.calls.Exist, callInfo)
	mock.lockExist.Unlock()
	return mock.ExistFunc(ctx, sock, name)
}

// ExistCalls gets all the calls that were made to Exist.
// Check the length with:
//
//	len(mockedContainerImageRepo.ExistCalls())
func (mock *ContainerImageRepo) ExistCalls() []struct {
	Ctx  context.Context
	Sock string
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Sock string
		Name string
	}
	mock.lockExist.RLock()
	calls = mock.calls.Exist
	mock.lockExist.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ContainerImageRepo) List(ctx context.Context, sock string) ([]types.ContainerImage, error) {
	if mock.ListFunc == nil {
		panic("ContainerImageRepo.ListFunc: method is nil but ContainerImageRepo.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Sock string
	}{
		Ctx:  ctx,
		Sock: sock,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, sock)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedContainerImageRepo.ListCalls())
func (mock *ContainerImageRepo) ListCalls() []struct {
	Ctx  context.Context
	Sock string
} {
	var calls []struct {
		Ctx  context.Context
		Sock string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Prune calls PruneFunc.
func (mock *ContainerImageRepo) Prune(ctx context.Context, sock string) error {
	if mock.PruneFunc == nil {
		panic("ContainerImageRepo.PruneFunc: method is nil but ContainerImageRepo.Prune was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Sock string
	}{
		Ctx:  ctx,
		Sock: sock,
	}
	mock.lockPrune.Lock()
	mock.calls.Prune = append(mock.calls.Prune, callInfo)
	mock.lockPrune.Unlock()
	return mock.PruneFunc(ctx, sock)
}

// PruneCalls gets all the calls that were made to Prune.
// Check the length with:
//
//	len(mockedContainerImageRepo.PruneCalls())
func (mock *ContainerImageRepo) PruneCalls() []struct {
	Ctx  context.Context
	Sock string
} {
	var calls []struct {
		Ctx  context.Context
		Sock string
	}
	mock.lockPrune.RLock()
	calls = mock.calls.Prune
	mock.lockPrune.RUnlock()
	return calls
}

// Pull calls PullFunc.
func (mock *ContainerImageRepo) Pull(ctx context.Context, sock string, req *request.ContainerImagePull) error {
	if mock.PullFunc == nil {
		panic("ContainerImageRepo.PullFunc: method is nil but ContainerImageRepo.Pull was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Sock string
		Req  *request.ContainerImagePull
	}{
		Ctx:  ctx,
		Sock: sock,
		Req:  req,
	}
	mock.lockPull.Lock()
	mock.calls.Pull = append(mock.calls.Pull, callInfo)
	mock.lockPull.Unlock()
	return mock.PullFunc(ctx, sock, req)
}

// PullCalls gets all the calls that were made to Pull.
// Check the length with:
//
//	len(mockedContainerImageRepo.PullCalls())
func (mock *ContainerImageRepo) PullCalls() []struct {
	Ctx  context.Context
	Sock string
	Req  *request.ContainerImagePull
} {
	var calls []struct {
		Ctx  context.Context
		Sock string
		Req  *request.ContainerImagePull
	}
	mock.lockPull.RLock()
	calls = mock.calls.Pull
	mock.lockPull.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *ContainerImageRepo) Remove(ctx context.Context, sock string, id string) error {
	if mock.RemoveFunc == nil {
		panic("ContainerImageRepo.RemoveFunc: method is nil but ContainerImageRepo.Remove was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Sock string
		ID   string
	}{
		Ctx:  ctx,
		Sock: sock,
		ID:   id,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, sock, id)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedContainerImageRepo.RemoveCalls())
func (mock *ContainerImageRepo) RemoveCalls() []struct {
	Ctx  context.Context
	Sock string
	ID   string
} {
	var calls []struct {
		Ctx  context.Context
		Sock string
		ID   string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
