// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/internal/request"
	"github.com/acepanel/panel/v3/pkg/types"
)

// Ensure that ContainerNetworkRepo does implement biz.ContainerNetworkRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.ContainerNetworkRepo = &ContainerNetworkRepo{}

// ContainerNetworkRepo is a mock implementation of biz.ContainerNetworkRepo.
//
//	func TestSomethingThatUsesContainerNetworkRepo(t *testing.T) {
//
//		// make and configure a mocked biz.ContainerNetworkRepo
//		mockedContainerNetworkRepo := &ContainerNetworkRepo{
//			CreateFunc: func(sock string, req *request.ContainerNetworkCreate) (string, error) {
//				panic("mock out the Create method")
//			},
//			ListFunc: func(sock string) ([]types.ContainerNetwork, error) {
//				panic("mock out the List method")
//			},
//			PruneFunc: func(sock string) error {
//				panic("mock out the Prune method")
//			},
//			RemoveFunc: func(sock string, id string) error {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedContainerNetworkRepo in code that requires biz.ContainerNetworkRepo
//		// and then make assertions.
//
//	}
type ContainerNetworkRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(sock string, req *request.ContainerNetworkCreate) (string, error)

	// ListFunc mocks the List method.
	ListFunc func(sock string) ([]types.ContainerNetwork, error)

	// PruneFunc mocks the Prune method.
	PruneFunc func(sock string) error

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(sock string, id string) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Sock is the sock argument value.
			Sock string
			// Req is the req argument value.
			Req *request.ContainerNetworkCreate
		}
		// List holds details about calls to the List method.
		List []struct {
			// Sock is the sock argument value.
			Sock string
		}
		// Prune holds details about calls to the Prune method.
		Prune []struct {
			// Sock is the sock argument value.
			Sock string
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Sock is the sock argument value.
			Sock string
			// ID is the id argument value.
			ID string
		}
	}
	lockCreate sync.RWMutex
	lockList   sync.RWMutex
	lockPrune  sync.RWMutex
	lockRemove sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ContainerNetworkRepo) Create(sock string, req *request.ContainerNetworkCreate) (string, error) {
	if mock.CreateFunc == nil {
		panic("ContainerNetworkRepo.CreateFunc: method is nil but ContainerNetworkRepo.Create was just called")
	}
	callInfo := struct {
		Sock string
		Req  *request.ContainerNetworkCreate
	}{
		Sock: sock,
		Req:  req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(sock, req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedContainerNetworkRepo.CreateCalls())
func (mock *ContainerNetworkRepo) CreateCalls() []struct {
	Sock string
	Req  *request.ContainerNetworkCreate
} {
	var calls []struct {
		Sock string
		Req  *request.ContainerNetworkCreate
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ContainerNetworkRepo) List(sock string) ([]types.ContainerNetwork, error) {
	if mock.ListFunc == nil {
		panic("ContainerNetworkRepo.ListFunc: method is nil but ContainerNetworkRepo.List was just called")
	}
	callInfo := struct {
		Sock string
	}{
		Sock: sock,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(sock)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedContainerNetworkRepo.ListCalls())
func (mock *ContainerNetworkRepo) ListCalls() []struct {
	Sock string
} {
	var calls []struct {
		Sock string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Prune calls PruneFunc.
func (mock *ContainerNetworkRepo) Prune(sock string) error {
	if mock.PruneFunc == nil {
		panic("ContainerNetworkRepo.PruneFunc: method is nil but ContainerNetworkRepo.Prune was just called")
	}
	callInfo := struct {
		Sock string
	}{
		Sock: sock,
	}
	mock.lockPrune.Lock()
	mock.calls.Prune = append(mock.calls.Prune, callInfo)
	mock.lockPrune.Unlock()
	return mock.PruneFunc(sock)
}

// PruneCalls gets all the calls that were made to Prune.
// Check the length with:
//
//	len(mockedContainerNetworkRepo.PruneCalls())
func (mock *ContainerNetworkRepo) PruneCalls() []struct {
	Sock string
} {
	var calls []struct {
		Sock string
	}
	mock.lockPrune.RLock()
	calls = mock.calls.Prune
	mock.lockPrune.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *ContainerNetworkRepo) Remove(sock string, id string) error {
	if mock.RemoveFunc == nil {
		panic("ContainerNetworkRepo.RemoveFunc: method is nil but ContainerNetworkRepo.Remove was just called")
	}
	callInfo := struct {
		Sock string
		ID   string
	}{
		Sock: sock,
		ID:   id,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(sock, id)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedContainerNetworkRepo.RemoveCalls())
func (mock *ContainerNetworkRepo) RemoveCalls() []struct {
	Sock string
	ID   string
} {
	var calls []struct {
		Sock string
		ID   string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
