// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"
	"time"

	"github.com/acepanel/panel/v3/internal/biz"
)

// Ensure that FileShareRepo does implement biz.FileShareRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.FileShareRepo = &FileShareRepo{}

// FileShareRepo is a mock implementation of biz.FileShareRepo.
//
//	func TestSomethingThatUsesFileShareRepo(t *testing.T) {
//
//		// make and configure a mocked biz.FileShareRepo
//		mockedFileShareRepo := &FileShareRepo{
//			ClearExpiredFunc: func() (int64, error) {
//				panic("mock out the ClearExpired method")
//			},
//			ConsumeFunc: func(token string, count bool) (*biz.FileShare, error) {
//				panic("mock out the Consume method")
//			},
//			CreateFunc: func(path string, maxDownloads uint, expiredAt time.Time) (*biz.FileShare, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(id uint) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(id uint) (*biz.FileShare, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func() ([]*biz.FileShare, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedFileShareRepo in code that requires biz.FileShareRepo
//		// and then make assertions.
//
//	}
type FileShareRepo struct {
	// ClearExpiredFunc mocks the ClearExpired method.
	ClearExpiredFunc func() (int64, error)

	// ConsumeFunc mocks the Consume method.
	ConsumeFunc func(token string, count bool) (*biz.FileShare, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(path string, maxDownloads uint, expiredAt time.Time) (*biz.FileShare, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uint) error

	// GetFunc mocks the Get method.
	GetFunc func(id uint) (*biz.FileShare, error)

	// ListFunc mocks the List method.
	ListFunc func() ([]*biz.FileShare, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClearExpired holds details about calls to the ClearExpired method.
		ClearExpired []struct {
		}
		// Consume holds details about calls to the Consume method.
		Consume []struct {
			// Token is the token argument value.
			Token string
			// Count is the count argument value.
			Count bool
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Path is the path argument value.
			Path string
			// MaxDownloads is the maxDownloads argument value.
			MaxDownloads uint
			// ExpiredAt is the expiredAt argument value.
			ExpiredAt time.Time
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uint
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
		}
	}
	lockClearExpired sync.RWMutex
	lockConsume      sync.RWMutex
	lockCreate       sync.RWMutex
	lockDelete       sync.RWMutex
	lockGet          sync.RWMutex
	lockList         sync.RWMutex
}

// ClearExpired calls ClearExpiredFunc.
func (mock *FileShareRepo) ClearExpired() (int64, error) {
	if mock.ClearExpiredFunc == nil {
		panic("FileShareRepo.ClearExpiredFunc: method is nil but FileShareRepo.ClearExpired was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClearExpired.Lock()
	mock.calls.ClearExpired = append(mock.calls.ClearExpired, callInfo)
	mock.lockClearExpired.Unlock()
	return mock.ClearExpiredFunc()
}

// ClearExpiredCalls gets all the calls that were made to ClearExpired.
// Check the length with:
//
//	len(mockedFileShareRepo.ClearExpiredCalls())
func (mock *FileShareRepo) ClearExpiredCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClearExpired.RLock()
	calls = mock.calls.ClearExpired
	mock.lockClearExpired.RUnlock()
	return calls
}

// Consume calls ConsumeFunc.
func (mock *FileShareRepo) Consume(token string, count bool) (*biz.FileShare, error) {
	if mock.ConsumeFunc == nil {
		panic("FileShareRepo.ConsumeFunc: method is nil but FileShareRepo.Consume was just called")
	}
	callInfo := struct {
		Token string
		Count bool
	}{
		Token: token,
		Count: count,
	}
	mock.lockConsume.Lock()
	mock.calls.Consume = append(mock.calls.Consume, callInfo)
	mock.lockConsume.Unlock()
	return mock.ConsumeFunc(token, count)
}

// ConsumeCalls gets all the calls that were made to Consume.
// Check the length with:
//
//	len(mockedFileShareRepo.ConsumeCalls())
func (mock *FileShareRepo) ConsumeCalls() []struct {
	Token string
	Count bool
} {
	var calls []struct {
		Token string
		Count bool
	}
	mock.lockConsume.RLock()
	calls = mock.calls.Consume
	mock.lockConsume.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *FileShareRepo) Create(path string, maxDownloads uint, expiredAt time.Time) (*biz.FileShare, error) {
	if mock.CreateFunc == nil {
		panic("FileShareRepo.CreateFunc: method is nil but FileShareRepo.Create was just called")
	}
	callInfo := struct {
		Path         string
		MaxDownloads uint
		ExpiredAt    time.Time
	}{
		Path:         path,
		MaxDownloads: maxDownloads,
		ExpiredAt:    expiredAt,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(path, maxDownloads, expiredAt)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedFileShareRepo.CreateCalls())
func (mock *FileShareRepo) CreateCalls() []struct {
	Path         string
	MaxDownloads uint
	ExpiredAt    time.Time
} {
	var calls []struct {
		Path         string
		MaxDownloads uint
		ExpiredAt    time.Time
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *FileShareRepo) Delete(id uint) error {
	if mock.DeleteFunc == nil {
		panic("FileShareRepo.DeleteFunc: method is nil but FileShareRepo.Delete was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedFileShareRepo.DeleteCalls())
func (mock *FileShareRepo) DeleteCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *FileShareRepo) Get(id uint) (*biz.FileShare, error) {
	if mock.GetFunc == nil {
		panic("FileShareRepo.GetFunc: method is nil but FileShareRepo.Get was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedFileShareRepo.GetCalls())
func (mock *FileShareRepo) GetCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *FileShareRepo) List() ([]*biz.FileShare, error) {
	if mock.ListFunc == nil {
		panic("FileShareRepo.ListFunc: method is nil but FileShareRepo.List was just called")
	}
	callInfo := struct {
	}{}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc()
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedFileShareRepo.ListCalls())
func (mock *FileShareRepo) ListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
