// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
)

// Ensure that LogRepo does implement biz.LogRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.LogRepo = &LogRepo{}

// LogRepo is a mock implementation of biz.LogRepo.
//
//	func TestSomethingThatUsesLogRepo(t *testing.T) {
//
//		// make and configure a mocked biz.LogRepo
//		mockedLogRepo := &LogRepo{
//			CleanFunc: func(logType string, date string) error {
//				panic("mock out the Clean method")
//			},
//			ListFunc: func(logType string, limit int, date string) ([]biz.LogEntry, error) {
//				panic("mock out the List method")
//			},
//			ListDatesFunc: func(logType string) ([]string, error) {
//				panic("mock out the ListDates method")
//			},
//		}
//
//		// use mockedLogRepo in code that requires biz.LogRepo
//		// and then make assertions.
//
//	}
type LogRepo struct {
	// CleanFunc mocks the Clean method.
	CleanFunc func(logType string, date string) error

	// ListFunc mocks the List method.
	ListFunc func(logType string, limit int, date string) ([]biz.LogEntry, error)

	// ListDatesFunc mocks the ListDates method.
	ListDatesFunc func(logType string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clean holds details about calls to the Clean method.
		Clean []struct {
			// LogType is the logType argument value.
			LogType string
			// Date is the date argument value.
			Date string
		}
		// List holds details about calls to the List method.
		List []struct {
			// LogType is the logType argument value.
			LogType string
			// Limit is the limit argument value.
			Limit int
			// Date is the date argument value.
			Date string
		}
		// ListDates holds details about calls to the ListDates method.
		ListDates []struct {
			// LogType is the logType argument value.
			LogType string
		}
	}
	lockClean     sync.RWMutex
	lockList      sync.RWMutex
	lockListDates sync.RWMutex
}

// Clean calls CleanFunc.
func (mock *LogRepo) Clean(logType string, date string) error {
	if mock.CleanFunc == nil {
		panic("LogRepo.CleanFunc: method is nil but LogRepo.Clean was just called")
	}
	callInfo := struct {
		LogType string
		Date    string
	}{
		LogType: logType,
		Date:    date,
	}
	mock.lockClean.Lock()
	mock.calls.Clean = append(mock.calls.Clean, callInfo)
	mock.lockClean.Unlock()
	return mock.CleanFunc(logType, date)
}

// CleanCalls gets all the calls that were made to Clean.
// Check the length with:
//
//	len(mockedLogRepo.CleanCalls())
func (mock *LogRepo) CleanCalls() []struct {
	LogType string
	Date    string
} {
	var calls []struct {
		LogType string
		Date    string
	}
	mock.lockClean.RLock()
	calls = mock.calls.Clean
	mock.lockClean.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *LogRepo) List(logType string, limit int, date string) ([]biz.LogEntry, error) {
	if mock.ListFunc == nil {
		panic("LogRepo.ListFunc: method is nil but LogRepo.List was just called")
	}
	callInfo := struct {
		LogType string
		Limit   int
		Date    string
	}{
		LogType: logType,
		Limit:   limit,
		Date:    date,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(logType, limit, date)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedLogRepo.ListCalls())
func (mock *LogRepo) ListCalls() []struct {
	LogType string
	Limit   int
	Date    string
} {
	var calls []struct {
		LogType string
		Limit   int
		Date    string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListDates calls ListDatesFunc.
func (mock *LogRepo) ListDates(logType string) ([]string, error) {
	if mock.ListDatesFunc == nil {
		panic("LogRepo.ListDatesFunc: method is nil but LogRepo.ListDates was just called")
	}
	callInfo := struct {
		LogType string
	}{
		LogType: logType,
	}
	mock.lockListDates.Lock()
	mock.calls.ListDates = append(mock.calls.ListDates, callInfo)
	mock.lockListDates.Unlock()
	return mock.ListDatesFunc(logType)
}

// ListDatesCalls gets all the calls that were made to ListDates.
// Check the length with:
//
//	len(mockedLogRepo.ListDatesCalls())
func (mock *LogRepo) ListDatesCalls() []struct {
	LogType string
} {
	var calls []struct {
		LogType string
	}
	mock.lockListDates.RLock()
	calls = mock.calls.ListDates
	mock.lockListDates.RUnlock()
	return calls
}
