// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
)

// Ensure that SafeRepo does implement biz.SafeRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.SafeRepo = &SafeRepo{}

// SafeRepo is a mock implementation of biz.SafeRepo.
//
//	func TestSomethingThatUsesSafeRepo(t *testing.T) {
//
//		// make and configure a mocked biz.SafeRepo
//		mockedSafeRepo := &SafeRepo{
//			FirewallRunningFunc: func() (bool, error) {
//				panic("mock out the FirewallRunning method")
//			},
//			GetPingStatusFunc: func() (bool, error) {
//				panic("mock out the GetPingStatus method")
//			},
//			SetPingStatusFunc: func(status bool) error {
//				panic("mock out the SetPingStatus method")
//			},
//		}
//
//		// use mockedSafeRepo in code that requires biz.SafeRepo
//		// and then make assertions.
//
//	}
type SafeRepo struct {
	// FirewallRunningFunc mocks the FirewallRunning method.
	FirewallRunningFunc func() (bool, error)

	// GetPingStatusFunc mocks the GetPingStatus method.
	GetPingStatusFunc func() (bool, error)

	// SetPingStatusFunc mocks the SetPingStatus method.
	SetPingStatusFunc func(status bool) error

	// calls tracks calls to the methods.
	calls struct {
		// FirewallRunning holds details about calls to the FirewallRunning method.
		FirewallRunning []struct {
		}
		// GetPingStatus holds details about calls to the GetPingStatus method.
		GetPingStatus []struct {
		}
		// SetPingStatus holds details about calls to the SetPingStatus method.
		SetPingStatus []struct {
			// Status is the status argument value.
			Status bool
		}
	}
	lockFirewallRunning sync.RWMutex
	lockGetPingStatus   sync.RWMutex
	lockSetPingStatus   sync.RWMutex
}

// FirewallRunning calls FirewallRunningFunc.
func (mock *SafeRepo) FirewallRunning() (bool, error) {
	if mock.FirewallRunningFunc == nil {
		panic("SafeRepo.FirewallRunningFunc: method is nil but SafeRepo.FirewallRunning was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFirewallRunning.Lock()
	mock.calls.FirewallRunning = append(mock.calls.FirewallRunning, callInfo)
	mock.lockFirewallRunning.Unlock()
	return mock.FirewallRunningFunc()
}

// FirewallRunningCalls gets all the calls that were made to FirewallRunning.
// Check the length with:
//
//	len(mockedSafeRepo.FirewallRunningCalls())
func (mock *SafeRepo) FirewallRunningCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFirewallRunning.RLock()
	calls = mock.calls.FirewallRunning
	mock.lockFirewallRunning.RUnlock()
	return calls
}

// GetPingStatus calls GetPingStatusFunc.
func (mock *SafeRepo) GetPingStatus() (bool, error) {
	if mock.GetPingStatusFunc == nil {
		panic("SafeRepo.GetPingStatusFunc: method is nil but SafeRepo.GetPingStatus was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPingStatus.Lock()
	mock.calls.GetPingStatus = append(mock.calls.GetPingStatus, callInfo)
	mock.lockGetPingStatus.Unlock()
	return mock.GetPingStatusFunc()
}

// GetPingStatusCalls gets all the calls that were made to GetPingStatus.
// Check the length with:
//
//	len(mockedSafeRepo.GetPingStatusCalls())
func (mock *SafeRepo) GetPingStatusCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPingStatus.RLock()
	calls = mock.calls.GetPingStatus
	mock.lockGetPingStatus.RUnlock()
	return calls
}

// SetPingStatus calls SetPingStatusFunc.
func (mock *SafeRepo) SetPingStatus(status bool) error {
	if mock.SetPingStatusFunc == nil {
		panic("SafeRepo.SetPingStatusFunc: method is nil but SafeRepo.SetPingStatus was just called")
	}
	callInfo := struct {
		Status bool
	}{
		Status: status,
	}
	mock.lockSetPingStatus.Lock()
	mock.calls.SetPingStatus = append(mock.calls.SetPingStatus, callInfo)
	mock.lockSetPingStatus.Unlock()
	return mock.SetPingStatusFunc(status)
}

// SetPingStatusCalls gets all the calls that were made to SetPingStatus.
// Check the length with:
//
//	len(mockedSafeRepo.SetPingStatusCalls())
func (mock *SafeRepo) SetPingStatusCalls() []struct {
	Status bool
} {
	var calls []struct {
		Status bool
	}
	mock.lockSetPingStatus.RLock()
	calls = mock.calls.SetPingStatus
	mock.lockSetPingStatus.RUnlock()
	return calls
}
