// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/acepanel/panel/v3/internal/biz"
	"github.com/acepanel/panel/v3/internal/request"
)

// Ensure that SSHRepo does implement biz.SSHRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.SSHRepo = &SSHRepo{}

// SSHRepo is a mock implementation of biz.SSHRepo.
//
//	func TestSomethingThatUsesSSHRepo(t *testing.T) {
//
//		// make and configure a mocked biz.SSHRepo
//		mockedSSHRepo := &SSHRepo{
//			CreateFunc: func(req *request.SSHCreate) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(id uint) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(id uint) (*biz.SSH, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(page uint, limit uint) ([]*biz.SSH, int64, error) {
//				panic("mock out the List method")
//			},
//			ListFilesFunc: func(hostID uint, path string) ([]*biz.SSHFileInfo, error) {
//				panic("mock out the ListFiles method")
//			},
//			MkdirFunc: func(hostID uint, path string) error {
//				panic("mock out the Mkdir method")
//			},
//			TransferFileFunc: func(ctx context.Context, srcID uint, srcPath string, dstID uint, dstPath string, progress func(transferred int64, total int64)) error {
//				panic("mock out the TransferFile method")
//			},
//			UpdateFunc: func(req *request.SSHUpdate) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedSSHRepo in code that requires biz.SSHRepo
//		// and then make assertions.
//
//	}
type SSHRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(req *request.SSHCreate) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uint) error

	// GetFunc mocks the Get method.
	GetFunc func(id uint) (*biz.SSH, error)

	// ListFunc mocks the List method.
	ListFunc func(page uint, limit uint) ([]*biz.SSH, int64, error)

	// ListFilesFunc mocks the ListFiles method.
	ListFilesFunc func(hostID uint, path string) ([]*biz.SSHFileInfo, error)

	// MkdirFunc mocks the Mkdir method.
	MkdirFunc func(hostID uint, path string) error

	// TransferFileFunc mocks the TransferFile method.
	TransferFileFunc func(ctx context.Context, srcID uint, srcPath string, dstID uint, dstPath string, progress func(transferred int64, total int64)) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(req *request.SSHUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Req is the req argument value.
			Req *request.SSHCreate
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uint
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
			// Page is the page argument value.
			Page uint
			// Limit is the limit argument value.
			Limit uint
		}
		// ListFiles holds details about calls to the ListFiles method.
		ListFiles []struct {
			// HostID is the hostID argument value.
			HostID uint
			// Path is the path argument value.
			Path string
		}
		// Mkdir holds details about calls to the Mkdir method.
		Mkdir []struct {
			// HostID is the hostID argument value.
			HostID uint
			// Path is the path argument value.
			Path string
		}
		// TransferFile holds details about calls to the TransferFile method.
		TransferFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SrcID is the srcID argument value.
			SrcID uint
			// SrcPath is the srcPath argument value.
			SrcPath string
			// DstID is the dstID argument value.
			DstID uint
			// DstPath is the dstPath argument value.
			DstPath string
			// Progress is the progress argument value.
			Progress func(transferred int64, total int64)
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Req is the req argument value.
			Req *request.SSHUpdate
		}
	}
	lockCreate       sync.RWMutex
	lockDelete       sync.RWMutex
	lockGet          sync.RWMutex
	lockList         sync.RWMutex
	lockListFiles    sync.RWMutex
	lockMkdir        sync.RWMutex
	lockTransferFile sync.RWMutex
	lockUpdate       sync.RWMutex
}

// Create calls CreateFunc.
func (mock *SSHRepo) Create(req *request.SSHCreate) error {
	if mock.CreateFunc == nil {
		panic("SSHRepo.CreateFunc: method is nil but SSHRepo.Create was just called")
	}
	callInfo := struct {
		Req *request.SSHCreate
	}{
		Req: req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSSHRepo.CreateCalls())
func (mock *SSHRepo) CreateCalls() []struct {
	Req *request.SSHCreate
} {
	var calls []struct {
		Req *request.SSHCreate
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *SSHRepo) Delete(id uint) error {
	if mock.DeleteFunc == nil {
		panic("SSHRepo.DeleteFunc: method is nil but SSHRepo.Delete was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedSSHRepo.DeleteCalls())
func (mock *SSHRepo) DeleteCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *SSHRepo) Get(id uint) (*biz.SSH, error) {
	if mock.GetFunc == nil {
		panic("SSHRepo.GetFunc: method is nil but SSHRepo.Get was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSSHRepo.GetCalls())
func (mock *SSHRepo) GetCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *SSHRepo) List(page uint, limit uint) ([]*biz.SSH, int64, error) {
	if mock.ListFunc == nil {
		panic("SSHRepo.ListFunc: method is nil but SSHRepo.List was just called")
	}
	callInfo := struct {
		Page  uint
		Limit uint
	}{
		Page:  page,
		Limit: limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(page, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedSSHRepo.ListCalls())
func (mock *SSHRepo) ListCalls() []struct {
	Page  uint
	Limit uint
} {
	var calls []struct {
		Page  uint
		Limit uint
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListFiles calls ListFilesFunc.
func (mock *SSHRepo) ListFiles(hostID uint, path string) ([]*biz.SSHFileInfo, error) {
	if mock.ListFilesFunc == nil {
		panic("SSHRepo.ListFilesFunc: method is nil but SSHRepo.ListFiles was just called")
	}
	callInfo := struct {
		HostID uint
		Path   string
	}{
		HostID: hostID,
		Path:   path,
	}
	mock.lockListFiles.Lock()
	mock.calls.ListFiles = append(mock.calls.ListFiles, callInfo)
	mock.lockListFiles.Unlock()
	return mock.ListFilesFunc(hostID, path)
}

// ListFilesCalls gets all the calls that were made to ListFiles.
// Check the length with:
//
//	len(mockedSSHRepo.ListFilesCalls())
func (mock *SSHRepo) ListFilesCalls() []struct {
	HostID uint
	Path   string
} {
	var calls []struct {
		HostID uint
		Path   string
	}
	mock.lockListFiles.RLock()
	calls = mock.calls.ListFiles
	mock.lockListFiles.RUnlock()
	return calls
}

// Mkdir calls MkdirFunc.
func (mock *SSHRepo) Mkdir(hostID uint, path string) error {
	if mock.MkdirFunc == nil {
		panic("SSHRepo.MkdirFunc: method is nil but SSHRepo.Mkdir was just called")
	}
	callInfo := struct {
		HostID uint
		Path   string
	}{
		HostID: hostID,
		Path:   path,
	}
	mock.lockMkdir.Lock()
	mock.calls.Mkdir = append(mock.calls.Mkdir, callInfo)
	mock.lockMkdir.Unlock()
	return mock.MkdirFunc(hostID, path)
}

// MkdirCalls gets all the calls that were made to Mkdir.
// Check the length with:
//
//	len(mockedSSHRepo.MkdirCalls())
func (mock *SSHRepo) MkdirCalls() []struct {
	HostID uint
	Path   string
} {
	var calls []struct {
		HostID uint
		Path   string
	}
	mock.lockMkdir.RLock()
	calls = mock.calls.Mkdir
	mock.lockMkdir.RUnlock()
	return calls
}

// TransferFile calls TransferFileFunc.
func (mock *SSHRepo) TransferFile(ctx context.Context, srcID uint, srcPath string, dstID uint, dstPath string, progress func(transferred int64, total int64)) error {
	if mock.TransferFileFunc == nil {
		panic("SSHRepo.TransferFileFunc: method is nil but SSHRepo.TransferFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SrcID    uint
		SrcPath  string
		DstID    uint
		DstPath  string
		Progress func(transferred int64, total int64)
	}{
		Ctx:      ctx,
		SrcID:    srcID,
		SrcPath:  srcPath,
		DstID:    dstID,
		DstPath:  dstPath,
		Progress: progress,
	}
	mock.lockTransferFile.Lock()
	mock.calls.TransferFile = append(mock.calls.TransferFile, callInfo)
	mock.lockTransferFile.Unlock()
	return mock.TransferFileFunc(ctx, srcID, srcPath, dstID, dstPath, progress)
}

// TransferFileCalls gets all the calls that were made to TransferFile.
// Check the length with:
//
//	len(mockedSSHRepo.TransferFileCalls())
func (mock *SSHRepo) TransferFileCalls() []struct {
	Ctx      context.Context
	SrcID    uint
	SrcPath  string
	DstID    uint
	DstPath  string
	Progress func(transferred int64, total int64)
} {
	var calls []struct {
		Ctx      context.Context
		SrcID    uint
		SrcPath  string
		DstID    uint
		DstPath  string
		Progress func(transferred int64, total int64)
	}
	mock.lockTransferFile.RLock()
	calls = mock.calls.TransferFile
	mock.lockTransferFile.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *SSHRepo) Update(req *request.SSHUpdate) error {
	if mock.UpdateFunc == nil {
		panic("SSHRepo.UpdateFunc: method is nil but SSHRepo.Update was just called")
	}
	callInfo := struct {
		Req *request.SSHUpdate
	}{
		Req: req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedSSHRepo.UpdateCalls())
func (mock *SSHRepo) UpdateCalls() []struct {
	Req *request.SSHUpdate
} {
	var calls []struct {
		Req *request.SSHUpdate
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
