// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"net/http"
	"sync"
	"time"

	"github.com/acepanel/panel/v3/internal/biz"
)

// Ensure that UserTokenRepo does implement biz.UserTokenRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.UserTokenRepo = &UserTokenRepo{}

// UserTokenRepo is a mock implementation of biz.UserTokenRepo.
//
//	func TestSomethingThatUsesUserTokenRepo(t *testing.T) {
//
//		// make and configure a mocked biz.UserTokenRepo
//		mockedUserTokenRepo := &UserTokenRepo{
//			CreateFunc: func(userID uint, ips []string, expired time.Time) (*biz.UserToken, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(id uint) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(id uint) (*biz.UserToken, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(userID uint, page uint, limit uint) ([]*biz.UserToken, int64, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(id uint, ips []string, expired time.Time) (*biz.UserToken, error) {
//				panic("mock out the Update method")
//			},
//			ValidateReqFunc: func(req *http.Request) (uint, error) {
//				panic("mock out the ValidateReq method")
//			},
//		}
//
//		// use mockedUserTokenRepo in code that requires biz.UserTokenRepo
//		// and then make assertions.
//
//	}
type UserTokenRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(userID uint, ips []string, expired time.Time) (*biz.UserToken, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uint) error

	// GetFunc mocks the Get method.
	GetFunc func(id uint) (*biz.UserToken, error)

	// ListFunc mocks the List method.
	ListFunc func(userID uint, page uint, limit uint) ([]*biz.UserToken, int64, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id uint, ips []string, expired time.Time) (*biz.UserToken, error)

	// ValidateReqFunc mocks the ValidateReq method.
	ValidateReqFunc func(req *http.Request) (uint, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// UserID is the userID argument value.
			UserID uint
			// Ips is the ips argument value.
			Ips []string
			// Expired is the expired argument value.
			Expired time.Time
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uint
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
			// UserID is the userID argument value.
			UserID uint
			// Page is the page argument value.
			Page uint
			// Limit is the limit argument value.
			Limit uint
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID uint
			// Ips is the ips argument value.
			Ips []string
			// Expired is the expired argument value.
			Expired time.Time
		}
		// ValidateReq holds details about calls to the ValidateReq method.
		ValidateReq []struct {
			// Req is the req argument value.
			Req *http.Request
		}
	}
	lockCreate      sync.RWMutex
	lockDelete      sync.RWMutex
	lockGet         sync.RWMutex
	lockList        sync.RWMutex
	lockUpdate      sync.RWMutex
	lockValidateReq sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserTokenRepo) Create(userID uint, ips []string, expired time.Time) (*biz.UserToken, error) {
	if mock.CreateFunc == nil {
		panic("UserTokenRepo.CreateFunc: method is nil but UserTokenRepo.Create was just called")
	}
	callInfo := struct {
		UserID  uint
		Ips     []string
		Expired time.Time
	}{
		UserID:  userID,
		Ips:     ips,
		Expired: expired,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(userID, ips, expired)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserTokenRepo.CreateCalls())
func (mock *UserTokenRepo) CreateCalls() []struct {
	UserID  uint
	Ips     []string
	Expired time.Time
} {
	var calls []struct {
		UserID  uint
		Ips     []string
		Expired time.Time
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserTokenRepo) Delete(id uint) error {
	if mock.DeleteFunc == nil {
		panic("UserTokenRepo.DeleteFunc: method is nil but UserTokenRepo.Delete was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserTokenRepo.DeleteCalls())
func (mock *UserTokenRepo) DeleteCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UserTokenRepo) Get(id uint) (*biz.UserToken, error) {
	if mock.GetFunc == nil {
		panic("UserTokenRepo.GetFunc: method is nil but UserTokenRepo.Get was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUserTokenRepo.GetCalls())
func (mock *UserTokenRepo) GetCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserTokenRepo) List(userID uint, page uint, limit uint) ([]*biz.UserToken, int64, error) {
	if mock.ListFunc == nil {
		panic("UserTokenRepo.ListFunc: method is nil but UserTokenRepo.List was just called")
	}
	callInfo := struct {
		UserID uint
		Page   uint
		Limit  uint
	}{
		UserID: userID,
		Page:   page,
		Limit:  limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(userID, page, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserTokenRepo.ListCalls())
func (mock *UserTokenRepo) ListCalls() []struct {
	UserID uint
	Page   uint
	Limit  uint
} {
	var calls []struct {
		UserID uint
		Page   uint
		Limit  uint
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserTokenRepo) Update(id uint, ips []string, expired time.Time) (*biz.UserToken, error) {
	if mock.UpdateFunc == nil {
		panic("UserTokenRepo.UpdateFunc: method is nil but UserTokenRepo.Update was just called")
	}
	callInfo := struct {
		ID      uint
		Ips     []string
		Expired time.Time
	}{
		ID:      id,
		Ips:     ips,
		Expired: expired,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, ips, expired)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserTokenRepo.UpdateCalls())
func (mock *UserTokenRepo) UpdateCalls() []struct {
	ID      uint
	Ips     []string
	Expired time.Time
} {
	var calls []struct {
		ID      uint
		Ips     []string
		Expired time.Time
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ValidateReq calls ValidateReqFunc.
func (mock *UserTokenRepo) ValidateReq(req *http.Request) (uint, error) {
	if mock.ValidateReqFunc == nil {
		panic("UserTokenRepo.ValidateReqFunc: method is nil but UserTokenRepo.ValidateReq was just called")
	}
	callInfo := struct {
		Req *http.Request
	}{
		Req: req,
	}
	mock.lockValidateReq.Lock()
	mock.calls.ValidateReq = append(mock.calls.ValidateReq, callInfo)
	mock.lockValidateReq.Unlock()
	return mock.ValidateReqFunc(req)
}

// ValidateReqCalls gets all the calls that were made to ValidateReq.
// Check the length with:
//
//	len(mockedUserTokenRepo.ValidateReqCalls())
func (mock *UserTokenRepo) ValidateReqCalls() []struct {
	Req *http.Request
} {
	var calls []struct {
		Req *http.Request
	}
	mock.lockValidateReq.RLock()
	calls = mock.calls.ValidateReq
	mock.lockValidateReq.RUnlock()
	return calls
}
