name: Test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          cache: true
          go-version-file: go.mod
      - name: Install dependencies
        run: sudo apt-get install -y curl jq
      - name: Set up environment
        run: |
          cp config.example.yml config.yml
      - name: Verify dependency injection
        run: go tool wire check ./...
      - name: Run tests
        run: sudo go test -v -race -coverprofile="coverage.out" ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v7
        with:
          disable_search: true
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
