package apache

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/acepanel/panel/v3/pkg/webserver/types"
)

// StaticVhost 纯静态虚拟主机
type StaticVhost struct {
	*baseVhost
}

// PHPVhost PHP 虚拟主机
type PHPVhost struct {
	*baseVhost
}

// ProxyVhost 反向代理虚拟主机
type ProxyVhost struct {
	*baseVhost
}

// baseVhost Apache 虚拟主机基础实现
type baseVhost struct {
	config    *Config
	vhost     *Block // 主 VirtualHost 块
	configDir string
	siteName  string
}

// newBaseVhost 创建基础虚拟主机实例
func newBaseVhost(configDir string) (*baseVhost, error) {
	if configDir == "" {
		return nil, fmt.Errorf("config directory is required")
	}

	v := &baseVhost{
		configDir: configDir,
		siteName:  filepath.Base(filepath.Dir(configDir)),
	}

	// 从配置目录加载主配置文件
	var config *Config
	configFile := filepath.Join(configDir, "apache.conf")
	if _, err := os.Stat(configFile); err == nil {
		config, err = ParseFile(configFile)
		if err != nil {
			return nil, fmt.Errorf("failed to parse apache config: %w", err)
		}
	}

	// 没有配置文件则使用默认配置
	if config == nil {
		var err error
		config, err = ParseString(v.defaultConf())
		if err != nil {
			return nil, fmt.Errorf("failed to parse default config: %w", err)
		}
	}

	v.config = config
	if vhosts := config.VirtualHosts(); len(vhosts) > 0 {
		v.vhost = vhosts[0]
	} else {
		v.vhost = config.AddVirtualHost("*:80")
	}

	return v, nil
}

// defaultConf 返回替换好站点名的默认配置模板
func (v *baseVhost) defaultConf() string {
	return strings.ReplaceAll(DefaultVhostConf, "/opt/ace/sites/default", fmt.Sprintf("/opt/ace/sites/%s", v.siteName))
}

// NewStaticVhost 创建纯静态虚拟主机实例
func NewStaticVhost(configDir string) (*StaticVhost, error) {
	base, err := newBaseVhost(configDir)
	if err != nil {
		return nil, err
	}
	return &StaticVhost{baseVhost: base}, nil
}

// NewPHPVhost 创建 PHP 虚拟主机实例
func NewPHPVhost(configDir string) (*PHPVhost, error) {
	base, err := newBaseVhost(configDir)
	if err != nil {
		return nil, err
	}
	return &PHPVhost{baseVhost: base}, nil
}

// NewProxyVhost 创建反向代理虚拟主机实例
func NewProxyVhost(configDir string) (*ProxyVhost, error) {
	base, err := newBaseVhost(configDir)
	if err != nil {
		return nil, err
	}
	return &ProxyVhost{baseVhost: base}, nil
}

func (v *baseVhost) Enable() bool {
	disableConf := filepath.Join(v.configDir, "site", "00-disable.conf")
	_, err := os.Stat(disableConf)
	return os.IsNotExist(err)
}

func (v *baseVhost) SetEnable(enable bool) error {
	disableConf := filepath.Join(v.configDir, "site", "00-disable.conf")

	if enable {
		if err := os.Remove(disableConf); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove disable config: %w", err)
		}
		return nil
	}

	// 禁用：所有请求重写到禁用页面
	content := fmt.Sprintf("# Auto-generated by AcePanel. DO NOT EDIT MANUALLY!\nRewriteEngine On\nRewriteRule ^ %s [L]\n", DisablePage)
	if err := os.WriteFile(disableConf, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write disable config: %w", err)
	}
	return nil
}

func (v *baseVhost) Listen() []types.Listen {
	var result []types.Listen
	// Apache 的监听写在 <VirtualHost *:80> 标签参数中
	for _, addr := range v.vhost.ArgValues() {
		result = append(result, types.Listen{Address: addr, Args: []string{}})
	}
	return result
}

func (v *baseVhost) SetListen(listens []types.Listen) error {
	var args []string
	for _, l := range listens {
		addr := l.Address
		// 只有端口号时补 *: 前缀
		if !strings.Contains(addr, ":") {
			addr = "*:" + addr
		}
		args = append(args, addr)
	}
	v.vhost.SetArgs(args...)
	return nil
}

func (v *baseVhost) ServerName() []string {
	names := make([]string, 0)
	if name := v.vhost.Value("ServerName"); name != "" {
		names = append(names, name)
	}
	for _, alias := range v.vhost.GetAll("ServerAlias") {
		names = append(names, argValues(alias.Args)...)
	}
	return names
}

func (v *baseVhost) SetServerName(serverName []string) error {
	if len(serverName) == 0 {
		return nil
	}
	v.vhost.Set("ServerName", serverName[0])
	v.vhost.RemoveAll("ServerAlias")
	if len(serverName) > 1 {
		v.vhost.Add("ServerAlias", serverName[1:]...)
	}
	return nil
}

func (v *baseVhost) Index() []string {
	if values := v.vhost.Values("DirectoryIndex"); values != nil {
		return values
	}
	return []string{}
}

func (v *baseVhost) SetIndex(index []string) error {
	if len(index) == 0 {
		v.vhost.Remove("DirectoryIndex")
		return nil
	}
	v.vhost.Set("DirectoryIndex", index...)
	return nil
}

func (v *baseVhost) Root() string {
	return v.vhost.Value("DocumentRoot")
}

func (v *baseVhost) SetRoot(root string) error {
	v.vhost.Set("DocumentRoot", root)

	// 同步更新 Directory 块路径
	if dirBlock := v.vhost.GetBlock("Directory"); dirBlock != nil {
		dirBlock.SetArgs(root)
	} else {
		v.vhost.AddBlock("Directory", root).Append(
			Dir("Options", "-Indexes", "+FollowSymLinks"),
			Dir("AllowOverride", "All"),
			Dir("Require", "all", "granted"),
		)
	}
	return nil
}

func (v *baseVhost) Includes() []types.IncludeFile {
	var result []types.IncludeFile
	for _, name := range []string{"Include", "IncludeOptional"} {
		for _, d := range v.vhost.GetAll(name) {
			if len(d.Args) > 0 {
				result = append(result, types.IncludeFile{Path: d.Args[0].Value})
			}
		}
	}
	return result
}

func (v *baseVhost) SetIncludes(includes []types.IncludeFile) error {
	v.vhost.RemoveAll("Include")
	v.vhost.RemoveAll("IncludeOptional")
	for _, inc := range includes {
		v.vhost.Add("Include", inc.Path)
	}
	return nil
}

func (v *baseVhost) AccessLog() string {
	cfg, err := ParseFragment(v.Config("020-access-log.conf", types.ScopeSite))
	if err != nil {
		return ""
	}
	if d := cfg.FindOne("CustomLog"); d != nil && len(d.Args) > 0 {
		return d.Args[0].Value
	}
	return ""
}

func (v *baseVhost) SetAccessLog(accessLog string) error {
	if accessLog == "" {
		return v.RemoveConfig("020-access-log.conf", types.ScopeSite)
	}
	cfg := &Config{}
	cfg.Append(Dir("CustomLog", accessLog, "combined"))
	return v.SetConfig("020-access-log.conf", "site", cfg.Export()+"\n")
}

func (v *baseVhost) ErrorLog() string {
	cfg, err := ParseFragment(v.Config("020-error-log.conf", types.ScopeSite))
	if err != nil {
		return ""
	}
	if d := cfg.FindOne("ErrorLog"); d != nil && len(d.Args) > 0 {
		return d.Args[0].Value
	}
	return ""
}

func (v *baseVhost) SetErrorLog(errorLog string) error {
	if errorLog == "" {
		return v.RemoveConfig("020-error-log.conf", types.ScopeSite)
	}
	cfg := &Config{}
	cfg.Append(Dir("ErrorLog", errorLog))
	return v.SetConfig("020-error-log.conf", "site", cfg.Export()+"\n")
}

func (v *baseVhost) Save() error {
	configFile := filepath.Join(v.configDir, "apache.conf")
	if err := os.WriteFile(configFile, []byte(v.config.Render()+"\n"), 0600); err != nil {
		return fmt.Errorf("failed to save config file: %w", err)
	}
	return nil
}

func (v *baseVhost) Reset() error {
	config, err := ParseString(v.defaultConf())
	if err != nil {
		return fmt.Errorf("failed to reset config: %w", err)
	}
	v.config = config
	if vhosts := config.VirtualHosts(); len(vhosts) > 0 {
		v.vhost = vhosts[0]
	}
	return nil
}

func (v *baseVhost) Config(name string, scope types.ConfigScope) string {
	content, err := os.ReadFile(filepath.Join(v.configDir, string(scope), name))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(content))
}

func (v *baseVhost) SetConfig(name string, scope types.ConfigScope, content string) error {
	return v.writeConfig(name, scope, "# Auto-generated by AcePanel. DO NOT EDIT MANUALLY!\n"+content)
}

func (v *baseVhost) SetRawConfig(name string, scope types.ConfigScope, content string) error {
	return v.writeConfig(name, scope, content)
}

func (v *baseVhost) writeConfig(name string, scope types.ConfigScope, content string) error {
	if err := os.WriteFile(filepath.Join(v.configDir, string(scope), name), []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}
	return nil
}

func (v *baseVhost) RemoveConfig(name string, scope types.ConfigScope) error {
	if err := os.Remove(filepath.Join(v.configDir, string(scope), name)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove config file: %w", err)
	}
	return nil
}

func (v *baseVhost) SSL() bool {
	return v.vhost.Has("SSLEngine") && strings.EqualFold(v.vhost.Value("SSLEngine"), "on")
}

func (v *baseVhost) SSLConfig() *types.SSLConfig {
	if !v.SSL() {
		return nil
	}

	config := &types.SSLConfig{
		Cert: v.vhost.Value("SSLCertificateFile"),
		Key:  v.vhost.Value("SSLCertificateKeyFile"),
	}
	if protocols := v.vhost.Values("SSLProtocol"); protocols != nil {
		config.Protocols = protocols
	}

	for _, h := range v.vhost.GetAll("Header") {
		if isHSTSHeader(h) {
			config.HSTS = true
			break
		}
	}
	config.OCSP = strings.EqualFold(v.vhost.Value("SSLUseStapling"), "on")
	for _, r := range v.vhost.GetAll("RewriteRule") {
		if argsContain(r.Args, "https://") {
			config.HTTPRedirect = true
			break
		}
	}

	return config
}

func (v *baseVhost) SetSSLConfig(cfg *types.SSLConfig) error {
	if cfg == nil {
		return fmt.Errorf("SSL config cannot be nil")
	}

	v.vhost.Set("SSLEngine", "on")
	if cfg.Cert != "" {
		v.vhost.Set("SSLCertificateFile", cfg.Cert)
	}
	if cfg.Key != "" {
		v.vhost.Set("SSLCertificateKeyFile", cfg.Key)
	}

	if len(cfg.Protocols) > 0 {
		v.vhost.Set("SSLProtocol", cfg.Protocols...)
	} else {
		v.vhost.Set("SSLProtocol", "all", "-SSLv2", "-SSLv3", "-TLSv1", "-TLSv1.1")
	}

	// HSTS：先移除旧的 HSTS Header 再添加，保留其他 Header
	if cfg.HSTS {
		v.vhost.RemoveFunc("Header", isHSTSHeader)
		v.vhost.Add("Header", "always", "set", "Strict-Transport-Security", HSTSValue)
	}

	if cfg.OCSP {
		v.vhost.Set("SSLUseStapling", "on")
	}

	// HTTP 强制跳转 HTTPS
	if cfg.HTTPRedirect {
		v.vhost.Set("RewriteEngine", "on")
		v.vhost.Add("RewriteCond", "%{HTTPS}", "off")
		v.vhost.Add("RewriteRule", "^(.*)$", "https://%{HTTP_HOST}%{REQUEST_URI}", "[R=301,L]")
	}

	// 确保监听 443 端口
	if !v.hasPort("443") {
		v.vhost.AppendArg("*:443")
	}

	return nil
}

func (v *baseVhost) ClearSSL() error {
	for _, name := range []string{"SSLEngine", "SSLCertificateFile", "SSLCertificateKeyFile", "SSLProtocol", "SSLCipherSuite", "SSLUseStapling"} {
		v.vhost.Remove(name)
	}
	v.vhost.RemoveFunc("Header", isHSTSHeader)
	v.vhost.Remove("RewriteEngine")
	v.vhost.RemoveAll("RewriteCond")
	v.vhost.RemoveAll("RewriteRule")

	// 移除 443 监听端口
	var newArgs []string
	for _, addr := range v.vhost.ArgValues() {
		if portOf(addr) != "443" {
			newArgs = append(newArgs, addr)
		}
	}
	if len(newArgs) == 0 {
		newArgs = []string{"*:80"}
	}
	v.vhost.SetArgs(newArgs...)
	return nil
}

// hasPort 判断 VirtualHost 是否监听指定端口
func (v *baseVhost) hasPort(port string) bool {
	return slices.ContainsFunc(v.vhost.ArgValues(), func(addr string) bool {
		return portOf(addr) == port
	})
}

func (v *baseVhost) RateLimit() *types.RateLimit {
	if v.vhost.Value("SetOutputFilter") != "RATE_LIMIT" {
		return nil
	}

	rateLimit := &types.RateLimit{}
	for _, d := range v.vhost.GetAll("SetEnv") {
		vals := argValues(d.Args)
		if len(vals) >= 2 && vals[0] == "rate-limit" {
			rateLimit.Rate, _ = strconv.Atoi(vals[1])
		}
	}
	return rateLimit
}

func (v *baseVhost) SetRateLimit(limit *types.RateLimit) error {
	// Apache mod_ratelimit 只支持流量限制，不支持并发连接限制
	if limit.Rate > 0 {
		v.vhost.Set("SetOutputFilter", "RATE_LIMIT")
		v.vhost.Set("SetEnv", "rate-limit", strconv.Itoa(limit.Rate))
	} else {
		v.vhost.Remove("SetOutputFilter")
		v.vhost.RemoveAll("SetEnv")
	}
	return nil
}

func (v *baseVhost) ClearRateLimit() error {
	v.vhost.Remove("SetOutputFilter")
	v.vhost.RemoveAll("SetEnv")
	return nil
}

func (v *baseVhost) BasicAuth() map[string]string {
	if !strings.EqualFold(v.vhost.Value("AuthType"), "Basic") {
		return nil
	}
	return map[string]string{
		"realm":     v.vhost.Value("AuthName"),
		"user_file": v.vhost.Value("AuthUserFile"),
	}
}

func (v *baseVhost) SetBasicAuth(auth map[string]string) error {
	realm := auth["realm"]
	if realm == "" {
		realm = "Restricted"
	}
	v.vhost.Set("AuthType", "Basic")
	v.vhost.Set("AuthName", realm)
	v.vhost.Set("AuthUserFile", auth["user_file"])
	v.vhost.Set("Require", "valid-user")
	return nil
}

func (v *baseVhost) ClearBasicAuth() error {
	for _, name := range []string{"AuthType", "AuthName", "AuthUserFile", "Require"} {
		v.vhost.Remove(name)
	}
	return nil
}

func (v *baseVhost) RealIP() *types.RealIP {
	// Apache 使用 mod_remoteip
	header := v.vhost.Value("RemoteIPHeader")
	if header == "" {
		return nil
	}

	var from []string
	for _, d := range v.vhost.GetAll("RemoteIPTrustedProxy") {
		if len(d.Args) > 0 {
			from = append(from, d.Args[0].Value)
		}
	}

	return &types.RealIP{From: from, Header: header}
}

func (v *baseVhost) SetRealIP(realIP *types.RealIP) error {
	v.vhost.Remove("RemoteIPHeader")
	v.vhost.RemoveAll("RemoteIPTrustedProxy")

	if realIP == nil || (len(realIP.From) == 0 && realIP.Header == "") {
		return nil
	}

	if realIP.Header != "" {
		v.vhost.Set("RemoteIPHeader", realIP.Header)
	}
	for _, ip := range realIP.From {
		if ip != "" {
			v.vhost.Add("RemoteIPTrustedProxy", ip)
		}
	}
	return nil
}

func (v *baseVhost) ClearRealIP() error {
	v.vhost.Remove("RemoteIPHeader")
	v.vhost.RemoveAll("RemoteIPTrustedProxy")
	return nil
}

func (v *baseVhost) Redirects() []types.Redirect {
	redirects, _ := parseRedirectFiles(filepath.Join(v.configDir, "site"))
	return redirects
}

func (v *baseVhost) SetRedirects(redirects []types.Redirect) error {
	return writeRedirectFiles(filepath.Join(v.configDir, "site"), redirects)
}

// ========== PHPVhost ==========

func (v *PHPVhost) PHP() uint {
	cfg, err := ParseFragment(v.Config("010-php.conf", types.ScopeSite))
	if err != nil {
		return 0
	}
	d := cfg.FindOne("FilesMatch.SetHandler")
	if d == nil || len(d.Args) == 0 {
		return 0
	}
	return phpVersionFromHandler(d.Args[0].Value)
}

func (v *PHPVhost) SetPHP(version uint) error {
	if version == 0 {
		return v.RemoveConfig("010-php.conf", types.ScopeSite)
	}

	// sock 路径格式: proxy:unix:/tmp/php-cgi-84.sock|fcgi://localhost/
	handler := fmt.Sprintf("proxy:unix:/tmp/php-cgi-%d.sock|fcgi://localhost/", version)
	cfg := &Config{}
	cfg.Append(Blk("FilesMatch", `\.php$`).Append(
		&Directive{Name: "SetHandler", Args: []Argument{dquote(handler)}},
	))
	return v.SetConfig("010-php.conf", "site", cfg.Export()+"\n")
}

// phpVersionFromHandler 从 SetHandler 值提取 PHP 版本号
func phpVersionFromHandler(handler string) uint {
	idx := strings.Index(handler, "php-cgi-")
	if idx == -1 {
		return 0
	}
	var version uint
	if _, err := fmt.Sscanf(handler[idx:], "php-cgi-%d.sock", &version); err != nil {
		return 0
	}
	return version
}

// ========== ProxyVhost ==========

func (v *ProxyVhost) Proxies() []types.Proxy {
	proxies, _ := parseProxyFiles(filepath.Join(v.configDir, "site"))
	return proxies
}

func (v *ProxyVhost) SetProxies(proxies []types.Proxy) error {
	return writeProxyFiles(filepath.Join(v.configDir, "site"), proxies)
}

func (v *ProxyVhost) ClearProxies() error {
	return clearProxyFiles(filepath.Join(v.configDir, "site"))
}

func (v *ProxyVhost) Upstreams() []types.Upstream {
	upstreams, _ := parseBalancerFiles(filepath.Join(v.configDir, "shared"))
	return upstreams
}

func (v *ProxyVhost) SetUpstreams(upstreams []types.Upstream) error {
	return writeBalancerFiles(filepath.Join(v.configDir, "shared"), upstreams)
}

func (v *ProxyVhost) ClearUpstreams() error {
	return clearBalancerFiles(filepath.Join(v.configDir, "shared"))
}

// isHSTSHeader 判断是否为 HSTS 响应头指令
func isHSTSHeader(d *Directive) bool {
	return argsContain(d.Args, "Strict-Transport-Security")
}

// argsContain 判断参数值中是否有任一含子串
func argsContain(args []Argument, sub string) bool {
	for _, a := range args {
		if strings.Contains(a.Value, sub) {
			return true
		}
	}
	return false
}

// portOf 提取监听地址的端口部分，如 *:443 -> 443
func portOf(addr string) string {
	if idx := strings.LastIndex(addr, ":"); idx >= 0 {
		return addr[idx+1:]
	}
	return ""
}
