package apache

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/samber/lo"

	"github.com/acepanel/panel/v3/pkg/webserver/conf"
	"github.com/acepanel/panel/v3/pkg/webserver/types"
)

// StaticVhost 纯静态虚拟主机
type StaticVhost struct {
	*baseVhost
}

// PHPVhost PHP 虚拟主机
type PHPVhost struct {
	*baseVhost
}

// ProxyVhost 反向代理虚拟主机
type ProxyVhost struct {
	*baseVhost
}

// baseVhost Apache 虚拟主机基础实现
type baseVhost struct {
	config     *conf.Config
	vhost      *conf.Directive // 主 VirtualHost 块，写盘时按端口拆成明文与 TLS 两个块
	httpsPorts map[string]bool // 走 TLS 的端口
	configDir  string
	siteName   string
}

// newBaseVhost 创建基础虚拟主机实例
func newBaseVhost(configDir string) (*baseVhost, error) {
	if configDir == "" {
		return nil, errors.New("config directory is required")
	}

	v := &baseVhost{
		httpsPorts: make(map[string]bool),
		configDir:  configDir,
		siteName:   filepath.Base(filepath.Dir(configDir)),
	}

	var config *conf.Config
	configFile := filepath.Join(configDir, ConfigName)
	if _, err := os.Stat(configFile); err == nil {
		config, err = ParseFile(configFile)
		if err != nil {
			return nil, fmt.Errorf("failed to parse apache config: %w", err)
		}
	}

	if config == nil {
		var err error
		config, err = ParseString(v.defaultConf())
		if err != nil {
			return nil, fmt.Errorf("failed to parse default config: %w", err)
		}
	}

	v.config = config
	v.loadVhosts()

	return v, nil
}

// loadVhosts 把写盘时拆开的明文与 TLS 两个 VirtualHost 合回单一逻辑视图
func (v *baseVhost) loadVhosts() {
	clear(v.httpsPorts)
	vhosts := v.config.Blocks("VirtualHost")
	if len(vhosts) == 0 {
		v.vhost = v.config.AddBlock("VirtualHost", "*:80")
		return
	}

	main := vhosts[0]
	for _, b := range vhosts {
		if strings.EqualFold(b.Value("SSLEngine"), "on") {
			main = b
			for _, addr := range b.Values() {
				v.httpsPorts[portOf(addr)] = true
			}
			break
		}
	}

	var addrs []string
	for _, b := range vhosts {
		if b != main {
			addrs = append(addrs, b.Values()...)
		}
	}
	if len(addrs) > 0 {
		main.SetArgs(append(addrs, main.Values()...)...)
		v.config.RemoveFunc("VirtualHost", func(d *conf.Directive) bool { return d != main })
	}
	v.vhost = main
}

// defaultConf 返回替换好站点名的默认配置模板
func (v *baseVhost) defaultConf() string {
	return strings.ReplaceAll(DefaultVhostConf, "/opt/ace/sites/default", "/opt/ace/sites/"+v.siteName)
}

// NewStaticVhost 创建纯静态虚拟主机实例
func NewStaticVhost(configDir string) (*StaticVhost, error) {
	base, err := newBaseVhost(configDir)
	if err != nil {
		return nil, err
	}
	return &StaticVhost{baseVhost: base}, nil
}

// NewPHPVhost 创建 PHP 虚拟主机实例
func NewPHPVhost(configDir string) (*PHPVhost, error) {
	base, err := newBaseVhost(configDir)
	if err != nil {
		return nil, err
	}
	return &PHPVhost{baseVhost: base}, nil
}

// NewProxyVhost 创建反向代理虚拟主机实例
func NewProxyVhost(configDir string) (*ProxyVhost, error) {
	base, err := newBaseVhost(configDir)
	if err != nil {
		return nil, err
	}
	return &ProxyVhost{baseVhost: base}, nil
}

func (v *baseVhost) Enable() bool {
	disableConf := filepath.Join(v.configDir, "site", "00-disable.conf")
	_, err := os.Stat(disableConf)
	return os.IsNotExist(err)
}

func (v *baseVhost) SetEnable(enable bool) error {
	disableConf := filepath.Join(v.configDir, "site", "00-disable.conf")

	if enable {
		if err := os.Remove(disableConf); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove disable config: %w", err)
		}
		return nil
	}

	// 禁用：所有请求重写到禁用页面
	content := fmt.Sprintf("# Auto-generated by AcePanel. DO NOT EDIT MANUALLY!\nRewriteEngine On\nRewriteRule ^ %s [L]\n", DisablePage)
	if err := os.WriteFile(disableConf, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write disable config: %w", err)
	}
	return nil
}

// Default 默认站点切换只在 nginx 与 Caddy 支持
func (v *baseVhost) Default() bool {
	return false
}

func (v *baseVhost) SetDefault(bool) error {
	return nil
}

func (v *baseVhost) Listen() []types.Listen {
	var result []types.Listen
	// Apache 的监听写在 <VirtualHost *:80> 标签参数中，是否走 TLS 取自加载时记下的 httpsPorts
	for _, addr := range v.vhost.Values() {
		args := []string{}
		if v.httpsPorts[portOf(addr)] {
			args = append(args, "ssl")
		}
		result = append(result, types.Listen{Address: addr, Args: args})
	}
	return result
}

func (v *baseVhost) SetListen(listens []types.Listen) error {
	var args []string
	clear(v.httpsPorts)
	for _, l := range listens {
		addr := l.Address
		// 只有端口号时补 *: 前缀
		if !strings.Contains(addr, ":") {
			addr = "*:" + addr
		}
		args = append(args, addr)
		if slices.Contains(l.Args, "ssl") {
			v.httpsPorts[portOf(addr)] = true
		}
	}
	v.vhost.SetArgs(args...)
	return nil
}

func (v *baseVhost) ServerName() []string {
	names := make([]string, 0)
	if name := v.vhost.Value("ServerName"); name != "" {
		names = append(names, name)
	}
	for _, alias := range v.vhost.GetAll("ServerAlias") {
		names = append(names, alias.Values()...)
	}
	return names
}

func (v *baseVhost) SetServerName(serverName []string) error {
	if len(serverName) == 0 {
		return nil
	}
	v.vhost.Set("ServerName", serverName[0])
	v.vhost.Remove("ServerAlias")
	if len(serverName) > 1 {
		v.vhost.Add("ServerAlias", serverName[1:]...)
	}
	return nil
}

func (v *baseVhost) Index() []string {
	if values := v.vhost.Get("DirectoryIndex").Values(); values != nil {
		return values
	}
	return []string{}
}

func (v *baseVhost) SetIndex(index []string) error {
	if len(index) == 0 {
		v.vhost.Remove("DirectoryIndex")
		return nil
	}
	v.vhost.Set("DirectoryIndex", index...)
	return nil
}

func (v *baseVhost) Root() string {
	return v.vhost.Value("DocumentRoot")
}

func (v *baseVhost) SetRoot(root string) error {
	v.vhost.Set("DocumentRoot", root)

	// 同步更新 Directory 块路径
	if dirBlock := v.vhost.GetBlock("Directory"); dirBlock != nil {
		dirBlock.SetArgs(root)
	} else {
		v.vhost.AddBlock("Directory", root).Append(
			conf.Dir("Options", "-Indexes", "+FollowSymLinks"),
			conf.Dir("AllowOverride", "All"),
			conf.Dir("Require", "all", "granted"),
		)
	}
	return nil
}

func (v *baseVhost) Includes() []types.IncludeFile {
	var result []types.IncludeFile
	for _, name := range []string{"Include", "IncludeOptional"} {
		for _, d := range v.vhost.GetAll(name) {
			if len(d.Args) > 0 {
				result = append(result, types.IncludeFile{Path: d.Args[0].Value})
			}
		}
	}
	return result
}

func (v *baseVhost) SetIncludes(includes []types.IncludeFile) error {
	v.vhost.Remove("Include")
	v.vhost.Remove("IncludeOptional")
	for _, inc := range includes {
		v.vhost.Add("Include", inc.Path)
	}
	return nil
}

func (v *baseVhost) AccessLog() string {
	cfg, err := ParseFragment(v.Config("020-access-log.conf", types.ScopeSite))
	if err != nil {
		return ""
	}
	if d := cfg.FindOne("CustomLog"); d != nil && len(d.Args) > 0 {
		return d.Args[0].Value
	}
	return ""
}

func (v *baseVhost) SetAccessLog(accessLog string) error {
	if accessLog == "" {
		return v.RemoveConfig("020-access-log.conf", types.ScopeSite)
	}
	cfg := &conf.Config{}
	cfg.Append(conf.Dir("CustomLog", accessLog, "combined"))
	return v.SetConfig("020-access-log.conf", "site", Export(cfg)+"\n")
}

func (v *baseVhost) ErrorLog() string {
	cfg, err := ParseFragment(v.Config("020-error-log.conf", types.ScopeSite))
	if err != nil {
		return ""
	}
	if d := cfg.FindOne("ErrorLog"); d != nil && len(d.Args) > 0 {
		return d.Args[0].Value
	}
	return ""
}

func (v *baseVhost) SetErrorLog(errorLog string) error {
	if errorLog == "" {
		return v.RemoveConfig("020-error-log.conf", types.ScopeSite)
	}
	cfg := &conf.Config{}
	cfg.Append(conf.Dir("ErrorLog", errorLog))
	return v.SetConfig("020-error-log.conf", "site", Export(cfg)+"\n")
}

func (v *baseVhost) Save() error {
	configFile := filepath.Join(v.configDir, ConfigName)
	if err := os.WriteFile(configFile, []byte(Render(v.expand())+"\n"), 0600); err != nil {
		return fmt.Errorf("failed to save config file: %w", err)
	}
	return nil
}

// expand TLS 端口与明文端口各占一个 VirtualHost。SSLEngine 按 VirtualHost 生效，
// 同一个块里混用两种端口会让明文端口直接断连，连强制跳转都执行不到
func (v *baseVhost) expand() *conf.Config {
	plainAddrs, tlsAddrs := []string{}, []string{}
	for _, addr := range v.vhost.Values() {
		if v.httpsPorts[portOf(addr)] {
			tlsAddrs = append(tlsAddrs, addr)
		} else {
			plainAddrs = append(plainAddrs, addr)
		}
	}
	if len(plainAddrs) == 0 || len(tlsAddrs) == 0 {
		return v.config
	}

	plain := v.vhost.Clone()
	plain.SetArgs(plainAddrs...)
	plain.Filter(func(n conf.Node) bool {
		d, ok := n.(*conf.Directive)
		return !ok || !strings.HasPrefix(d.Name, "SSL")
	})
	plain.RemoveFunc("Header", isHSTSHeader)

	config := &conf.Config{Block: *v.config.Clone()}
	config.Blocks("VirtualHost")[0].SetArgs(tlsAddrs...)
	config.Append(&conf.Blank{}, plain)

	return config
}

func (v *baseVhost) Reset() error {
	config, err := ParseString(v.defaultConf())
	if err != nil {
		return fmt.Errorf("failed to reset config: %w", err)
	}
	v.config = config
	v.loadVhosts()
	return nil
}

func (v *baseVhost) Config(name string, scope types.ConfigScope) string {
	content, err := os.ReadFile(filepath.Join(v.configDir, string(scope), name))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(content))
}

func (v *baseVhost) SetConfig(name string, scope types.ConfigScope, content string) error {
	return v.writeConfig(name, scope, "# Auto-generated by AcePanel. DO NOT EDIT MANUALLY!\n"+content)
}

func (v *baseVhost) SetRawConfig(name string, scope types.ConfigScope, content string) error {
	return v.writeConfig(name, scope, content)
}

func (v *baseVhost) writeConfig(name string, scope types.ConfigScope, content string) error {
	if err := os.WriteFile(filepath.Join(v.configDir, string(scope), name), []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}
	return nil
}

func (v *baseVhost) RemoveConfig(name string, scope types.ConfigScope) error {
	if err := os.Remove(filepath.Join(v.configDir, string(scope), name)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove config file: %w", err)
	}
	return nil
}

func (v *baseVhost) SSL() bool {
	return v.vhost.Has("SSLEngine") && strings.EqualFold(v.vhost.Value("SSLEngine"), "on")
}

func (v *baseVhost) SSLConfig() *types.SSLConfig {
	if !v.SSL() {
		return nil
	}

	config := &types.SSLConfig{
		Cert: v.vhost.Value("SSLCertificateFile"),
		Key:  v.vhost.Value("SSLCertificateKeyFile"),
	}
	config.Protocols = parseSSLProtocols(v.vhost.Get("SSLProtocol").Values())

	for _, h := range v.vhost.GetAll("Header") {
		if isHSTSHeader(h) {
			config.HSTS = true
			break
		}
	}
	config.OCSP = strings.EqualFold(v.vhost.Value("SSLUseStapling"), "on")
	for _, r := range v.vhost.GetAll("RewriteRule") {
		if argsContain(r.Args, "https://") {
			config.HTTPRedirect = true
			break
		}
	}

	return config
}

func (v *baseVhost) SetSSLConfig(cfg *types.SSLConfig) error {
	if cfg == nil {
		return errors.New("SSL config cannot be nil")
	}

	v.vhost.Set("SSLEngine", "on")
	if cfg.Cert != "" {
		v.vhost.Set("SSLCertificateFile", cfg.Cert)
	}
	if cfg.Key != "" {
		v.vhost.Set("SSLCertificateKeyFile", cfg.Key)
	}

	v.vhost.Set("SSLProtocol", sslProtocolArgs(cfg.Protocols)...)

	// 先移除旧的再按需添加，保留其他 Header；只加不减会让开关关不掉，且重复保存时不断累加
	v.vhost.RemoveFunc("Header", isHSTSHeader)
	if cfg.HSTS {
		v.vhost.Add("Header", "always", "set", "Strict-Transport-Security", HSTSValue)
	}

	if cfg.OCSP {
		v.vhost.Set("SSLUseStapling", "on")
	} else {
		v.vhost.Remove("SSLUseStapling")
	}

	v.removeHTTPRedirect()
	if cfg.HTTPRedirect {
		v.vhost.Set("RewriteEngine", "on")
		v.vhost.Add("RewriteCond", "%{HTTPS}", "off")
		v.vhost.Add("RewriteRule", "^(.*)$", "https://%{HTTP_HOST}%{REQUEST_URI}", "[R=301,L]")
	}

	// 监听没标 ssl 时按 443 兜底，否则整站会落进明文块
	if len(v.httpsPorts) == 0 {
		v.httpsPorts["443"] = true
		if !v.hasPort("443") {
			v.vhost.AppendArg("*:443")
		}
	}

	return nil
}

// sslProtocolArgs 面板的协议列表转 Apache 语法。Apache 只认带 +/- 前缀的增减写法，
// 直接列出多个协议名会以 "Illegal protocol" 拒载整份配置
func sslProtocolArgs(protocols []string) []string {
	if len(protocols) == 0 {
		protocols = []string{"TLSv1.2", "TLSv1.3"}
	}
	return append([]string{"-all"}, lo.Map(protocols, func(p string, _ int) string {
		return "+" + strings.TrimPrefix(p, "+")
	})...)
}

// parseSSLProtocols 从 Apache 语法还原协议列表，只取显式开启的项
func parseSSLProtocols(args []string) []string {
	return lo.FilterMap(args, func(a string, _ int) (string, bool) {
		return strings.CutPrefix(a, "+")
	})
}

func (v *baseVhost) removeHTTPRedirect() {
	v.vhost.RemoveFunc("RewriteCond", func(d *conf.Directive) bool {
		return d.Arg(0) == "%{HTTPS}" && strings.EqualFold(d.Arg(1), "off")
	})
	v.vhost.RemoveFunc("RewriteRule", func(d *conf.Directive) bool {
		return argsContain(d.Args, "https://%{HTTP_HOST}")
	})
}

func (v *baseVhost) ClearSSL() error {
	for _, name := range []string{"SSLEngine", "SSLCertificateFile", "SSLCertificateKeyFile", "SSLProtocol", "SSLCipherSuite", "SSLUseStapling"} {
		v.vhost.Remove(name)
	}
	v.vhost.RemoveFunc("Header", isHSTSHeader)
	v.removeHTTPRedirect()
	clear(v.httpsPorts)

	var newArgs []string
	for _, addr := range v.vhost.Values() {
		if portOf(addr) != "443" {
			newArgs = append(newArgs, addr)
		}
	}
	if len(newArgs) == 0 {
		newArgs = []string{"*:80"}
	}
	v.vhost.SetArgs(newArgs...)
	return nil
}

// hasPort 判断 VirtualHost 是否监听指定端口
func (v *baseVhost) hasPort(port string) bool {
	return slices.ContainsFunc(v.vhost.Values(), func(addr string) bool {
		return portOf(addr) == port
	})
}

func (v *baseVhost) RateLimit() *types.RateLimit {
	if v.vhost.Value("SetOutputFilter") != "RATE_LIMIT" {
		return nil
	}

	rateLimit := &types.RateLimit{}
	for _, d := range v.vhost.GetAll("SetEnv") {
		vals := d.Values()
		if len(vals) >= 2 && vals[0] == "rate-limit" {
			rateLimit.Rate, _ = strconv.Atoi(vals[1])
		}
	}
	return rateLimit
}

func (v *baseVhost) SetRateLimit(limit *types.RateLimit) error {
	// Apache mod_ratelimit 只支持流量限制，不支持并发连接限制
	if limit.Rate > 0 {
		v.vhost.Set("SetOutputFilter", "RATE_LIMIT")
		v.vhost.Set("SetEnv", "rate-limit", strconv.Itoa(limit.Rate))
	} else {
		v.vhost.Remove("SetOutputFilter")
		v.vhost.Remove("SetEnv")
	}
	return nil
}

func (v *baseVhost) ClearRateLimit() error {
	v.vhost.Remove("SetOutputFilter")
	v.vhost.Remove("SetEnv")
	return nil
}

func (v *baseVhost) BasicAuth() []types.BasicAuth {
	var auths []types.BasicAuth
	for _, block := range v.vhost.FindBlocks("Location") {
		if len(block.Args) > 0 && strings.EqualFold(block.Value("AuthType"), "Basic") {
			auths = append(auths, types.BasicAuth{Path: block.Arg(0), UserFile: strings.TrimSuffix(block.Value("AuthUserFile"), userFileSuffix)})
		}
	}
	if len(auths) > 0 {
		return auths
	}

	// 兼容旧版 vhost 级整站配置
	if strings.EqualFold(v.vhost.Value("AuthType"), "Basic") {
		return []types.BasicAuth{{Path: "/", UserFile: v.vhost.Value("AuthUserFile")}}
	}
	return nil
}

// userFileSuffix 加密用户文件的后缀，与面板可回读的明文 htpasswd 并存
const userFileSuffix = ".apache"

func (v *baseVhost) SetBasicAuth(auths []types.BasicAuth) error {
	_ = v.ClearBasicAuth()
	// Location 块后声明者覆盖先声明者，按路径长度升序写出使更精确的目录规则生效；
	// 且 Location 在合并顺序上晚于 Directory 块，认证不会被 Require all granted 覆盖
	auths = slices.SortedStableFunc(slices.Values(auths), func(a, b types.BasicAuth) int {
		return len(a.Path) - len(b.Path)
	})
	for _, auth := range auths {
		// 缺文件时照写规则，Apache 找不到 AuthUserFile 会拒绝访问，比放行安全
		if _, err := types.WriteUserFile(auth.UserFile, userFileSuffix, ":"); err != nil {
			return err
		}
		v.vhost.AddBlock("Location", auth.Path).Append(
			conf.Dir("AuthType", "Basic"),
			conf.Dir("AuthName", "Restricted"),
			conf.Dir("AuthUserFile", auth.UserFile+userFileSuffix),
			conf.Dir("Require", "valid-user"),
		)
	}
	return nil
}

func (v *baseVhost) ClearBasicAuth() error {
	// 清除旧版 vhost 级指令
	for _, name := range []string{"AuthType", "AuthName", "AuthUserFile"} {
		v.vhost.Remove(name)
	}
	v.vhost.RemoveFunc("Require", func(d *conf.Directive) bool {
		return len(d.Args) == 1 && d.Args[0].Value == "valid-user"
	})
	v.vhost.RemoveFunc("Location", func(d *conf.Directive) bool {
		return d.Block != nil && d.Has("AuthType")
	})
	return nil
}

func (v *baseVhost) RealIP() *types.RealIP {
	header := v.vhost.Value("RemoteIPHeader")
	if header == "" {
		return nil
	}

	var from []string
	for _, d := range v.vhost.GetAll("RemoteIPTrustedProxy") {
		if len(d.Args) > 0 {
			from = append(from, d.Args[0].Value)
		}
	}

	return &types.RealIP{From: from, Header: header}
}

func (v *baseVhost) SetRealIP(realIP *types.RealIP) error {
	v.vhost.Remove("RemoteIPHeader")
	v.vhost.Remove("RemoteIPTrustedProxy")

	if realIP == nil || (len(realIP.From) == 0 && realIP.Header == "") {
		return nil
	}

	if realIP.Header != "" {
		v.vhost.Set("RemoteIPHeader", realIP.Header)
	}
	for _, ip := range realIP.From {
		if ip != "" {
			v.vhost.Add("RemoteIPTrustedProxy", ip)
		}
	}
	return nil
}

func (v *baseVhost) ClearRealIP() error {
	v.vhost.Remove("RemoteIPHeader")
	v.vhost.Remove("RemoteIPTrustedProxy")
	return nil
}

func (v *baseVhost) Redirects() []types.Redirect {
	redirects, _ := parseRedirectFiles(filepath.Join(v.configDir, "site"))
	return redirects
}

func (v *baseVhost) SetRedirects(redirects []types.Redirect) error {
	return writeRedirectFiles(filepath.Join(v.configDir, "site"), redirects)
}

// ========== PHPVhost ==========

func (v *PHPVhost) PHP() uint {
	cfg, err := ParseFragment(v.Config("010-php.conf", types.ScopeSite))
	if err != nil {
		return 0
	}
	d := cfg.FindOne("FilesMatch.SetHandler")
	if d == nil || len(d.Args) == 0 {
		return 0
	}
	return phpVersionFromHandler(d.Args[0].Value)
}

func (v *PHPVhost) SetPHP(version uint) error {
	if version == 0 {
		return v.RemoveConfig("010-php.conf", types.ScopeSite)
	}

	handler := fmt.Sprintf("proxy:unix:/tmp/php-cgi-%d.sock|fcgi://localhost/", version)
	cfg := &conf.Config{}
	cfg.Append(conf.Blk("FilesMatch", `\.php$`).Append(
		&conf.Directive{Name: "SetHandler", Args: []conf.Arg{dquote(handler)}},
	))
	return v.SetConfig("010-php.conf", "site", Export(cfg)+"\n")
}

// phpVersionFromHandler 从 SetHandler 值提取 PHP 版本号
func phpVersionFromHandler(handler string) uint {
	idx := strings.Index(handler, "php-cgi-")
	if idx == -1 {
		return 0
	}
	var version uint
	if _, err := fmt.Sscanf(handler[idx:], "php-cgi-%d.sock", &version); err != nil {
		return 0
	}
	return version
}

// ========== ProxyVhost ==========

func (v *ProxyVhost) Proxies() []types.Proxy {
	proxies, _ := parseProxyFiles(filepath.Join(v.configDir, "site"))
	return proxies
}

func (v *ProxyVhost) SetProxies(proxies []types.Proxy) error {
	return writeProxyFiles(filepath.Join(v.configDir, "site"), proxies, v.upstreamNames())
}

// upstreamNames 已写入的上游名，代理目标指向其中之一时要换成 balancer 地址
func (v *ProxyVhost) upstreamNames() []string {
	return balancerNames(filepath.Join(v.configDir, "shared"))
}

func (v *ProxyVhost) ClearProxies() error {
	return clearProxyFiles(filepath.Join(v.configDir, "site"))
}

func (v *ProxyVhost) Upstreams() []types.Upstream {
	upstreams, _ := parseBalancerFiles(filepath.Join(v.configDir, "shared"))
	return upstreams
}

func (v *ProxyVhost) SetUpstreams(upstreams []types.Upstream) error {
	return writeBalancerFiles(filepath.Join(v.configDir, "shared"), upstreams)
}

func (v *ProxyVhost) ClearUpstreams() error {
	return clearBalancerFiles(filepath.Join(v.configDir, "shared"))
}

// isHSTSHeader 判断是否为 HSTS 响应头指令
func isHSTSHeader(d *conf.Directive) bool {
	return argsContain(d.Args, "Strict-Transport-Security")
}

// argsContain 判断参数值中是否有任一含子串
func argsContain(args []conf.Arg, sub string) bool {
	for _, a := range args {
		if strings.Contains(a.Value, sub) {
			return true
		}
	}
	return false
}

// portOf 提取监听地址的端口部分，如 *:443 -> 443
func portOf(addr string) string {
	if idx := strings.LastIndex(addr, ":"); idx >= 0 {
		return addr[idx+1:]
	}
	return ""
}
